Devolutions/devolutions-gateway

- Cargo.toml
- jet-proto/Cargo.toml
- jet-proto/src/lib.rs
- src/config.rs
- src/main.rs
The clap and log dependencies were updated to simplify the import of macros and remove the macro_use statements.
> Upgrade to Rust edition 2018.

- .gitignore
- Cargo.lock
For executables it is recommended to distributed Cargo.lock, this way a build always uses the same version for dependencies.
> Add Cargo.lock to the repository.

- Cargo.lock
cargo-audit reports that we are using a vulnerable version of smallvec. Updating the dependencies fixes the issue.
```
devolutions-jet (master)> cargo audit
Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
Loaded 31 security advisories (from /home/sduquette/.cargo/advisory-db)
Scanning Cargo.lock for vulnerabilities (218 crate dependencies)
error: Vulnerable crates found!
ID:	 RUSTSEC-2019-0009
Crate:	 smallvec
Version: 0.6.9
Date:	 2019-06-06
URL:	 https://github.com/servo/rust-smallvec/issues/148
Title:	 Double-free and use-after-free in SmallVec::grow()
Solution: upgrade to: >= 0.6.10
```
> Update the dependencies

- src/config.rs
- src/http/controllers/jet.rs
- src/http/http_server.rs
- src/http/middlewares/auth.rs
- src/http/middlewares/mod.rs
- src/http/mod.rs
- src/jet/association.rs
- tests/common.rs
Changes:
- Fixed the command line parameters (use - instead of _.  jet-instance and not jet_instance for example)
- Added api_key. If provided, call to POST /jet/association/<id> has to contain the api_key. If not provided, all calls are accepted.  Env variable : JET_API_KEY or --api-key on command line
- The route /jet/gater/<id> is now /jet/association/<id>/candidates
> Jet improvement

- src/config.rs
- src/http/controllers/jet.rs
- src/main.rs
You can now specify the external url for a listener. You can specify it with the listener, separated with a comma
**-l tcp://0.0.0.0:8080**
The external url will be tcp://JET_INSTANCE:8080 where JET_INSTANCE is the value of jet-instance parameter
**-l tcp://0.0.0.0:8080,tcp://jet.io:8080**
The external url will be tcp://jet.io:8080
**-l tcp://0.0.0.0:8080,tcp://<jet_intance>:8080**
The external url will be tcp://JET_INSTANCE:8080 where JET_INSTANCE is the value of jet-instance parameter
> Accept external url on command line

- src/config.rs
You can specify a list of listeners, separated with ;
Example : 
JET_LISTENERS=tcp://0.0.0.0:8080,tcp://<jet_instance>:8080;ws://0.0.0.0:9090,wss://<jet_instance>:443
> Added env. variable JET_LISTENERS to add a list of listeners

- Cargo.toml
- src/logger.rs
- src/main.rs
- src/proxy.rs
- src/rdp/sequence_future/mcs.rs
- src/rdp/sequence_future/negotiation.rs
- src/rdp/sequence_future/nla.rs
- src/rdp/sequence_future/post_mcs.rs
- src/transport/tcp.rs
- src/transport/ws.rs
The first batch of changes for Jet optimization:
1. Proxy moved out to the separate module;
2. Added LevelFilter to the AsyncDrain, so now Jet does not rain "channel overflow" messages to logs. The performance was improved by up to 25%;
3. Replaced debug logs in RDP connection sequence and in the "hot" places (such as TcpJetStream::poll, TcpJetSink::start_send) with trace logs, removed trace logs from release builds. Thus, a release build will not spend time to canceled trace logs, which can be viewed at any time in debug builds :) The performance was improved by up to 15%. @fdubois1 are you agree with these changes?
> Logs optimization

- Cargo.lock
- Cargo.toml
- src/http/controllers/jet.rs
- src/jet.rs
- src/jet/association.rs
- src/jet/candidate.rs
- src/websocket_client.rs
We can now add a query param when we get all associations.  We add ?detail=true to get something like this :
[
{
"id": "815d02a7-7316-41d5-8111-43bc9ffc8f00",
"version": 2,
"bytes_sent": 720,
"bytes_recv": 1712,
"candidates": [
{
"id": "055a01aa-bd34-42c5-b6fe-19aa18afc6e8",
"url": "tcp://10.1.21.112:8080/",
"state": "Connected",
"association_id": "815d02a7-7316-41d5-8111-43bc9ffc8f00",
"transport_type": "Tcp",
"bytes_sent": 720,
"bytes_recv": 1712
},
{
"id": "c4173e98-8c80-4eb6-8046-ca5721ed7e35",
"url": "tcp://10.1.21.112:8081/",
"state": "Final",
"association_id": "815d02a7-7316-41d5-8111-43bc9ffc8f00",
"transport_type": "Tcp",
"bytes_sent": 0,
"bytes_recv": 0
},
{
"id": "47c6877b-910b-4a06-9677-144b6ff3c014",
"url": "wss://566c2e8f.ngrok.io/",
"state": "Final",
"association_id": …
> Added option to get candidate details when we get association list

- Cargo.lock
- Cargo.toml
Moving to 0.9.0 to deploy a new jet version soon
> Version bump from 0.8.0 to 0.9.0

- Cargo.lock
This fixes a vulnerability reported by `cargo audit`.
Reference: https://rustsec.org/advisories/RUSTSEC-2020-0007.html
```
ID:       RUSTSEC-2020-0007
Crate:    bitvec
Version:  0.17.1
Date:     2020-03-27
URL:      https://rustsec.org/advisories/RUSTSEC-2020-0007
Title:    use-after or double free of allocated memory
Solution:  upgrade to >= 0.17.4
Dependency tree: 
bitvec 0.17.1
└── ironrdp 0.4.0
└── devolutions-jet 0.11.0
```
> Update the bitvec dependency

- src/lib.rs
- src/main.rs
This is to deal with a limitation of cargo-fuzz, fuzzers can only use code from librairies. The workaround is to move the code to lib.rs and import it in main.rs. I'm currently working on fuzzers, they will be added in another pull request.
Tests are passing with the exception of `rdp_with_nla_ntlm` which is also failing on the master branch.
> Move the code in a library

- Dockerfile
Add ca-certificates package while we are at it, and remove libssl1.1 as it shouldn't be needed (unless pulled by curl again, but only as an indirect dependency).
Adding curl is necessary to use it for Docker health check commands like in the other containers we have.
> Add curl to docker container

- Cargo.lock
- Cargo.toml
- src/logger.rs
Dorenavant, les traces ressembleront a ceci (ajout du module a la fin): 
2020-05-11 09:53:39:951218 INFO Configuring http router, **module: [devolutions_jet::http::http_server]**
2020-05-11 09:53:39:951591 INFO Saphir successfully started and listening on http://0.0.0.0:10256/, **module: [saphir::server]**
> Added module in log + version bump

- src/config.rs
- src/http/controllers/health.rs
- src/http/controllers/jet.rs
- src/http/http_server.rs
- src/jet_client.rs
- src/proxy.rs
- src/service.rs
- All env. variable are now DGATEWAY_XYZ
Parameters added:
- farm-name
- application-protocols (only rdp and wayk can be specified for now. Only rdp is used to replace old rdp parameter)
Parameters renamed:
- jet-instance --> hostname
Parameters removed:
- rdp
Parameters updated:
- certificate-file and private-key-file can specify a full path OR a filename and the config path will be added
- listeners has to be defined with * instead of <jet_instance> (example : -l tcp://*:8080,tcp://*:8080)
Other:
- Health check will return the string : "Devolutions Gateway "<hostname>" is alive and healthy."
> Cli update

- src/config.rs
Si un fichier est fourni, c'est probablement que l'on veut appliquer cette config. Ainsi, si le fichier de config ne peut être lu ou le format n'est pas bon, il y aura un panic afin d'éviter de démarrer avec des valeurs par défaut.  On imprime l'erreur afin d'orienter les recherches. On aura des erreurs de ce genre : 
`A configuration file has been provided (/etc/devolutions-gateway/gateway.json), but it can't be used: invalid type: string "true", expected a boolean at line 13 column 26', src/config.rs:256:19`
`A configuration file has been provided (/etc/devolutions-gateway/gateway.json), but it can't be used: missing field `Listeners` at line 6 column 1', src/config.rs:256:19`
> Panic if a configuration file is provided but can't be read or it has a bad format

- Cargo.lock
- Cargo.toml
- src/http/controllers/health.rs
- src/http/controllers/jet.rs
- src/http/controllers/sessions.rs
- src/jet_client.rs
- src/proxy.rs
- src/service.rs
- src/utils/association.rs
- src/websocket_client.rs
> Fixed issues after async-upgrade branch review

- ci/azure-pipelines.yaml
- ci/tlk.ps1
Refactor azure-pipelines.yaml to use tlk.ps1 as much as possible, with highly regular YAML sections using as much variables as possible. I guess we could come up with reusable YAML templates in the end and avoid copy/pasting the almost-identical sections we now have.
> Use tlk.ps1 for build + packaging on all platforms

- Cargo.lock
- Cargo.toml
- jetsocat/Cargo.toml
- jetsocat/proxy/Cargo.toml
- jetsocat/proxy/README.md
- jetsocat/proxy/src/bin/socks_test.rs
- jetsocat/proxy/src/lib.rs
- jetsocat/proxy/src/socks4.rs
- jetsocat/proxy/src/socks5.rs
- jetsocat/proxy/src/test_utils.rs
- jetsocat/src/client.rs
- jetsocat/src/lib.rs
- jetsocat/src/main.rs
- jetsocat/src/proxy.rs
- jetsocat/src/server.rs
- jetsocat/src/utils.rs
Missing HTTP/HTTPS proxy support, but this is a feature complete for SOCKS family.
> WAYK 2256: jetsocat proxy support for SOCKS4, SOCKS4a, SOCKS5 and SOCKS5H

- devolutions-gateway/src/interceptor/pcap_recording.rs
- devolutions-gateway/src/plugin_manager/packets_parsing.rs
- devolutions-gateway/src/plugin_manager/recording.rs
Added creating of additional frames by timeout.
Added path api for the feature sogar integration.
Updated api according to the changes in the libarary.
> Bugfix session recording

- CHANGELOG.md
- Cargo.lock
- devolutions-gateway/Cargo.toml
- devolutions-gateway/src/http/http_server.rs
- devolutions-gateway/src/http/middlewares/log.rs
- devolutions-gateway/src/http/middlewares/mod.rs
- powershell/build.ps1
I added a log for each http request received.  I also added the request_id in the slog logger.  It means that all logs during the request process will be tagged with request_id=XYZ.  It could be useful. For example : 
2021-04-20 19:15:23:343338 DEBG Request received: POST /jet/association/e531a228-027c-49fd-a74c-0474e5e63963/candidates, **request_id: 50772e60-01f7-419c-958a-230d1894484d**, listener: 0.0.0.0:7171, module: [devolutions_gateway::http::middlewares::log]
2021-04-20 19:15:23:356786 DEBG The jet_tp claim is None, **request_id: 50772e60-01f7-419c-958a-230d1894484d**, listener: 0.0.0.0:7171, module: [devolutions_gateway::http::controllers::jet::SG_JetController]
2021-04-20 19:15:23:357645 INFO POST /jet/association/e531a228-027c-49fd-a74c-0474e5e63963/candidates 200 OK …
> Add logs to track all HTTP requests received and processed

- devolutions-gateway/src/config.rs
- devolutions-gateway/src/interceptor/pcap_recording.rs
- devolutions-gateway/src/jet_client.rs
- devolutions-gateway/src/plugin_manager.rs
- devolutions-gateway/src/plugin_manager/push_files.rs
- devolutions-gateway/src/plugin_manager/recording.rs
Added usage of the sogar util to push files to the remote
> Pushing files to the remote

- jetsocat/src/io.rs
- jetsocat/src/main.rs
- jetsocat/src/pipe.rs
- jetsocat/src/utils.rs
* Fix process piping.
Process was closed early.
To fix this, a handle is kept alive until piping operation ends.
* Fix WebSocket read buffer advancing.
Buffer was not marked as filled causing WebSocket to close itself.
* Flush on write. `sftp` works thanks to this.
* Add `ws-listen` pipe. Useful for debugging but might be used for other purposes as well.
> Jetsocat fixes

- Cargo.lock
- devolutions-gateway/Cargo.toml
- devolutions-gateway/src/config.rs
- devolutions-gateway/src/jet_client.rs
- devolutions-gateway/src/registry/mod.rs
- devolutions-gateway/src/registry/push_files.rs
- devolutions-gateway/src/websocket_client.rs
1 - Sogar update
2 - Don't use sogar_cli to push files. We use sogar_core since we already have a dependency on it
3 - Remove sogar_path from config, not needed since we don't use sogar_cli
> Don't use sogar_cli to push files to remote registry 

- Cargo.lock
- Cargo.toml
- devolutions-gateway/Cargo.toml
- devolutions-gateway/src/http/controllers/http_bridge.rs
- devolutions-gateway/src/http/controllers/mod.rs
- devolutions-gateway/src/http/http_server.rs
- devolutions-gateway/src/http/mod.rs
- devolutions-gateway/src/jet/candidate.rs
- devolutions-gateway/src/registry/mod.rs
- devolutions-gateway/src/service.rs
- devolutions-gateway/src/utils.rs
Add a new route for http bridging validated using a JWT.
This is similar to the one in Wayk Bastion, but a JWT signed with the provisioner key is used for permission.
The JWT currently only provides the destination to forward to.
This is basically a kind of HTTP reverse proxy.
Related ticket: https://devolutions.atlassian.net/browse/WAYK-2562
> WAYK-2562: initial HTTP bridge implementation

- devolutions-gateway/src/http/controllers/http_bridge.rs
- devolutions-gateway/src/http/middlewares/auth.rs
- powershell/DevolutionsGateway/Public/DGateway.ps1
To forward a request via the Gateway, the only thing to do is : 
1 - Create a token that will contain the target
2 - Add a header Gateway-Authorization with that bearer token
For example : 
Gateway-Autorization : Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9DQo.eyJpYXQiOjE2MjgwMDgyMjUsIm5iZiI6MTYyODAwODIyNSwiZXhwIjoxNjI4MDA4MzQ1LCJ0eXBlIjoiYnJpZGdlIiwidGFyZ2V0IjoiaHR0cDovL2xvY2FsaG9zdDo3MTcxL2hlYWx0aCJ9DQo.FGJUjppORtVivURoNE15uE3nycb9Dymh5OU9acAsSuH-MP3DlxpCyiy3KLT3tv4i1SNhLiOR_5-joiT474KtSN4wZLPgU7BV4_uN_SXR0qkW3iu1tW3lmSlbvNiLTLNB32aaLedFIHuAreR8HtQUm7KNV1TdpOIScjWjgBS78xSdMaxkfVAD-MZToWTpr0HKJFyME4DzZoDZX6Xz9r6VKTiAmRTD10Ni5m-USvgi53CMWEoI8hY-TVroUEhARbx8JK5CeGzPYUfyORXHGUnR5Wc8gBJZZwDEN-GCelXP57Gc81oeZ4HQoMmpmMILwTi5ygujmA5jtCNC5mvgRiH5lA
I also added parameters to the powershell …
> Bridge all verbs (get/put/patch/post/delete) + Authorization is set in Gateway-Authorization header

- devolutions-gateway/src/http/controllers/diagnostics.rs
- devolutions-gateway/src/http/controllers/mod.rs
- devolutions-gateway/src/http/http_server.rs
- devolutions-gateway/src/http/mod.rs
- jet-proto/src/token.rs
It requires a scope token with scope set to "gateway.diagnostics.read"
> WAYK-2567: Add endpoint to get logs (GET /diagnostics/logs)

- devolutions-gateway/src/config.rs
- devolutions-gateway/src/http/controllers/diagnostics.rs
I added endpoint ``/diagnostics/configuration`
To access this endpoint, you need a valid scope token with scope "gateway.diagnostics.read"
It returns hostname + listeners. Here is an example : 
```
{
"hostname": "jet-fdubois.ngrok.io",
"listeners": [
{
"internal_url": "ws://0.0.0.0:7171/",
"external_url": "wss://jet-fdubois.ngrok.io:7171/"
},
{
"internal_url": "tcp://0.0.0.0:8080",
"external_url": "tcp://3.tcp.ngrok.io:21405"
}
]
}
```
> WAYK-2568: Add an endpoint to get configuration information

- devolutions-gateway/src/http/controllers/http_bridge.rs
- devolutions-gateway/src/http/controllers/sessions.rs
- devolutions-gateway/src/http/middlewares/auth.rs
- devolutions-gateway/src/jet_client.rs
- devolutions-gateway/src/rdp/accept_connection_future.rs
- devolutions-gateway/src/websocket_client.rs
I ran cargo clippy and fixed warning
> Cargo clippy

- devolutions-gateway/src/config.rs
- devolutions-gateway/src/service.rs
If the provisionner public key is not set, the gateway doesn't start. It was a panic so no log file generated. Hard to debug, you had to launch the gateway on a command line to see the error. I changed that for a log message... It will panic anyway, but at least, the log file will be there with a log similar to that
2021-09-01 10:27:22:677491 ERRO Devolutions Gateway can't be launched. Invalid configuration: provisioner public key is missing, module: [devolutions_gateway::service]
> WAYK-2577: Devolutions-Gateway - Log invalid configuration

- .github/workflows/ci.yml
- devolutions-gateway/Cargo.toml
Port the CI build into GitHub workflow
- A patch is required for `embed-resource` build dependency, I raised a PR for the issue. Alternatively we could manually set the Windows SDK include paths
- Artifacts are not code-signed, as the relevant secrets are not yet available. Once they're made available in a properly configured environment, code-signing will probably be refactored into new "release {dev/production}" jobs. Currently the workflow prints a notice that artifacts are *not* code-signed.
Performance is roughly on-par with Azure, since we are able to parallelize the builds
> GitHub workflow

- Cargo.lock
- Cargo.toml
- devolutions-gateway/Cargo.toml
- devolutions-gateway/src/config.rs
- devolutions-gateway/src/http/controllers/jet.rs
- devolutions-gateway/src/http/middlewares/auth.rs
- devolutions-gateway/src/preconnection_pdu.rs
- devolutions-gateway/src/service.rs
- devolutions-gateway/src/token.rs
- devolutions-gateway/src/transport/ws.rs
- devolutions-gateway/src/utils.rs
- devolutions-gateway/src/websocket_client.rs
- jetsocat/Cargo.toml
- jetsocat/proxy/Cargo.toml
- jetsocat/proxy/src/lib.rs
- jetsocat/src/jmux/listener.rs
- jetsocat/src/jmux/mod.rs
- jetsocat/src/lib.rs
- jetsocat/src/listener.rs
- jetsocat/src/main.rs
- jetsocat/src/pipe.rs
- jmux-proto/Cargo.toml
- jmux-proto/src/lib.rs
- jmux-proxy/Cargo.toml
- jmux-proxy/src/codec.rs
- jmux-proxy/src/config.rs
- jmux-proxy/src/id_allocator.rs
- jmux-proxy/src/lib.rs
- tools/tokengen/src/main.rs
Expose JMUX proxy through the new `/jmux` websocket endpoint.
A JMUX token must be provided either through query params or the `Authorization` header.
- Extracted jmux-related code into jmux-proto and jmux-proxy crates
- Improved JMUX proxy related logs
- Support for target filtering
```
$ cargo run -p devolutions-gateway -- --hostname jet-relay.ngrok.io -l "ws://*:7171,wss://*:443" --provisioner-public-key-file /etc/wayk-bastion/den-gateway/provisioner.pem
```
```
$ cargo run -p tokengen -- --provider-private-key /etc/wayk-bastion/den-server/den-private.key jmux
```
```
$ cargo run -p jetsocat -- jmux-proxy "ws://127.0.0.1:7171/jmux?token=<GENERATED TOKEN>" socks5-listen://0.0.0.0:5003 --log-term
```
> JMUX websocket endpoint

- Cargo.lock
- devolutions-gateway/Cargo.toml
- devolutions-gateway/src/config.rs
- devolutions-gateway/src/generic_client.rs
- devolutions-gateway/src/http/controllers/http_bridge.rs
- devolutions-gateway/src/http/controllers/jet.rs
- devolutions-gateway/src/jet_client.rs
- devolutions-gateway/src/jet_rendezvous_tcp_proxy.rs
- devolutions-gateway/src/lib.rs
- devolutions-gateway/src/rdp.rs
- devolutions-gateway/src/rdp/connection_sequence_future.rs
- devolutions-gateway/src/routing_client.rs
- devolutions-gateway/src/token.rs
- devolutions-gateway/src/transport/tcp.rs
- devolutions-gateway/src/transport/ws.rs
- devolutions-gateway/src/utils.rs
- devolutions-gateway/src/websocket_client.rs
A new optional claim `dst_hst` is added to the association token.
A list of target addresses can be specified through it.
A connection will be attempted to each host successively until one succeeds, or all fail.
Todo:
> DPS-5255: support for alternate hosts

- devolutions-gateway/src/http/controllers/association.rs
- devolutions-gateway/src/http/controllers/diagnostics.rs
- devolutions-gateway/src/http/controllers/health.rs
- devolutions-gateway/src/http/controllers/http_bridge.rs
- devolutions-gateway/src/http/controllers/mod.rs
- devolutions-gateway/src/http/controllers/sessions.rs
- devolutions-gateway/src/http/http_server.rs
- devolutions-gateway/src/jet_rendezvous_tcp_proxy.rs
We need to be able to access all important endpoints through `jet/*` to
simplify routing rules.
Older endpoints are still accessibles for compatibility, but will be
removed after one year starting today (2021/11/19).
Note 1: this also fixes DPS-5166 (`jet/health` requiring authorization)
Note 2: `bridge/*` is moved to `jet/bridge/*` without adding compatibility
routes because it's currently unused.
Note 3: `registry/*` is left untouched for now, particular attention is
needed. Since it's not yet used in other products, this shouldn't be an
issue to postpone decision here.
> DPS-5167: duplicate root HTTP endpoints under jet/

- devolutions-gateway/src/generic_client.rs
- devolutions-gateway/src/jet_client.rs
- devolutions-gateway/src/jet_rendezvous_tcp_proxy.rs
- devolutions-gateway/src/rdp.rs
- devolutions-gateway/src/websocket_client.rs
As per the spec, if session recording is required through the `jet_rec` claim,
but the relay happen to be unable to perform the recording, the connection MUST be rejected.
> WAYK-2565: reject proxy if rec policy can't be met

- devolutions-gateway/src/generic_client.rs
- devolutions-gateway/src/rdp.rs
- devolutions-gateway/src/token.rs
- devolutions-gateway/src/transport/tcp.rs
- devolutions-gateway/src/transport/ws.rs
- devolutions-gateway/src/utils.rs
A custom `serde::de::Deserialize` trait implementation is used in order to dynamically validate target addresses based on the application protocol claim provided in the same token:
- If the application protocol claim is set to a known protocol for which the default port is known, then the port can be omitted.
- Otherwise, the port must be included or token will be rejected.
This PR also adds timeout to host connections.
> DPS-5332: default port based on protocol claim

- Cargo.lock
- devolutions-gateway/src/websocket_client.rs
Requests injected to saphir through the `inject_raw` function were missing the peer address because it was not correctly forwarded.
This fix depends on a saphir patch which should be merged upstream at some point.
> fix: add peer address when injecting HTTP requests

- .github/workflows/release.yml
- ci/tlk.ps1
Fix issues with the release workflow:
- Uncomment the final steps of the release pipeline to actually allow the release
- Fix the syntax and auth of the `gh release create` command
- Don't run the workflow if the specified run isn't from master, or it didn't complete successfully
- Don't fail the workflow if the PS module version is already published
> Enable releases

- .github/workflows/README.md
- .github/workflows/ci.yml
- .github/workflows/package.yml
- .github/workflows/release.yml
- ci/tlk.ps1
A large (and hopefully final) refactor of the CI and release.
The previous setup performed the build, test and packaging inside the CI workflow. The release workflow code-signed the artifacts, then built the docker containers (the `servercore-ltsc2019` container is too large to be a build artifact) and published them, created a GitHub release and published the PowerShell module.
However, although the Windows Gateway .msi was code-signed; the executable it installed was not: since the packaging happened in the CI workflow. It's not preferable to code-sign inside the CI workflow since it requires approval to access the signing certificates. Unsigned builds are fine for dev; but we might want to create a fully signed build independently of a release.
The PR splits everything into 3 …
> Refactor CI

- devolutions-gateway/src/http/http_server.rs
- devolutions-gateway/src/http/middlewares/auth.rs
- devolutions-gateway/src/token.rs
- tools/tokengen/src/main.rs
Check for JWT in requests with the shape `/route?token=<JWT>`.
This allow configuring KDC client to use `/KdcProxy?token=<JWT>` to identify itself.
> DGW-18: parse query parameters to retrieve token

- Cargo.lock
- crates/jmux-proxy/src/config.rs
- devolutions-gateway/Cargo.toml
- devolutions-gateway/src/config.rs
- devolutions-gateway/src/http/controllers/kdc_proxy.rs
- devolutions-gateway/src/token.rs
- devolutions-gateway/src/utils.rs
- devolutions-gateway/src/websocket_client.rs
- tools/tokengen/src/main.rs
Claims:
- `dst_hst`: destination address with optional scheme and port
- `dst_addl`: list of items as defined for `dst_hst`
Wildcards are supported similarly to [Wildcard certificates](https://en.wikipedia.org/wiki/Wildcard_certificate)
> DGW-21: specify JMUX filtering through claims

- Cargo.lock
- jetsocat/Cargo.toml
- jetsocat/src/lib.rs
- jetsocat/src/main.rs
- jetsocat/src/utils.rs
- jetsocat/tests/socks5-to-jmux.rs
Used to define a timeout when opening pipes.
Issue: ARC-64
> feat(jetsocat): `--timeout` option

- devolutions-gateway/src/websocket_client.rs
If any host is specified as `*`, the JMUX proxy should be in allow all mode.
> feat(dgw): `*` in JMUX token for "allow all" rule

- Cargo.lock
- jetsocat/Cargo.toml
- jetsocat/src/lib.rs
- jetsocat/src/listener.rs
- jetsocat/src/main.rs
- jetsocat/src/process_watcher.rs
- jetsocat/src/utils.rs
- jetsocat/tests/socks5-to-jmux.rs
Add `--watch-parent` and `--watch-process` CLI options.
Jetsocat will close itself automatically when watched process is not running anymore.
Issue: ARC-68
> feat(jetsocat): process watcher option

- Cargo.lock
Pull a fix for the following vulnerability:
GHSA-76w9-p8mg-j927 Out-of-bounds Write in nix
> build(deps): Bump nix to 0.24

- .github/workflows/README.md
- .github/workflows/ci.yml
- .github/workflows/create-new-release.yml
- .github/workflows/jetsocat-nuget.yml
- .github/workflows/package.yml
- .github/workflows/release.yml
- README.md
- jetsocat/nuget/.gitignore
- jetsocat/nuget/Devolutions.Jetsocat.nuspec
- jetsocat/nuget/Devolutions.Jetsocat.targets
- jetsocat/nuget/package.ps1
Workup improvements to build and release workflows.
- The "Release" workflow now checks if this version has already been released (on GitHub) and will fail-fast. GitHub releases are not idempotent, so in this case it's necessary to increment the version (👍) or delete the existing release (👎) and try again.
- Migrate the jetsocat nuget workflow from conan-nuget repository. This must be run separately since it's necessary to specify the nuget package version using workflow_dispatch. GH is currently not starting the workflow, so this is untested but we should be able to easily resolve any issues once they transpire.
- Add a new "Generate New Release" workflow which calls each individual workflow (CI, Package, Release) and runs the whole release process from start-to-finish. 
- Add some …
> Workflow improvements

- devolutions-gateway/src/websocket_client.rs
> feat(dgw): limit JMUX wildcard addresses

- Cargo.lock
This is bad.
Indeed, `Content-Type` is a "singleton field": a single member is anticipated as the field value.
RFC9110 says:
> Although Content-Type is defined as a singleton field,
> it is sometimes incorrectly generated multiple times,
> resulting in a combined field value that appears to be a list.
> Recipients often attempt to handle this error by using
> the last syntactically valid member of the list, leading to
> potential interoperability and security issues if different
> implementations have different error handling behaviors.
This was a bug in Saphir. I fixed it and updated the reference in Cargo.lock.
> fix(dgw): Content-Type header present twice for Json responses

- devolutions-gateway/src/config.rs
It's not always required and when specified it causes an error on start up because files (obviously) do not exist.
> fix(dgw): remove TLS options from default configuration

- .github/workflows/publish-clients.yml
- ci/npm-publish.ps1
- devolutions-gateway/openapi/ts-angular-client/README.md
- devolutions-gateway/openapi/ts-angular-client/build.ps1
- devolutions-gateway/openapi/ts-angular-client/config.json
- devolutions-gateway/openapi/ts-angular-client/package.json
Actually mostly a CI fix.
In fact, the TypeScript package must be built and then the resulting artifacts used when publishing.
Roughly:
- `npm run build`
- `cd ./dist/`
- `npm publish`
> fix(ts-angular-client): fix npm package

- devolutions-gateway/openapi/dotnet-subscriber/src/Devolutions.Gateway.Subscriber/Models/SubscriberMessage.cs
- devolutions-gateway/openapi/dotnet-subscriber/src/Devolutions.Gateway.Subscriber/Models/SubscriberMessageKind.cs
- devolutions-gateway/openapi/subscriber-api.yaml
- devolutions-gateway/src/lib.rs
- devolutions-gateway/src/openapi.rs
- devolutions-gateway/src/subscriber.rs
This timestamp is the date and time the message was produced on Gateway side. The field is present in all subscriber messages.
Issue: DGW-50
> feat(dgw): add timestamp to subscriber messages

- crates/jmux-proxy/src/lib.rs
Previously, JMUX proxy task wasn't properly shut down because tokio tasks are detached by default (similar to `std::thread::spawn`). This adds a helper wrapper to explicitely specify whether a task should be joined or detached.
Issue: DGW-54
> fix(jmux-proxy): properly cancel proxy task

- devolutions-gateway/src/token.rs
With this change, we do not allow reuse for RDP sessions more than a few seconds following the previous use. The interval is 10 seconds which is expected to give plenty of time to RDP handshake and negotiations. Once this interval is exceeded, we consider the RDP session is fully started and the same token can't be reused anymore.
Two reasons why this is beneficial:
- Security wise: the reuse interval is considerably shortened
- Feature wise: more efficient forced RDP session termination
Regarding the second point: Windows’ mstsc will keep alive the session by re-opening it immediately. Because we allow token reuse in a limited fashion for RDP, as long as the association token is not expired, the terminate action has effectively no visible effect (besides that multiple sessions occurred). …
> feat(dgw): smaller token reuse interval for RDP sessions

- ci/tlk.ps1
- crates/devolutions-gateway-generators/src/lib.rs
- devolutions-gateway/src/token.rs
- devolutions-gateway/tests/token_security.rs
With this change, a subkey is allowed to sign a short-lived KDC token.
> feat(dgw): extend subkey capabilities to KDC tokens

- .github/workflows/ci.yml
- .github/workflows/jetsocat-nuget.yml
- Fix the casing of the jetsocat universal binary to match thin binaries (this doesn't matter for the release, since the build script performs a case-insensitive match)
- Install jfrog CLI in the actions runner
> Fix nuget packaging for jetsocat

- .github/workflows/ci.yml
- ci/tlk.ps1
stdout of invoked commands was eaten by the PowerShell pipeline stream. Appending `| Out-Host` make it clear that we don’t want that.
> ci: fix tlk.ps1 eating stdout

- package/Windows/Actions/CustomAction.cpp
On a new install, the Devolutions Gateway service will not exist and the attempt to read its startup type will obviously fail. 
Currently this pops a warning dialog to the user, which is almost certainly not what we want - it could be interpreted as an error. The issue is already written to the .msi log, so don't prompt the user.
> feat(installer): don't show an error dialog from installer custom action

- package/Windows/DevolutionsGateway.wxs
The installer invokes calcs.exe to reset the permissions on %programdata%\Devolutions\Gateway
However, if a user or tool has previously edited permissions on a file within the directory (and removed the "inheritance" flag), those permissions will not be reset. By adding the `/t` switch to [calcs](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/cacls), we can ask it to traverse subdirectories and files:
> /t | Changes ACLs of specified files in the current directory and all subdirectories.
> fix(installer): recursively reset permissions on the ProgramData directory

- package/Windows/Includes/DevolutionsGateway.wxi
We specify access rights to the %programdata%\devolutions\gateway directory using an SDDL string.
PowerShell has some functionality to convert ACLs to SDDLs and vice-versa. To retrieve the SDDL for a path, you can run `Get-Acl | Format-List` (The returned object has an `Sddl` property).
Going the other way, one can use `ConvertFrom-SddlString`. In this specific example:
`PS C:\wayk\dev\devolutions-gateway> ConvertFrom-SddlString -Sddl "D:PAI(A;OICI;FA;;;SY)(A;OICI;0x1201bf;;;LS)(A;OICI;FA;;;BA)(A;OICI;0x1200a9;;;BU)"`
> Owner            : 
> Group            : 
> DiscretionaryAcl : {NT AUTHORITY\SYSTEM: AccessAllowed (ChangePermissions, CreateDirectories, Delete, DeleteSubdirectoriesAndFiles, ExecuteKey, FullControl, FullControl,
>                    FullControl, FullControl, GenericAll, …
> fix(installer): grant Local Service access rights to the ProgramData directory

- package/Windows/Actions/CustomAction.cpp
- package/Windows/Actions/CustomAction.def
- package/Windows/DevolutionsGateway.wxs
If the Gateway service startup type is "Automatic", the installer will now attempt to start the service after configuring it. This is done using a C++ custom action, since it's not possible to use conditions in the WiX `ServiceControl` element.
`StartService` can fail for fairly benign reasons, so failing to start the service does not cause the installation to fail.
The service will not be started if it's startup type is on-demand.
Finally, this behaviour can be overridden by setting `P.DGW.NO_START_SERVICE` via `msiexec`.
Additionally, file pickers inside the installer now always present an "All Files" option. When picking the provisioner public key, .pem is offered before .key to prevent users accidentally selecting the certificate private key in this step.
> feat(installer): start the Gateway service at install time

- devolutions-gateway/src/config.rs
- powershell/DevolutionsGateway/Public/DGateway.ps1
By convention:
.pem -> public key
.key -> private key
.crt -> certificate
Note that this is merely a convention, not a standard, and file openers should be able to select a .key file when choosing a public key (through the drop-down menu typically)
> fix: normalize file extensions

- devolutions-gateway/src/config.rs
- devolutions-gateway/src/http/controllers/health.rs
- devolutions-gateway/src/token.rs
- rust-toolchain.toml
This change is making possible to omit the port in the target host field. The Telnet default port will be inferred as appropriate.
> feat(dgw): add Telnet protocol variant

- powershell/DevolutionsGateway/Public/DGateway.ps1
Without this patch, the nil UUID is used as the "missing" value instead of $null.
Issue: DGW-73
> fix(pwsh): nil UUID when creating an empty DGatewayConfig

- .github/workflows/ci.yml
- .github/workflows/package.yml
- .github/workflows/publish-clients.yml
- .github/workflows/release.yml
- package/Windows/Actions/CustomAction.cpp
- package/Windows/DevolutionsGateway.wxs
- On first time installs, always initialize the default config file before applying any PowerShell configuration commands. This ensures that the ID is properly created.
- Properly pass only the hostname (instead of the full URI) to `Set-DGatewayHostname`
- Fix deprecation warnings in GitHub Actions
Issue: DGW-72
Issue: DGW-73
> fix(installer): fix configuration creation with installer

- package/Windows/Actions/CustomAction.cpp
Unicode character literals in source files can be problematic, depending on the editor and encoding. Instead, avoid the issue by masking the character with an asterisk instead of a unicode "bullet".
Issue: DGW-74
> fix(installer): avoid unicode char literals

- .github/workflows/package.yml
> ci(jetsocat): enable hardened runtime on macOS

- Cargo.lock
- jetsocat/Cargo.toml
Let rustls use the plateform’s native certificate store.
> feat(jetsocat): use rustls-native-certs

- jetsocat/Cargo.toml
- jetsocat/src/main.rs
- jetsocat/src/pipe.rs
- jetsocat/src/utils.rs
- `write-file://<PATH>`: write file at the specified location
- `read-file://<PATH>`: read wile at the specified location
> feat(jetsocat): file-based pipes

- jetsocat/nuget/Devolutions.Jetsocat.targets
It's preferable if we set the execute bit on jetsocat binaries for macOS and Linux rather than relying on the consumer to do it. However, even if we set this properly at build time it's unlikely to be preserved by the nuget package.
Instead, set the file permissions while building the final target. The solution is not the neatest (I don't know how to target the copied file in the target `bin` directory, particularly on macOS where it might be somewhere in the final .app bundle structure).
> fix(jetsocat): set execute permission in binary

- Cargo.lock
- devolutions-gateway/Cargo.toml
- devolutions-gateway/src/config.rs
Use `x509-cert` crate to extract the public key from the leaf TLS certificate. `x509-cert` supports more certificates.
> fix(dgw): better TLS leaf certificate public key extracting

- powershell/build.ps1
use csproj explicitly with dotnet publish -o parameter (output path) since recent .NET SDK makes it an error rather than a warning on a .sln (default), breaking the build
> fix powershell/build.ps1 output path

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- devolutions-gateway/src/config.rs
- devolutions-gateway/src/http/middlewares/log.rs
- devolutions-gateway/src/log.rs
Set a maximum size of 3 MB for each file and a maximum of 10 log files.
With this change, Devolutions Gateway should never consume more than 30 MB for its logs.
Issue: DGW-34
A pull request was opened in `tracing` repository: https://github.com/tokio-rs/tracing/pull/2497
Until it’s merged, `tracing-appender` dependency is patched and points to my fork.
Future work includes removing this patch.
> fix(dgw): size-based log rotation

- package/Windows/Actions/CustomAction.cpp
- package/Windows/Actions/CustomAction.def
- package/Windows/Actions/DevolutionsGateway.Installer.Actions.vcxproj
- package/Windows/Actions/stdafx.h
- package/Windows/DevolutionsGateway.wxs
- package/Windows/DevolutionsGateway_en-us.wxl
- package/Windows/DevolutionsGateway_fr-fr.wxl
- package/Windows/WixUI_CustomInstallDir.wxs
PowerShell configuration commands are now executed as custom actions instead of WixSilentExec. Errors are tracked and, if the installer is running with UI, an appropriate error message is shown to the user. For first time installs, if the installation fails, files that may have been created by the configuration process are cleaned up.
PowerShell command output is redirected to a temporary file; in the case of an error we provide the user the path to that file. A general command execution error will display a string error value. 
Custom actions are refactored slightly for consistency and readability:
- Internal functions now only return `void`, `BOOL`, or `HRESULT` where possible. Errors are always handled as `HRESULT` and other results (e.g. Win32 error codes, `LSTATUS`, null references) …
> feat(installer): improved error handling and rollback in Windows installer

- devolutions-gateway/src/jrec.rs
Improve session recording file layout:
- use one directory per session id, rather than all files within same directory
- use regular file names within session directory (session.webm, session.trp)
- create session.json manifest file + update duration at session termination
- data not found in manifest file should be stored in DVLS database with id
> improve session recording file layout

- devolutions-gateway/src/http/controllers/config.rs
- devolutions-gateway/src/http/controllers/diagnostics.rs
- devolutions-gateway/src/http/controllers/health.rs
- devolutions-gateway/src/http/controllers/heartbeat.rs
- devolutions-gateway/src/http/controllers/http_bridge.rs
- devolutions-gateway/src/http/controllers/jrl.rs
- devolutions-gateway/src/http/controllers/kdc_proxy.rs
- devolutions-gateway/src/http/controllers/recordings.rs
- devolutions-gateway/src/http/controllers/session.rs
- devolutions-gateway/src/http/controllers/sessions.rs
- devolutions-gateway/src/http/guards/access.rs
- devolutions-gateway/src/http/middlewares/auth.rs
- devolutions-gateway/src/http/mod.rs
- devolutions-gateway/src/listener.rs
- devolutions-gateway/src/token.rs
- devolutions-gateway/src/websocket_client.rs
Before:
```
2023-04-26T16:21:19.242218Z ERROR
listener{url=ws://0.0.0.0:7171/}:ws{client=127.0.0.1:56058}:http:request
{request_id=84e4946b-9af4-448f-8292-5d8c4f191578 method=GET uri=/
jet/heartbeat}: devolutions_gateway::http: 401 Unauthorized at /
rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/
function.rs:250:5 [Invalid claims for Scope token]
```
Now:
```
2023-04-26T16:16:19.968334Z ERROR
listener{url=ws://0.0.0.0:7171/}:ws{client=127.0.0.1:55024}:http:request
{request_id=f92c01fc-90de-4ca5-b2cd-e6c9e6d42be8 method=GET uri=/
jet/heartbeat}: devolutions_gateway::http: error=401 Unauthorized
at devolutions-gateway/src/http/middlewares/auth.rs:111:82
[source: invalid claims for Scope token, because unknown variant
`gateway.heartbeat.ready`, expected one of `*`, …
```
> feat(dgw): improve HTTP error reporting

- .github/workflows/build-tools.yml
Build **jet-doctor** and **tokengen** in CI for Windows, Linux (x86_64) and macOS (x86_64, arm64 and universal).
Windows and macOS executables are code-signed.
Additionally, the macOS universal executables are marked 'executable' and packaged into a disk image (.dmg) which is further signed and notarized. This is suitable for distribution to a user without needing to bypass Gatekeeper on the client system.
Build time is not optimized (i.e. slow) but it's not expected to run this workflow often.
> feat(ci): Build jet-doctor and tokengen in CI

- devolutions-gateway/src/api/fwd.rs
- devolutions-gateway/src/config.rs
- devolutions-gateway/src/lib.rs
- devolutions-gateway/src/rdp_extension.rs
- devolutions-gateway/src/service.rs
- devolutions-gateway/src/target_addr.rs
- devolutions-gateway/src/tls.rs
- devolutions-gateway/src/utils.rs
As of rustls 0.21, it’s possible to disable the TLS resumption that is not supported by some services such as CredSSP.
This allow us to reuse the same TLS client config and connector for all proxy-based TLS connections.
(TlsConnector is just a wrapper around the config providing the `connect` method.)
> Making one of these can be expensive, and should be once per process
> rather than once per connection.
[source](https://docs.rs/rustls/0.21.1/rustls/client/struct.ClientConfig.html)
> perf(dgw): re-use TLS client config

- .github/workflows/ci.yml
- ci/tlk.ps1
- Although it's possible to check if we're on a fork (and even to check for `dependabot` builds by checking `github.actor`), it's not possible to exclude a job based on a matrix condition. Instead, generate the build matrices dynamically using PowerShell. This allows us to drop the Windows builds in case secrets are not available (e.g. a PR from a fork). A warning will be printed in this case.
- Revert to using `secrets.ARTIFACTORY_READ_TOKEN`. This token is now available for builds from `dependabot`.
- Don't bootstrap conan or OpenSSL when building for non-Windows.
- Drop the `jetsocat` build for the Windows x86 target.
> fix(ci): limit builds on forked PRs, optimize CI workflow

- Cargo.lock
- crates/jmux-proxy/src/config.rs
- devolutions-gateway/Cargo.toml
- devolutions-gateway/src/api/kdc_proxy.rs
- devolutions-gateway/src/api/rdp.rs
- devolutions-gateway/src/rdp_extension.rs
Case is irrelevant when comparing hostnames and schemes.
Note: using eq_ignore_ascii_case is okay because we don’t really expect unicode in such context.
> fix(jmux): ignore case for hosts and schemes

- CHANGELOG.md
- Cargo.lock
- devolutions-gateway/Cargo.toml
- devolutions-gateway/src/api/diagnostics.rs
- devolutions-gateway/src/config.rs
- devolutions-gateway/src/ngrok.rs
Previously, a Duration was deserialized from a string using the `humantime_serde` crate. With this patch, the duration is specified in seconds using an integer.
In other words, this code:
```rust
#[serde(default, skip_serializing_if = "Option::is_none", with = "humantime_serde")]
pub heartbeat_interval: Option<Duration>,
```
Is changed into this:
```rust
#[serde(skip_serializing_if = "Option::is_none")]
pub heartbeat_interval: Option<u64>,
```
> fix(dgw): durations in seconds in ngrok config

- devolutions-gateway/src/api/jrec.rs
When listing the recordings, if the recording directory does not exist, it means that there is no recording yet (and the folder will be created later). However, Devolutions Gateway is attempting to read this folder anyway and the HTTP error 500 (Internal Server Error) is returned. This patch fixes this by returning an empty list as appropriate.
Issue: DGW-99
> fix(dgw): error 500 when recording folder is missing

- devolutions-gateway/src/api/fwd.rs
The name of the endpoint was wrong, and thus /jet/fwd/tls was returning the 404 Not Found status.
Furthermore, the `with_tls` option was not properly set.
Issue: DGW-102
> fix(dgw): typo in TLS forward route

- Cargo.lock
- Cargo.toml
- crates/jmux-proxy/src/lib.rs
- devolutions-gateway/src/api/fwd.rs
- devolutions-gateway/src/api/rdp.rs
- devolutions-gateway/src/config.rs
- devolutions-gateway/src/generic_client.rs
- devolutions-gateway/src/main.rs
- devolutions-gateway/src/middleware/auth.rs
- devolutions-gateway/src/ngrok.rs
- devolutions-gateway/src/proxy.rs
- devolutions-gateway/src/rdp_extension.rs
- devolutions-gateway/src/service.rs
- devolutions-gateway/src/subscriber.rs
- jetsocat/src/lib.rs
- jetsocat/src/main.rs
- Records additional info on running sessions
- Improves file rotation
> feat(dgw): improve logs

- .github/dependabot.yml
- .github/workflows/dependabot-auto-merge.yml
- Cargo.lock
- benchmarks/Cargo.toml
- crates/devolutions-gateway-generators/Cargo.toml
- crates/devolutions-gateway-task/Cargo.toml
- crates/jet-proto/Cargo.toml
- crates/jmux-generators/Cargo.toml
- crates/jmux-proto/Cargo.toml
- crates/jmux-proxy/Cargo.toml
- crates/mock-net/Cargo.toml
- crates/proxy-generators/Cargo.toml
- crates/proxy-http/Cargo.toml
- crates/proxy-server/Cargo.toml
- crates/proxy-socks/Cargo.toml
- crates/proxy-tester/Cargo.toml
- crates/sogar-registry/Cargo.toml
- crates/test-utils/Cargo.toml
- crates/transport/Cargo.toml
- devolutions-gateway/Cargo.toml
- fuzz/Cargo.toml
- jetsocat/Cargo.toml
- tools/generate-openapi/Cargo.toml
- tools/jet-doctor/Cargo.toml
- tools/subscriber-dummy/Cargo.toml
- tools/tokengen/Cargo.toml
- `cargo-edit` is now preserving the original version format, so I relaxed the patch number.
- dependabot grouped updates
- enable auto-merge automatically for dependabot PRs. Note that we still require someone to approve before the dependabot PR is actually merged. This is just to save a few clicks.
> Clean dependencies

- tools/tokengen/src/main.rs
Useful when testing endpoints using `jetsocat`.
Example:
```bash
cargo run -p jetsocat -- forward - "ws://127.0.0.1:7171/jet/fwd/tcp/123e4567-e89b-12d3-a456-426614174000?token=$(cargo run --manifest-path=./tools/tokengen/Cargo.toml -- --provisioner-key /path/to/provisioner.key forward --dst-hst 127.0.0.1:9999 --jet-aid 123e4567-e89b-12d3-a456-426614174000)"
```
> chore(tokengen): add --jet-aid CLI argument

- README.md
- devolutions-gateway/src/api/diagnostics.rs
- devolutions-gateway/src/config.rs
- devolutions-gateway/src/ngrok.rs
Some ngrok options are not making much sense for Devolutions Gateway.
- PROXY protocol: we do not handle PROXY protocol in Devolutions Gateway and instead make use of Conn::peer_addr to find the original client IP.
- Basic Authentication: we have our own way to handle the authentication using Json Web Tokens.
- Schemes: only HTTPS should be used when exposing a Devolutions Gateway on internet.
The `Authtoken` key was also renamed to `AuthToken` for readability.
> fix(dgw)!: adjust ngrok options

- powershell/DevolutionsGateway/DevolutionsGateway.psd1
- powershell/DevolutionsGateway/Public/DGateway.ps1
- powershell/pester/Config.Tests.ps1
- powershell/pester/ImportCertificate.Tests.ps1
- powershell/run-tests.ps1
Add verbosity profile configuration:
```
It 'Sets log verbosity profile' {
Set-DGatewayConfig -ConfigPath:$ConfigPath -VerbosityProfile 'All'
$(Get-DGatewayConfig -ConfigPath:$ConfigPath).VerbosityProfile | Should -Be 'All'
Set-DGatewayConfig -ConfigPath:$ConfigPath -VerbosityProfile 'Default'
$(Get-DGatewayConfig -ConfigPath:$ConfigPath).VerbosityProfile | Should -Be 'Default'
Set-DGatewayConfig -ConfigPath:$ConfigPath -VerbosityProfile 'Tls'
$(Get-DGatewayConfig -ConfigPath:$ConfigPath).VerbosityProfile | Should -Be 'Tls'
{ Set-DGatewayConfig -ConfigPath:$ConfigPath -VerbosityProfile 'yolo' } | Should -Throw
}
```
Add ngrok tunnel configuration:
```
It 'Sets ngrok configuration' {
$AuthToken = '4nq9771bPxe8ctg7LKr_2ClH7Y15Zqe4bWLWF9p'
$Metadata = '{"serial": "00012xa-33rUtz9", …
```
> add verbosity profile, ngrok tunnel configuration

- Cargo.lock
- README.md
- devolutions-gateway/Cargo.toml
- devolutions-gateway/src/api/kdc_proxy.rs
- devolutions-gateway/src/config.rs
- devolutions-gateway/src/service.rs
- devolutions-gateway/src/tls.rs
- devolutions-gateway/src/token.rs
- devolutions-gateway/tests/config.rs
- docs/COOKBOOK.md
PFX files may now be specified in the `TlsCertificateFile` option.
Furthermore, a new optional option is added: `TlsPrivateKeyPassword`.
This option may be used when the PFX file is encrypted using a passkey.
Issue: DGW-121
> feat(dgw): support for PFX files

- .github/workflows/ci.yml
Our CI is wonky: for Windows runners, `rustup` is _sometimes_ failing with this error:
```
error: failed to install component: 'clippy-preview-x86_64-pc-windows-msvc', detected conflict: 'bin/cargo-clippy.exe'
```
It looks like rustup is trying to re-install a toolchain that is already installed:
```
$ rustup toolchain install "1.73.0"
info: syncing channel updates for '1.73.0-x86_64-pc-windows-msvc'
info: latest update on 2023-10-05, rust version 1.73.0 (cc66ad468 2023-10-03)
info: downloading component 'cargo'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: installing component 'cargo'
info: installing component 'rust-std'
info: installing component 'rustc'
1.73.0-x86_64-pc-windows-msvc installed - rustc 1.73.0 (cc66ad468 2023-10-03)
info: checking for …
```
> ci: remove explicit rustup commands

- crates/jmux-proxy/src/lib.rs
- crates/proxy-server/src/main.rs
- devolutions-gateway/src/api/kdc_proxy.rs
- devolutions-gateway/src/config.rs
- devolutions-gateway/src/target_addr.rs
- devolutions-gateway/src/utils.rs
This patch ensures Devolutions Gateway does not immediately discard resolved addresses which are not emitted first by Tokio’s `lookup_host`.
Typically, the first address is enough and there is no need to try subsequent ones. Therefore, it is not expected for this change to cause any additional latence in the the vast majority of the cases. However, just to be on the safe side and enable easier troubleshooting, a WARN-level log is emitted when failing at connecting to a resolved address. If latence were to be introduced by this patch, we can easily be made aware of the problem and investigate further (network configuration, etc).
If this proves to be a problem in the future, we can add filtering options. For instance, on a network where IPv4 is not supported or disabled, we may want to …
> fix(dgw): use all resolved addresses when connecting

- crates/jmux-proxy/src/codec.rs
- crates/jmux-proxy/src/lib.rs
- devolutions-gateway/src/log.rs
- rust-toolchain.toml
Notably, status codes like ECONNRESET or ECONNABORTED are not considered anymore as actual errors, and will be logged accordingly.
> fix(dgw): improve logs quality for JMUX proxy

- .github/workflows/publish-libraries.yml
`npm push mylib.nupkg` will push both the nupkg and the snupkg if they are in the same folder.
Currently, we are redundantly attempting to push the snupkg files separately:
Usually, we don’t need to "retry" pushing only the symbols, so it should be enough to only iterate on the nupkg files.
Note: I also renamed `publish-clients.yml` to `publish-libraries.yml`, so the filename is the same as the workflow name.
> ci: remove redundant snupkg pushing

- devolutions-gateway/src/tls.rs
This can help with troubleshooting configuration problems with Windows system certificate store.
> fix(dgw): upgrade Windows store resolve error log

- ci/tlk.ps1
- powershell/DevolutionsGateway/DevolutionsGateway.psd1
- powershell/DevolutionsGateway/DevolutionsGateway.psm1
- powershell/DevolutionsGateway/Private/CertificateHelper.ps1
- powershell/DevolutionsGateway/src/DevolutionsGateway.csproj
- powershell/build.ps1
Remove dependency on PemUtils for RSA key operations in the PowerShell module, which was important for New-RsaKeyPair to work properly even in Windows PowerShell, given that the new Devolutions Gateway standalone needs a generated key pair at installation. The current module would already detect PowerShell 7 and use the newer APIs, but the fallback was still PemUtils in Windows PowerShell.
The remaining internal function that won't work in Windows PowerShell is ConvertTo-RsaPrivateKey which converts a PEM private key to System.Security.Cryptography.RSA which we then use to sign tokens in New-JwtRs256, called from New-DGatewayToken. We don't need to sign tokens from the installer, so I just throw an exception for now if we're trying to use it from Windows PowerShell. However, porting would …
> switch from PemUtils to Picky in PowerShell module

- powershell/DevolutionsGateway/DevolutionsGateway.psd1
- powershell/DevolutionsGateway/Public/DGateway.ps1
- powershell/pester/Config.Tests.ps1
Add basic web app (standalone) configuration in the PowerShell module, excluding the list of users with their hashes. It would actually be a lot easier from PowerShell if we could switch to using a separate users.txt file with <user>:<hash> line entries. We also still need argon2 hashing from PowerShell, which we're hoping we can get from picky.
> add basic webapp configuration to PowerShell module

- package/WindowsManaged/.editorconfig
- package/WindowsManaged/Actions/CustomActions.cs
- package/WindowsManaged/Actions/GatewayActions.cs
- package/WindowsManaged/DevolutionsGateway.csproj
- package/WindowsManaged/Dialogs/CertificateDialog.Designer.cs
- package/WindowsManaged/Dialogs/CertificateDialog.cs
- package/WindowsManaged/Dialogs/GatewayDialog.cs
- package/WindowsManaged/Dialogs/Wizard.cs
- package/WindowsManaged/Program.cs
- package/WindowsManaged/Properties/Constants.cs
- package/WindowsManaged/Properties/GatewayProperties.g.cs
- package/WindowsManaged/Properties/GatewayProperties.g.tt
- package/WindowsManaged/Properties/WixProperty.cs
- package/WindowsManaged/README.md
- powershell/DevolutionsGateway/DevolutionsGateway.psd1
Adds support for using Windows certificate store parameters in the managed Windows installer.
If certificate selection is required (i.e. an https listener is being created), the user will now be prompted with "External" and "System" options for certificate selection. "External" functions as before; "System" allows the user to select the store location and name, and search for certificates by thumbprint or subject name.
The user must select _one_ certificate in this mode. If multiple certificates match their search, they will be forced to choose one. The certificate mode, store location, name and certificate subject will be configured in the Gateway .cfg file.
https://github.com/Devolutions/devolutions-gateway/assets/2573400/c342785d-f221-43e8-bec6-7307458a3530
Notes:
- The "Search" screen …
> feat(installer): add Windows sytem certificate support to managed installer

- .github/workflows/ci.yml
- .github/workflows/package.yml
Add the standalone gateway web UI to CI and package workflows.
There is a lot of room for improvement; this is the bare minimum work to make the files available at packaging time.
> ci: add standalone web ui to CI builds

- devolutions-gateway/src/api/webapp.rs
An oversight in the endpoint for signing webapp token was discovered. The configured maximum lifetime wasn’t properly enforced. Fortunately, this bug was discovered by our security team before the feature was released and delivered.
As such, there is no need to create a security advisory.
cc @pdugre
> fix(dgw): validate maximum lifetime for webapp token

- .github/workflows/ci.yml
- .github/workflows/package.yml
- .github/workflows/release.yml
- ci/tlk.ps1
- package/WindowsManaged/DevolutionsGateway.csproj
- package/WindowsManaged/Program.cs
Integrate the managed wixsharp Windows installer into the build system.
> [!IMPORTANT] 
> The previous WiX installer is still built. In CI and packaging it gets a "-legacy" suffix on the .msi filename. In release, only the legacy installer is currently released - this is a safety hatch in case we need to make a new release between now and 2024.1. Once we are ready to commit; the legacy installer can be removed from the build system.
> These changes add a fair amount of complexity to the build system, which can be removed again once we're committed (2024.1)
In Dev and CI; the managed installer is built using the wixsharp project and msbuild. This is convenient and produces a multi-language MSI in a single build step.
In Packaging, it's necessary to code sign the new runtime components of …
> ci: build managed installer in workflows

- README.md
- devolutions-gateway/src/api/webapp.rs
- devolutions-gateway/src/config.rs
- devolutions-gateway/tests/config.rs
- devolutions-gateway/tests/webapp.rs
- docs/COOKBOOK.md
This changes the `Users` option into `UsersPath` for specifying a path to a users.txt file.
By default, the path is `%ProgrameData%/Devolutions/Gateway/users.txt`.
For each line such as `<user>:<hash>`:
* `<user>`: The name of the user.
* `<hash>`: Hash of the password in the PHC string format.
Blank lines and lines starting by `#` are ignored.
Issue: DGW-127
> feat(dgw): store users list in a users.txt file

- webapp/.gitignore
- webapp/src/client/app/modules/base/menu/app-menu.component.html
- webapp/src/client/app/modules/base/menu/app-menu.component.scss
- webapp/src/client/app/modules/base/menu/app-menu.component.ts
- webapp/src/client/app/modules/login/login.component.html
- webapp/src/client/app/modules/login/login.component.ts
- webapp/src/client/app/shared/services/auth.service.ts
- webapp/src/client/app/shared/services/navigation.service.ts
- webapp/src/client/app/shared/services/web-session.service.ts
Implement the none authorization for the web app login.
Also adjusted the token lifespan. I had set it for 10 minutes for testing, but now it's set to the specified 8 hours.
Edited the git ignore to remove some of the 'extra' angular stuff that is not required for source control.
Small adjustments to the UI:
- login page to handle the auto-login smoothly.
- moved the logout button to be positioned at the bottom of the left hand sidebar.
> feat(dgw): implement none authorization type for webapp login

- powershell/DevolutionsGateway/DevolutionsGateway.psd1
- powershell/DevolutionsGateway/Public/DGateway.ps1
- powershell/DevolutionsGateway/src/DevolutionsGateway.csproj
- powershell/pester/Users.Tests.ps1
Add PowerShell user management cmdlets with argon2 password hashing. Here's my set of commands to bootstrap a localhost HTTP configuration with user "admin" and password "yolo123!" for local development:
```
$ConfigPath = Join-Path (Get-Location) 'config'
$Env:DGATEWAY_CONFIG_PATH="$ConfigPath"
$WebAppPath = Join-Path (Get-Location) 'webapp'
$Env:DGATEWAY_WEBAPP_PATH="$ConfigPath"
New-Item $ConfigPath -ItemType Directory -ErrorAction SilentlyContinue
.\powershell\build.ps1
pwsh.exe
Import-Module .\powershell\DevolutionsGateway
$Hostname = "localhost"
$Username = "admin"
$Password = "yolo123!"
$HttpListener = New-DGatewayListener 'http://*:7171' 'http://*:7171'
$WebApp = New-DGatewayWebAppConfig -Enabled $true -Authentication Custom
$ConfigParams = @{
Hostname = $Hostname
Listeners = …
```
> add powershell user management with argon2 password hashing

- .github/workflows/ci.yml
- package/WindowsManaged/Actions/CustomActions.cs
- package/WindowsManaged/Actions/GatewayActions.cs
- package/WindowsManaged/DevolutionsGateway.csproj
- package/WindowsManaged/Dialogs/AccessUriDialog.Designer.cs
- package/WindowsManaged/Dialogs/AccessUriDialog.cs
- package/WindowsManaged/Dialogs/CertificateDialog.Designer.cs
- package/WindowsManaged/Dialogs/CertificateDialog.cs
- package/WindowsManaged/Dialogs/CustomizeDialog.cs
- package/WindowsManaged/Dialogs/ListenersDialog.Designer.cs
- package/WindowsManaged/Dialogs/ProgressDialog.cs
- package/WindowsManaged/Dialogs/PublicKeyDialog.Designer.cs
- package/WindowsManaged/Dialogs/PublicKeyDialog.cs
- package/WindowsManaged/Dialogs/WebClientDialog.Designer.cs
- package/WindowsManaged/Dialogs/WebClientDialog.cs
- package/WindowsManaged/Dialogs/WebClientDialog.resx
- package/WindowsManaged/Dialogs/Wizard.cs
- package/WindowsManaged/Helpers/StockIcon.cs
- package/WindowsManaged/Program.cs
- package/WindowsManaged/Properties/Constants.cs
- package/WindowsManaged/Properties/GatewayProperties.g.cs
- package/WindowsManaged/Properties/GatewayProperties.g.tt
- package/WindowsManaged/README.md
- package/WindowsManaged/Resources/Includes.cs
- webapp/.gitignore
When customizing the install, the user is now prompted to setup the standalone web application (and, optionally, generate a certificate and/or provisioner key pair - in this case, the relevant dialogs are skipped in the wizard).
An additional dialog allows configuring the authentication mode and (if relevant) a default user.
If the file "users.txt" exists in the %programdata% directory, the installer will enforce it's permissions with the following ACL:
>NT AUTHORITY\SYSTEM Allow FullControl, NT AUTHORITY\LOCAL SERVICE Allow Write, ReadAndExecute, Synchronize, BUILTIN\Administrators Allow FullControl
Finally, I added a prerequisite check for the installed .NET Framework version.
> [!NOTE] 
> This is an intermediate PR and final polish (for example, but not limited to: finishing …
> feat(installer): initial webapp integration

- package/WindowsManaged/Actions/CustomActions.cs
- package/WindowsManaged/Actions/GatewayActions.cs
- package/WindowsManaged/Actions/WinAPI.cs
- package/WindowsManaged/DevolutionsGateway.csproj
- package/WindowsManaged/Dialogs/CertificateDialog.Designer.cs
- package/WindowsManaged/Dialogs/CustomizeDialog.cs
- package/WindowsManaged/Dialogs/NgrokListenersDialog.Designer.cs
- package/WindowsManaged/Dialogs/NgrokListenersDialog.cs
- package/WindowsManaged/Dialogs/NgrokListenersDialog.resx
- package/WindowsManaged/Dialogs/WebClientDialog.Designer.cs
- package/WindowsManaged/Dialogs/Wizard.cs
- package/WindowsManaged/Helpers/StockIcon.cs
- package/WindowsManaged/Program.cs
- package/WindowsManaged/Properties/GatewayProperties.g.cs
- package/WindowsManaged/Properties/GatewayProperties.g.tt
- package/WindowsManaged/Properties/WixProperty.cs
This PR adds the ability to configure ngrok ingress via the Windows installer
> [!NOTE]  
> Th is an intermediate PR. UI refinement, feedback items, strings and localization are still to be addressed. But the installer might be considered feature complete for the 2024.1 release at this point.
Basic ngrok options are available and supplant the traditional HTTP/TCP listener configuration. Certificate configuration is also not required.
Traditionally the installer asked the Gateway to generate an initial gateway.json in all modes. This is no longer acceptable: a gateway.json might exist from a previous install and already contain an HTTP/TCP listener configuration. If no gateway.json exists, the `--config-init-only` generates an HTTP/TCP configuration.
Now, when choosing to configure via the …
> feat(installer): add ngrok configuration support

- README.md
- devolutions-gateway/src/api/webapp.rs
- devolutions-gateway/src/config.rs
- devolutions-gateway/tests/config.rs
~~This also removes the `DGATEWAY_WEBAPP_PATH` env variable.~~
The `DGATEWAY_WEBAPP_PATH` env variable is conserved.
For example:
```json
{
"WebApp": {
"Enabled": true,
"Authentication": "Custom",
"StaticRootPath": "./webapp"
},
}
```
This will reproduce the behavior of the initial implementation, finding the webapp folder in the current working directly.
cc @kristahouse
> fix(dgw): debug option to set the webapp path

- devolutions-gateway/src/token.rs
- tools/tokengen/src/main.rs
- utils/dotnet/Devolutions.Gateway.Utils.Tests/JsonSerializationTests.cs
- utils/dotnet/Devolutions.Gateway.Utils/src/NetworkScanClaims.cs
1. added Network Scan jwt claim tyoe to tokengen
2. added Network Scan jwt claim tyoe to .Net, to be used in DVLS and RDM
3. added claim type in token.rs, allow future authentication to be done
> feat(Network-Scan): Added Network Scan JWT token type

- Cargo.lock
- crates/network-scanner-net/Cargo.toml
- crates/network-scanner-net/src/lib.rs
- crates/network-scanner-net/src/runtime.rs
- crates/network-scanner-net/src/tests.rs
- crates/tracing-cov-mark/Cargo.toml
- crates/tracing-cov-mark/src/lib.rs
- devolutions-gateway/Cargo.toml
- devolutions-gateway/tests/webapp.rs
@irvingoujAtDevolution this is what I mentioned you earlier this week.
We can assert that some code path has been exercised using this tracing subscriber and helper.
> test: initial tracing-cov-mark crate implementation

- devolutions-gateway/src/tls.rs
fix made by clippy with version 0.1.14
```
PS C:\Users\jou\code\devolutions-gateway> cargo clippy --version
clippy 0.1.74 (a28077b2 2023-12-04)
PS C:\Users\jou\code\devolutions-gateway> cargo --version
cargo 1.74.1 (ecb9851af 2023-10-18)
PS C:\Users\jou\code\devolutions-gateway> rustup --version      
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.74.1 (a28077b28 2023-12-04)`
```
> refactor(dgw): fix clippy warning

- devolutions-gateway/src/token.rs
As per previous Slack discussion, netowrk scan token should be used only once.
> fix(dgw): make NETSCAN tokens short-lived

- package/WindowsManaged/Dialogs/AccessUriDialog.cs
- package/WindowsManaged/Dialogs/CertificateDialog.Designer.cs
- package/WindowsManaged/Dialogs/CertificateDialog.cs
- package/WindowsManaged/Dialogs/ListenersDialog.cs
- package/WindowsManaged/Dialogs/PublicKeyDialog.Designer.cs
- package/WindowsManaged/Dialogs/PublicKeyDialog.cs
- package/WindowsManaged/Helpers/Localization.cs
- package/WindowsManaged/Program.cs
- package/WindowsManaged/Properties/Constants.cs
- package/WindowsManaged/Resources/DevolutionsGateway_en-us.wxl
- package/WindowsManaged/Resources/DevolutionsGateway_fr-fr.wxl
- package/WindowsManaged/Resources/Strings.g.cs
- package/WindowsManaged/Resources/Strings_en-US.json
- package/WindowsManaged/Resources/Strings_fr-FR.json
Fixes an important installer bug (the customization UI should only be shown on a first install, not on upgrades).
Additionally, incorporated feedback items:
- The Access URI hostname will default to the FQDN of the machine if it's domain-joined (rather than just the NetBIOS name)
- Added an "Enter search text here" cue banner on the system certificate selection page
- Default the Access URI protocol to whatever was chosen for the HTTP listener. The user can still customize.
- If configuring as a "companion" install (i.e. no ngrok, no standalone web application) provide a hint linking to the Devolutions Server/Hub documentation on the encryption keys page ("Find your public key for [Devolutions Server](https://docs.devolutions.net/server/dgw/server-configuration/) or [Devolutions …
> feat(installer): installer revision based on feedback

- Cargo.lock
- crates/network-scanner/Cargo.toml
- crates/network-scanner/examples/mdns.rs
- crates/network-scanner/examples/scan.rs
- crates/network-scanner/src/lib.rs
- crates/network-scanner/src/mdns.rs
- crates/network-scanner/src/scanner.rs
- crates/network-scanner/src/task_utils.rs
- devolutions-gateway/src/api/mod.rs
- devolutions-gateway/src/api/network_scan.rs
Add mdns to network scan, added some extra helper method for better readbility and maintainbility.
Open for review but needs to wait for the #689 to be merged first
> feat(dgw): mDNS network scan support

- devolutions-gateway/src/api/network_scan.rs
rename type ty to ap, stay consistent with rest of the gateway
> fix(dgw): rename type for network scan to ap(application protocol)

- devolutions-gateway/src/api/network_scan.rs
Need to fix the fact that the service indentification is currently based on port. For mdns, the service type is given, so no need to do port to service mapping anymore. but that is a TODO in the future. 
For this PR, we just add the port 3283 to common ports.
edit: #702 allows service type obtained by mdns to be passed to the caller
> fix(dgw): add ARD to common ports to scan

- crates/network-scanner/examples/mdns.rs
- crates/network-scanner/src/mdns.rs
- crates/network-scanner/src/scanner.rs
- crates/network-scanner/src/task_utils.rs
- devolutions-gateway/src/api/network_scan.rs
Current implementation only guesses what service type it is by using port, mdns allows more than just port guessing, enable passing kown protocol types to caller, for unknwon protocols, the caller can keep guess what it is using port.
> fix(dgw): forward protocol advertised by mDNS scanner

- package/WindowsManaged/DevolutionsGateway.csproj
- package/WindowsManaged/Dialogs/AccessUriDialog.cs
- package/WindowsManaged/Dialogs/CustomizeDialog.Designer.cs
- package/WindowsManaged/Dialogs/CustomizeDialog.cs
- package/WindowsManaged/Dialogs/GatewayDialog.cs
- package/WindowsManaged/Dialogs/ListenersDialog.Designer.cs
- package/WindowsManaged/Dialogs/ListenersDialog.cs
- package/WindowsManaged/Dialogs/NgrokListenersDialog.cs
- package/WindowsManaged/Dialogs/VerifyReadyDialog.cs
- package/WindowsManaged/Dialogs/WebClientDialog.cs
- package/WindowsManaged/Dialogs/Wizard.cs
- package/WindowsManaged/Program.cs
- package/WindowsManaged/Resources/DevolutionsGateway_en-us.wxl
- package/WindowsManaged/Resources/DevolutionsGateway_fr-fr.wxl
- package/WindowsManaged/Resources/Includes.cs
- package/WindowsManaged/Resources/Strings.g.cs
- package/WindowsManaged/Resources/Strings_en-US.json
- package/WindowsManaged/Resources/Strings_fr-FR.json
Bug fixes and refinement to the Windows installer based on feedback:
- Bump wixsharp dependency to 1.25.1 and implement a basic [unhandled exception handler](https://github.com/oleg-shilo/wixsharp/issues/1446)
- Fix display "flicker" when skipping dialogs due to conditions (instead of "fast forwarding" or "rewinding" through the dialog sequence, I realize we can jump to arbitrary indexes 🙌)
- Improve WinForms correctness (UI initialization in `OnLoad` instead of constructors) and fix one possible crash in the listener's dialog
- Tweak the info message on the customization screen to make the options more clear
- Fix a bug where top-level properties (e.g. configure ngrok, configure web app) could hold bad values after going back-and-forth
> feat(installer): bug fixes and refinement based on feedback

- Cargo.lock
- ci/tlk.ps1
- devolutions-gateway/Cargo.toml
OpenSSL was still a link dependency brought in by reqwest in Linux. We build for Linux on Ubuntu 20.04 and expect it to be forward-compatible, but this is not possible with OpenSSL, as the library is different and incompatible, especially since OpenSSL 1.1 is now in its EOL and Ubuntu 22.04 has moved on to OpenSSL 3.
Our last .deb package release somehow declares a dependency on libssl, but I'm not sure where it's coming from. Maybe we already removed it from the latest master branch and somehow re-introduced the OpenSSL link dependency by mistake. In any case, I at least updated the declared distro name to "focal" (20.04) since it was still saying "xenial" (16.04).
@CBenoit one last thing I want to make sure is that by switching to rustls for reqwest that we still validate against the …
> build(dgw): eliminate openssl link dependency on Linux

- devolutions-gateway/src/api/mod.rs
As mentioned here: https://github.com/Devolutions/devolutions-gateway/pull/706#discussion_r1493775706
If the intention is to have multiple endpoints related to network exploration, let’s nest everything under `/jet/net/`:
- `GET /jet/net/scan`
- `GET /jet/net/config`
- …
I want to make this change before we cut the release because it’s harder to change later because of our forward compatibility requirements.
> fix(dgw): /jet/network-scan -> /jet/net/scan

- devolutions-gateway/src/api/webapp.rs
Added the ability to generate netscan tokens for the webapp.
I also removed the "destination" field from the returned truple as with the netscan it's not relevant, hopefully that is ok, it was only used for logging.
> feat(dgw): generate netscan token for webapp

- devolutions-gateway/src/ngrok.rs
- devolutions-gateway/src/service.rs
Our installer is allowing the 0.0.0.0/0 CIDR by default because premium plans need the IP restrictions to be configured or just all external traffic. However this doesn’t play well with the free plan. This patch is using a dirty trick to detect the free plan and ignores the IP restriction configuration when it is detected.
Issue: DGW-134
> fix(dgw): better support for ngrok free plan

- devolutions-gateway/src/api/net.rs
- devolutions-gateway/src/config.rs
Until we are satisfied with the API for `/jet/net/config`, the endpoint is hidden by default.
The rationale is:
- Users may use a newer RDM/DVLS version which will poke the new endpoint without updating the Devolutions Gateway service, and
- the error may be cryptic if the endpoint already existed. It’s simpler to troubleshoot a 404 error (upgrade required) not found than, e.g., a de-serialization error (upgrade required? bug?).
Developers can enable the unstable API by setting the new debug flag:
```json
{
// -- snip -- //
"__debug__": {
"enable_unstable": true
}
}
```
> feat(dgw): hide unstable API behind a debug flag

- powershell/build.ps1
PowerShell uses a default directory structure for native DLLs than the .NET runtime, but it also (annoyingly) always assumes there is no "lib" prefix, while .NET expects prefix-less library names on Windows, and prefixed library names on non-Windows. This pull request just removes the "lib" prefix as does the native DLL directory structure conversion.
https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/writing-portable-modules?view=powershell-7.4&viewFallbackFrom=powershell-7#dependency-on-native-libraries
> fix lib prefix for PowerShell native library loader

- package/WindowsManaged/Actions/GatewayActions.cs
In the following conditions:
- Fresh installation
- Installing without UI (quiet or silent)
- Without passing a custom `INSTALLDIR` to msiexec
The action that sets the ARP (Add/Remove Programs) install location will use the default value for `INSTALLDIR`. However, it's sequenced too early: a default can't be resolved until after __CostFinalize__. In this case, we end up writing an empty string to the install location field.
> fix(installer): properly write ARP InstallLocation on fresh installs

- .github/workflows/package.yml
We hardcoded the path to the WiX Toolset binaries as `C:\Program Files (x86)\WiX Toolset v3.11\bin`, but the actual path is now different. Probably because GitHub updated the runner. Now it’s `Wix Toolset v3.14`. I used a regex to select the right folder regardless of the installed version so we don’t have to lose time updating the workflow each time.
> ci(package): fix WiX Toolset path

- package-lock.json
- webapp/package-lock.json
- webapp/package.json
- Support for client-side rendered hardware-accelerated cursors
> feat(webapp): bump iron-remote-gui-vnc to 0.2.1

- .github/workflows/package.yml
- .github/workflows/release.yml
Add an archive of the web client to the GitHub release. The archive is named `devolutions_gateway_webapp_{version}.tar.gz`
> ci: add a webclient archive to the GitHub release

- .github/workflows/ci.yml
- Cargo.lock
- ci/tlk.ps1
- devolutions-gateway/Cargo.toml
Add an arm64 build for Devolutions Gateway on Linux. Currently the binary is not packaged in a .deb nor is a container created. This will follow after the next round of updates to .deb packaging.
> ci(dgw): add arm64 build for Linux

- .github/workflows/release.yml
- package/Linux/Dockerfile
- package/Windows/Dockerfile
A minimum viable update to the containers produced for release.
Containers are now based on the base `powershell` images from [Microsoft](https://hub.docker.com/_/microsoft-powershell). This gives us a working PowerShell Core installation from scratch.
Containers are uplifted to newer images; particularly in the Linux case `buster` is quite old and Devolutions Gateway won't even run any more (the packaged `glibc` is too old):
buster-slim > bullseye-slim (Debian 11)
servercore-ltsc2019 > server core-ltsc2022
nanoserver-1809 > lts-nanoserver-ltsc2022
I added the web front end to the container (on Windows, in C:\Devolutions\Gateway\webapp\...; on Linux in /usr/share/devolutions-gateway/...). The paths should be resolvable by the Gateway without further configuration.
Finally, replace the …
> ci: update containers

- .github/workflows/ci.yml
Begin the migration to `@v4` workflow actions; `@v3` actions use a deprecated node version and will cease to function at some point.
Importantly, `upload-artifact@v4` creates immutable artifacts. When uploading artifacts from a matrix, it's possible to upload individual artifacts then merge them with `actions/upload-artifact/merge@v4`.
> ci: update CI workflow actions

- .github/workflows/package.yml
Follow up to #778. Upgrade actions versions in the package workflow.
Historically we had a dual mechanism for downloading CI artifacts. Why? We are specifying the run number of the CI workflow to download artifacts from. If the individual workflows (CI -> Package -> Release) are run individually by `workflow_dispatch`, each workflow will have a distinct run number and we can download it's artifacts using `gh`. If the workflows are dispatched from the `create_new_release` wrapper (`workflow_call`), there is one common run number. However, historically `gh` couldn't handle this situation and we were forced to use `actions/download-artifact` to get the artifacts for the _current_ run.
According to [#5625](https://github.com/cli/cli/issues/5625#issuecomment-1806284038) this issue is corrected …
>  ci: update package workflow actions

- .github/workflows/create-new-release.yml
- .github/workflows/release.yml
> ci: release workflow action update

- .github/workflows/ci.yml
- ci/tlk.ps1
- package/Linux/gateway/template/rules
Build an arm64 .deb package.
I haven't been able to figure out to get `dh_shlibdeps` to operator on a sysroot (even when pointing it to an arm64 sysroot using the `-l` argument, it complains that it can't check `libc` dependencies because it's not installed by a package.
For now, dependency information is hardcoded for arm64.
> ci: build arm64 deb

- .github/workflows/README.md
- .github/workflows/create-new-release.yml
- .github/workflows/package.yml
- .github/workflows/release.yml
Fixes issues with immutable artifacts when running the overall "create new release" workflow. Additionally, adds a "dry-run" option to that workflow and does some small cleanup (inputs from both `workflow_dispatch` and `workflow_call` are now both accessible through the `inputs` context).
> ci: fix artifact idempotency

- package/WindowsManaged/Dialogs/ListenersDialog.cs
Bind the test listener to "localhost" instead of any address (0.0.0.0). Additionally, fix a potential unhandled exception when starting the test listener.
> fix(installer): prevent possible prompt for firewall access in Windows installer

- .github/workflows/package.yml
The package workflow has a sequencing error: we need to `tar` the web client _after_ repackaging the Windows Installer; otherwise the tarball gets packaged instead of the directory.
> ci: fix packaging of web client

- .github/workflows/release.yml
We are trying to rename the filename of the deb package to append the ".0", but it already contains this suffix.
> ci: fix OneDrive upload step in release workflow

- jetsocat/nuget/Devolutions.Jetsocat.targets
In NET 8, the final build does not deploy `jetsocat` to the application bundle "Resources" directory because it doesn't have a content type set. This is documented [here](https://github.com/xamarin/xamarin-macios/blob/main/dotnet/BundleContents.md).
> ci: set content type on macOS jetsocat binary

- webapp/angular.json
- webapp/src/client/app/modules/web-client/ard/web-client-ard.component.ts
- webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.ts
- webapp/src/client/app/modules/web-client/ssh/web-client-ssh.component.ts
- webapp/src/client/app/modules/web-client/telnet/web-client-telnet.component.ts
- webapp/src/client/app/modules/web-client/vnc/web-client-vnc.component.ts
- webapp/src/client/app/shared/bases/base-web-client.component.ts
- webapp/src/client/app/shared/services/analytic.service.ts
- webapp/src/client/app/shared/services/api.service.ts
- webapp/src/environments/environment.development.ts
- webapp/src/environments/environment.production.ts
- webapp/src/environments/environment.ts
Enable analytics on Gateway Standalone with OpenSearch.
Place to pay attention to:
There is really no elegant solution to use system environment variables in angular. These env vars are hardcoded  in the environment file as suggested by Angular documentation. We could argue that it will be visible to our user in production anyway so it is not a bit deal if we expose it here.
Updated some functions that was originally not used.
> feat(dgw): add analytics to gateway standalone

- .github/workflows/ci.yml
The web client can't be built in a fork, because it requires access to secrets. This also prevents packaging working.
This PR disables those features in different repos. For now that will allow the core CI to run but preclude building changes to the web client, .deb or Windows installer.
> ci: skip web client and packaging in forks

- Cargo.lock
- devolutions-gateway/Cargo.toml
- devolutions-gateway/src/api/heartbeat.rs
The total and available space used for storing recordings is now returned in the heartbeat response.
If the system does not support this operation, the fields are excluded from the response.
Issue: DGW-100
```
$ curl -H "Accept: application/json" -H "Authorization: Bearer $(./tools/tokengen/target/release/tokengen --provisioner-key ./config/provisioner.priv.key scope gateway.heartbeat.read)" http://127.0.0.1:7171/jet/heartbeat
{"id":"aa0b2a02-bbbb-aaaa-bbbb-03c6391b86fb","hostname":"localhost","version":"2024.1.5","running_session_count":0,"recording_storage_total_space":737616650240,"recording_storage_available_space":199578578944}
```
> feat(dgw): return disk space available for recordings

- devolutions-gateway/src/api/jrec.rs
- devolutions-gateway/src/extract.rs
- devolutions-gateway/src/token.rs
- utils/dotnet/Devolutions.Gateway.Utils/src/AccessScope.cs
This new endpoint is used for deleting recordings and allow the service provider (e.g.: DVLS) to delete them according to its policy.
Issue: DGW-96
> feat(dgw): add /jet/jrec/delete/<ID> endpoint

- devolutions-gateway/src/api/heartbeat.rs
> feat(dgw): add recording_storage_is_writeable in heartbeat

- .github/workflows/ci.yml
- .github/workflows/package.yml
- package/WindowsManaged/DevolutionsGateway.csproj
- package/WindowsManaged/Program.cs
- package/WindowsManaged/Resources/Includes.cs
Install the Devolutions Gateway service under the `NetworkService` account instead of `LocalSystem`. This significantly reduces the permissions available to the service account.
Relevant file paths are updated to grant `NetworkService` the appropriate access. Broadly, file permissions in %programdata%/Devolutions/Gateway are inherited from the "Gateway" parent directory. In my tests there is no issue; however it could cause a problem if users have manually adjusted file permissions or customized their setup in unforeseen ways.
> [!WARNING]  
> We attempted this modification before but backed out again after at least one breaking problem in a customer environment. This is a change that we must make and we are likely in a better footing now to diagnose and deal with any resultant problems. …
> fix(installer)!: install Gateway service as NetworkService

- webapp/src/client/app/shared/services/net-scan.services.ts
Before: Netscan request is fired whenever this netscan component is mounted
After: Netscan request only one time per each web session. All results are cached in memory.
> fix(webapp): fix netscan result duplicate and performance improvement

- webapp/src/client/app/modules/base/menu/app-menu.component.ts
Before:  show version update icon when version  is different, the logic is that user would not be able to install a version we haven't released.
After: strictly check the version, only show icon if the latest version is greater than the current version
Issue: DGW-182
> fix(webapp): fix version compare logic

- webapp/package-lock.json
- webapp/package.json
Downgraded the Primeng package as the console log was introduced in version 16.5.0.
Upgrading to the next Primeng version would cause a cascade of updates for the majority of the angular dependencies. This includes upgrading the rxjs package, however, in doing so would cause a conflict in the web packages for IronRDP & IronVNC. We should make future plans to perform this update.
Issue: DGW-164
> DGW-164-Webapp-Suspicious-e-logs-in-web-application

- webapp/src/client/app/modules/web-client/form/form-components/ssh/ssh-form.component.ts
- webapp/src/client/app/modules/web-client/form/form-components/vnc/vnc-form.component.ts
- webapp/src/client/app/modules/web-client/form/web-client-form.component.ts
- webapp/src/client/app/shared/enums/web-client-auth-mode.enum.ts
- webapp/src/client/app/shared/services/web-form.service.ts
> fix(webapp): connect session button stays grayed out intermittently

- .github/workflows/ci.yml
Current CI build web app without optimization, we hence packed source map together with our Windows installer.
This will allow analytic data to get sent under correct index.
> build(webapp): build using production profile

- powershell/DevolutionsGateway/Private/CertificateHelper.ps1
When we call [Encoding.GetString(byte[])](https://learn.microsoft.com/en-us/dotnet/api/system.text.encoding.getstring?view=net-8.0#system-text-encoding-getstring(system-byte())) from a C# PowerShell runspace (e.g. DPS Console), we are getting the following error:
>The following exception occurred while retrieving member "GetString": "GenericArguments[0], 'System.ReadOnlySpan`1[System.Byte]', on 'System.Func`2[T,TResult]' violates the constraint of type 'T'."
I don't know why. This results in an empty `$PemData` which obviously can't be parsed.
The workaround is to read the certificate and private key file directly as UTF8, rather than getting the UTF8 representation of the data.
> fix(pwsh): fix reading .pem files from PowerShell runspace

- devolutions-gateway/Cargo.toml
- devolutions-gateway/src/lib.rs
- devolutions-gateway/src/listener.rs
Most browsers will keep HTTP connections open to increase throughput when performing subsequent transactions.
For simplicity, we don’t distinguish between idle and non-idle connections.
> perf(dgw): keep HTTP connections open for 10 minutes

- package/WindowsManaged/Actions/CustomActions.cs
- package/WindowsManaged/Actions/GatewayActions.cs
- package/WindowsManaged/Actions/WinAPI.cs
Use Win32 `SetFileSecurity` to fix the permissions on the program data and users database, instead of shelling out to cacls.exe.
> fix(installer): use Win32 to set file permissions

- devolutions-gateway/src/ngrok.rs
Now properly fallbacks to disabling IP restriction rules for TCP listeners as well.
Issue: DGW-193
> fix(dgw): IP restrictions fallback for ngrok TCP listeners

- .github/workflows/ci.yml
I also removed the `-Force` parameter as it does nothing as per the doc.
> The proxy cmdlet ignores this parameter since it's not supported
> by `Install-PSResource`.
https://learn.microsoft.com/en-us/powershell/module/powershellget/install-module?view=powershellget-3.x#-force
> ci: bump required Pester version to 5.6.0

- utils/dotnet/Devolutions.Gateway.Utils.Tests/JsonSerializationTests.cs
- utils/dotnet/Devolutions.Gateway.Utils.Tests/TargetAddrTests.cs
- utils/dotnet/Devolutions.Gateway.Utils.Tests/TokenUtilsTests.cs
- utils/dotnet/Devolutions.Gateway.Utils/Devolutions.Gateway.Utils.csproj
- utils/dotnet/Devolutions.Gateway.Utils/src/TargetAddr.cs
Make the `TargetAddr` more robust and easier to use by checking for invalid ports in its constructor.
> fix(dotnet-utils): handle invalid ports in TargetAddr constructor

- README.md
- package/WindowsManaged/.gitignore
- package/WindowsManaged/Actions/CustomActions.cs
- package/WindowsManaged/Actions/FileAccess.cs
- package/WindowsManaged/Actions/GatewayActions.cs
- package/WindowsManaged/Actions/Impersonation.cs
- package/WindowsManaged/Actions/WinAPI.cs
- package/WindowsManaged/Configuration/Gateway.cs
- package/WindowsManaged/Configuration/Listener.cs
- package/WindowsManaged/Configuration/Ngrok.cs
- package/WindowsManaged/Configuration/SubProvisionerPublicKey.cs
- package/WindowsManaged/Configuration/Subscriber.cs
- package/WindowsManaged/Configuration/Tunnel.cs
- package/WindowsManaged/Configuration/WebApp.cs
- package/WindowsManaged/DevolutionsGateway.csproj
- package/WindowsManaged/Dialogs/ExitDialog.Designer.cs
- package/WindowsManaged/Dialogs/ExitDialog.cs
- package/WindowsManaged/Program.cs
- package/WindowsManaged/Properties/GatewayProperties.g.cs
- package/WindowsManaged/Properties/GatewayProperties.g.tt
- package/WindowsManaged/Resources/DevolutionsGateway_en-us.wxl
- package/WindowsManaged/Resources/DevolutionsGateway_fr-fr.wxl
- package/WindowsManaged/Resources/Includes.cs
- package/WindowsManaged/Resources/Strings.g.cs
- package/WindowsManaged/Resources/Strings_en-US.json
- package/WindowsManaged/Resources/Strings_fr-FR.json
This PR adds a basic configuration check to the installer. We attempt to assess effective file permissions and report any issues to the user.
> [!NOTE]  
> I'd consider these changes quite safe; there is no behaviour change in the rest of the installer; the biggest risk is that we have false positives (inadvertently report non-issues to the user).
> [!NOTE]  
> This PR also makes "Custom" authentication the default option when enabling the standalone web application.
This is extremely tricky to make correct: paths may or may not exist (and it's hard to know if the path doesn't exist, or we simply don't have access), querying Windows access control lists is convoluted - especially when dealing with nested files and folders and inheritance, and we may be dealing with shared network …
> feat(installer): add a basic configuration check

- .github/workflows/ci.yml
`macos-11` runners are deprecated and need to be updated.
I've moved incrementally to `macos-12` to reduce headaches right now: later versions (13 and 14) require us to choose between Intel and Apple Silicon runners, which might require some further tweaking on our side. So I'm kicking that can down the road 🙄
> ci: update macOS runner version

- Cargo.lock
- crates/devolutions-agent-shared/Cargo.toml
- crates/devolutions-agent-shared/src/date_version.rs
- crates/devolutions-agent-shared/src/lib.rs
- crates/devolutions-agent-shared/src/update_json.rs
- devolutions-agent/Cargo.toml
- devolutions-agent/src/config.rs
- devolutions-agent/src/main.rs
- devolutions-agent/src/service.rs
- devolutions-agent/src/updater/detect.rs
- devolutions-agent/src/updater/error.rs
- devolutions-agent/src/updater/integrity.rs
- devolutions-agent/src/updater/io.rs
- devolutions-agent/src/updater/mod.rs
- devolutions-agent/src/updater/package.rs
- devolutions-agent/src/updater/product.rs
- devolutions-agent/src/updater/productinfo/db.rs
- devolutions-agent/src/updater/productinfo/mod.rs
- devolutions-agent/src/updater/productinfo/test_asset_db
- devolutions-agent/src/updater/security.rs
- devolutions-agent/src/updater/uuid.rs
- package/AgentWindowsManaged/Resources/Includes.cs
This PR implements Gateway updater logic in `devolutions-agent`.
This update mechanism is triggered by changing `ProgramData/Devolutions/Agent/update.json` file, setting the required version to update the gateway.
Example `update.json`:
```json
{
"Gateway": {
"TargetVersion": "2024.2.1"
}
}
```
- Feature quite generic, so additional products could be updated later with the same mechanism by extending it
- Updater checks for already installed products on the system via MSI's upgrade code, so no spurious same-version MSI invocation is possible
- Requested Gateway version's MSI is gathered from [devolutions.net ](https://devolutions.net/productinfo.htm)
- `update.json` is created on first service start, and correct DACL is set to allow `NT AUTHORITY/Network Service` (which is used by …
> feat(agent): Devolutions Gateway service updater

- webapp/player/index.html
This needs to be published for side by side installed Gateway to work on recording players.
> fix(dgw): preserve DGW access URI base in recording player

- devolutions-gateway/src/proxy.rs
- devolutions-gateway/src/recording.rs
- devolutions-gateway/src/service.rs
- devolutions-gateway/src/session.rs
- tools/tokengen/src/main.rs
When recording flag is set and recording stream is closed, the associated session is killed within 10 seconds.
Issue: DGW-86
> fix(dgw): enforce recording policy

- devolutions-gateway/src/recording.rs
- devolutions-gateway/src/session.rs
- devolutions-gateway/src/subscriber.rs
The session and recording manager tasks were waiting for each other. This prevent the service from shutting down gracefully.
> fix(dgw): properly stop session and recording manager tasks

- devolutions-gateway/src/recording.rs
- devolutions-gateway/src/session.rs
Previously the policy wasn’t properly enforced when the session was started after the recording stream was opened.
In practice it’s very unlikely to happen since all clients we are aware of are opening the recording stream after the session is started. However, at the Devolutions Gateway level, opening the recording stream first is also a totally valid flow that we don’t forbid. This patch is accounting for this by updating the recording policy accordingly on recording manager side once the session is opened.
> fix(dgw): make recording policy enforcing more robust

- Cargo.lock
Updated curve25519-dalek from `4.1.2` to `4.1.3`
Updated h2 from `0.4.2` to `0.4.5`
Resolve the following dependabot alerts : 
https://github.com/Devolutions/devolutions-gateway/security/dependabot/101
https://github.com/Devolutions/devolutions-gateway/security/dependabot/114
> chore(deps): update curve25519-dalek and h2

- .github/workflows/ci.yml
- ci/tlk.ps1
This patch is preparing the CI for newer rustls which is using aws-lc-rs as the default crypto backend.
- Install a newer version of gcc for Linux. aws-lc-rs is rejecting some versions of gcc, including the one packaged by default with Ubuntu 20.04. It’s important because of this bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95189
- Install NASM when building with release / production profiles.
- Run tests using the dev profile. The tlk.ps1 script only allowed release and production profiles, but there is no reason to run the tests using these profiles.
> ci: prepare for aws-lc-rs

- Cargo.lock
- crates/devolutions-agent-shared/src/date_version.rs
- devolutions-agent/Cargo.toml
- devolutions-agent/src/config.rs
- devolutions-agent/src/lib.rs
- devolutions-agent/src/main.rs
- devolutions-agent/src/remote_desktop/graphics.rs
- devolutions-agent/src/remote_desktop/input.rs
- devolutions-agent/src/remote_desktop/mod.rs
- devolutions-agent/src/remote_desktop/tls.rs
- devolutions-agent/src/service.rs
- devolutions-agent/src/updater/io.rs
- devolutions-agent/src/updater/mod.rs
- devolutions-agent/src/updater/productinfo/db.rs
- devolutions-agent/src/updater/security.rs
- devolutions-gateway/Cargo.toml
- devolutions-gateway/src/config.rs
https://github.com/user-attachments/assets/55ee3fc5-32f0-42dd-9396-f6345f60a491
```json
{
"RemoteDesktop": {
"Enabled": true
}
}
```
```json
{
"RemoteDesktop": {
"Enabled": true,
"Certificate": "rdpserver.crt",
"PrivateKey": "rdpserver.key"
}
}
```
```json
{
"RemoteDesktop": {
"Enabled": true,
"Port": 9999
}
}
```
- The server only sends garbage rectangles, no real interaction is happening yet.
- There is currently no user authentification. Any username / password is accepted.
- `RdpServer` should implement `Send`.
- `RdpServer` should support multiple listener (bind) addresses.
- `RdpServer` should support graceful shutdown.
> feat(agent): initial Remote Desktop server module

- devolutions-agent/src/config.rs
Instead of special-casing the "Enabled" property of the updater module config, we require it when deserializing from JSON, and if the config of the updater is completely removed, we assume that it’s not enabled.
We keep the updater enabled in the default config file.
Future modules will be enabled by default when generating a fresh config file as well, but we won’t enable them by default implicitly when installing a newer version of the executable. It’s easier to predict how the agent will behave for both us and the user.
The default config file is:
```json
{
"Updater": {
"Enabled": true
}
}
```
This PR is not changing that.
> fix(agent): make UpdaterConf::enabled required when deserializing

- CHANGELOG.md
- cliff.toml
- The version number for the latest release wasn’t updated properly.
- This also removes non-user-facing notes.
- git-cliff will now ignore changes related to nuget, dotnet, openapi and other packages that are not following the same release process. Commits not following the conventional commits specification will be included by default in a "Please Sort" section so it’s easier to spot them when editing the changelog.
> chore: clean up changelog and update git-cliff config

- Cargo.lock
- devolutions-gateway/Cargo.toml
- devolutions-gateway/src/config.rs
- devolutions-gateway/src/service.rs
By default, we look for the library at `/usr/lib/libxmf.so` on Linux, and `xmf.dll` alongside the executable on Windows.
Developers may specify a different path to xmf.dll / libxmf.so using `lib_xmf_path` debug option:
```rust
{
"__debug__": {
"lib_xmf_path": "/usr/local/lib/libxmf.so"
}
}
```
> feat(dgw): dynamically load XMF native lib on startup

- devolutions-agent/src/config.rs
- devolutions-agent/src/service.rs
- devolutions-gateway/src/config.rs
This option will be used to enable unstable features which may break at any point. The first feature to be put behind this option is the remote desktop module.
> fix(agent): add "EnableUnstable" debug option

- webapp/src/client/app/modules/web-client/net-scan/net-scan.component.html
- webapp/src/client/app/modules/web-client/net-scan/net-scan.component.scss
- webapp/src/client/app/modules/web-client/web-client.module.ts
- webapp/src/client/app/shared/directives/tooltip-ellipsis.directive.ts
- webapp/src/client/app/shared/shared.module.ts
> fix(webapp): add tooltip ellipsis for long service names in netscan ui

- crates/devolutions-gateway-generators/src/lib.rs
- devolutions-gateway/src/api/fwd.rs
- devolutions-gateway/src/api/webapp.rs
- devolutions-gateway/src/generic_client.rs
- devolutions-gateway/src/jmux.rs
- devolutions-gateway/src/recording.rs
- devolutions-gateway/src/service.rs
- devolutions-gateway/src/session.rs
- devolutions-gateway/src/token.rs
- tools/tokengen/src/main.rs
Possible values are:
- `none`: No policy to enforce (recording is optional)
- `external`: An external application (e.g.: RDM) must push the recording stream via a separate websocket connection
- `proxy`: Session must be recorded directly at Devolutions Gateway level (not implemented yet)
> fix(dgw)!: jet_rec claim is now a string

- .github/workflows/release.yml
> ci(release): download Cadeau before building the containers

- .github/workflows/package.yml
- .github/workflows/release.yml
We are not checking out the repository in the release workflow.
Because of that, the `download-cadeau.ps1` file is not found.
The cleanest fix appears to follow how thing are already done
and to upload a new artifact containing the native libraries.
> ci: fix release workflow for containers

- crates/jmux-generators/src/lib.rs
- crates/jmux-proto/src/lib.rs
- crates/jmux-proto/tests/message.rs
- crates/jmux-proxy/src/lib.rs
By removing a few `to_vec()` calls and reusing the `Bytes` buffer as-is, perfomance of JMUX proxy is increased by ~62.3%.
Performance was measured using `iperf` on local network.
JMUX proxy performance before this patch:
> 0.0000-10.0493 sec  8.21 GBytes  7.02 Gbits/sec
JMUX proxy performance after this patch:
> 0.0000-19.0245 sec  25.2 GBytes  11.4 Gbits/sec
This is still 78.6% slower than jetsocat regular TCP port forwarding.
> perf(jetsocat,dgw): remove to_vec calls from JMUX implementation

- crates/jmux-proxy/src/codec.rs
- crates/jmux-proxy/src/lib.rs
This updates the decoder part of the JMUX codec.
The intention is to increase the maximum message size for JMUX message in the future.
By increasing the maximum size from 4k to 16k, an improvement of about 77.7% can be achieved when measuring using iperf.
With 4k:
> 0.0000-19.4523 sec  26.6 GBytes  11.7 Gbits/sec
With 16k:
> 0.0000-13.8540 sec  33.6 GBytes  20.8 Gbits/sec
> fix(jetsocat,dgw): allow bigger JMUX messages

- crates/jmux-proto/src/lib.rs
- crates/jmux-proto/tests/message.rs
- crates/jmux-proxy/src/lib.rs
We’re spending a lot of time dealing with `Bytes` and `BytesMut` in the JMUX sender task.
This patch is getting rid of the leftmost drop. We can actually reuse the `BytesMut` buffer between writes and greatly reduces allocation / de-allocation.
Performance is increased by ~26.3%.
Before this patch:
> 0.0000-19.0245 sec 25.2 GBytes 11.4 Gbits/sec
After this patch:
> 0.0000-17.1307 sec  28.8 GBytes  14.4 Gbits/sec
> perf(jetsocat,dgw): reuse buffer in JMUX sender task

- crates/jmux-proxy/src/lib.rs
Number of syscalls is reduced by using a `BufWriter` and waiting for write operations to stop before calling `flush()`.
Performance is increased by ~28.4%.
Before this patch:
> 0.0000-17.1307 sec 28.8 GBytes 14.4 Gbits/sec
After this patch:
> 0.0000-13.8483 sec  29.9 GBytes  18.5 Gbits/sec
> perf(jetsocat,dgw): limit number of syscalls in JMUX sender task

- crates/jmux-proto/src/lib.rs
- crates/jmux-proxy/src/codec.rs
- crates/jmux-proxy/src/lib.rs
Replace the old naive flow control algorithm.
The new algorithm is much more fair, and considerably reduce the number of WindowAdjust messages exchanged.
The idea is to send WindowAdjust messages only when the scheduler is idle, and focus on handling active connections as fast as possible without sending any WindowAdjust message when it is busy.
Before this patch, single connection:
> 0.0000-15.5887 sec  34.4 GBytes  18.9 Gbits/sec
After this patch + maximum message size of 4 kB, single connection:
> 0.0000-10.0490 sec  23.0 GBytes  19.7 Gbits/sec
Improvement of 4.2%.
This patch + maximum message size of 16 kB, single connection:
> 0.0000-10.0393 sec  30.6 GBytes  26.2 Gbits/sec
Improvement of 38.6%.
Before this patch, 10 parallel connections:
> [ ID] Interval       Transfer     Bandwidth …
> perf(jetsocat,dgw): rework flow control algorithm

- devolutions-gateway/src/recording.rs
On Windows, the default default share_mode set when opening a new file is `FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE`.
We now overrides the share_mode and set it to `FILE_SHARE_READ`.
This makes the recording process more robust by ensuring no other process can write or delete the files while the Devolutions Gateway is actively writing it.
> fix(dgw): set dwShareMode for recording files on Windows

- crates/jmux-proxy/src/lib.rs
- tools/jetsocat-bench.nu
The memory consumption of the JMUX proxy was unbounded because we used an unbounded mpsc channel for message passing.
Here is a `jetsocat-bench.nu` run against master:
```
2024-09-05T22:05:24.786|INF|=============
2024-09-05T22:05:24.786|INF|=== master ===
2024-09-05T22:05:24.786|INF|=============
2024-09-05T22:05:28.961|INF|==> Enabled delay of 50msec
2024-09-05T22:05:28.962|INF|==> 1 connection
╭────────────────────────────┬──────────────────╮
│ name                       │ master.delay.001 │
│ parallel_connections       │ 1                │
│ average_throughput_per_sec │ 27.1 MiB         │
│ server_node_peak_used_mem  │ 14.4 MiB         │
│ client_node_peak_used_mem  │ 23.6 MiB         │
╰────────────────────────────┴──────────────────╯
2024-09-05T22:10:35.622|INF|==> 2 connections …
```
> fix(jetsocat,dgw): add backpressure in JMUX proxy

- webapp/angular.json
Angular 18 build output now have `browser` and `server` sub path under build output directory. We don't want it, updated settings to remove this difference
reference: https://github.com/angular/angular-cli/issues/26304
> build(webapp): angular 18 changed build output path, update config to remove it

- .github/workflows/ci.yml
- .github/workflows/package.yml
- ci/tlk.ps1
- package/AgentWindowsManaged/Program.cs
UAC integration for PEDM is not needed currently; but the hook DLL is built and packaged. 
Removing the hook DLL from the build system allows us to build Devolutions Agent for ARM64 on Windows (it has a reference that is not ARM64 compatible).
> ci: Windows ARM builds for Devolutions Agent

- .github/workflows/ci.yml
Temporarily skip uploads of Devolutions Agent artifacts on Windows ARM64.
There are further considerations here:
- Some artifacts are architecture specific but not currently named accordingly (DevolutionSession, DevolutionsPedmShellExt)
- The same is true for the msix package (DevolutionsPedmShellExt.msix). It's actually not currently clear to me if this is architecture specific, or should contain binaries for all architectures
- Some artifacts are "universal" (.NET Framework) and shouldn't be uploaded twice (DevolutionsPedmDesktop)
We can address these issues in source, the main point for now is that we are building ARM64 projects and can catch build breaks and etc
> ci: skip upload of agent windows-arm64 artifacts

- jetsocat/Cargo.toml
- jetsocat/src/main.rs
- jetsocat/src/pipe.rs
This PR adds support for Windows named pipes and Unix sockets to Jetsocat.
> feat(jetsocat): Windows named pipes and Unix sockets

- devolutions-gateway/Cargo.toml
- jetsocat/Cargo.toml
https://github.com/Devolutions/devolutions-gateway/pull/1038 caused TLS 1.2 to be disabled. It was previously enabled by one of our dependencies, but things changed down there.
> fix(jetsocat): enable support for TLS 1.2

- crates/devolutions-gateway-generators/src/lib.rs
- devolutions-gateway/src/api/fwd.rs
- devolutions-gateway/src/generic_client.rs
- devolutions-gateway/src/jmux.rs
- devolutions-gateway/src/rdp_extension.rs
- devolutions-gateway/src/session.rs
To prevent future regressions, it is ensured that we properly set the policy everywhere by checking at compile-time that a value is set.
> fix(dgw): properly set the recording policy for RDP via web

- .github/workflows/ci.yml
Weird GitHub actions behavior where a job is skipped if a job it depends on _would have been skipped_ even if it’s not because of `always()`.
> ci: fix pull_request check workflow for PRs coming from forks

- Cargo.lock
- crates/mock-net/Cargo.toml
- crates/mock-net/src/lib.rs
- devolutions-gateway/Cargo.toml
- devolutions-gateway/src/api/webapp.rs
- devolutions-gateway/src/main.rs
- devolutions-gateway/src/plugin_manager/mod.rs
- devolutions-gateway/src/tls.rs
- rust-toolchain.toml
This PR removes the `lazy_static` dependency as per this [FIXME](https://github.com/Devolutions/devolutions-gateway/blob/193630fd7e1624aa1a73592f01205aa788529b60/devolutions-gateway/Cargo.toml#L44).
> refactor: replace `lazy_static` with `LazyLock`

- .github/workflows/build-tools.yml
- .github/workflows/ci.yml
The macOS 12 runner image will be removed by December 3rd, 2024
> ci: update macos-12 runners to macos-14

- devolutions-gateway/src/api/webapp.rs
- devolutions-gateway/src/token.rs
- devolutions-gateway/tests/dvls_compatibility.rs
DVLS generates this claim since its version 2022.1.9. This version is almost three years old, and already completely phased out, as such it’s more than reasonnable to stop supporting this kind of token.
> fix(dgw): disallow SCOPE tokens missing the jti claim

- devolutions-gateway/src/middleware/cors.rs
We don’t expose any header particularly sensitive from the Devolutions Gateway, and the future HTTP bridge will always require a token which is only issued on a per need basis. In fact, in such cases we actually want to allow virtually any header to be used for web-based integration of various web services (e.g.: VMware dashboard).
The restriction imposed by the token requirement is strong enough.
> fix(dgw): allow any header to be set in browser JavaScript HTTP requests

- crates/devolutions-pedm-hook/src/appinfo.rs
- crates/devolutions-pedm-hook/src/lib.rs
- crates/devolutions-pedm-shell-ext/src/lib_win.rs
- crates/devolutions-pedm/src/elevator/local_admin_elevator.rs
- crates/devolutions-pedm/src/elevator/virtual_account_elevator.rs
- crates/devolutions-pedm/src/error.rs
- crates/devolutions-pedm/src/utils.rs
- crates/win-api-wrappers/src/identity/account.rs
- crates/win-api-wrappers/src/identity/sid.rs
- crates/win-api-wrappers/src/process.rs
- crates/win-api-wrappers/src/rpc.rs
- crates/win-api-wrappers/src/security/acl.rs
- crates/win-api-wrappers/src/security/crypt.rs
- crates/win-api-wrappers/src/security/privilege.rs
- crates/win-api-wrappers/src/token.rs
- crates/win-api-wrappers/src/utils.rs
Issue: DGW-215
I changed the attribute from `allow` to `expect` for the correct suppressions that we expect. A warning will be fired if the warning ever ends up not fired anymore (e.g.: because the code changed, or a false-positive is fixed).
> refactor(pedm): audit clippy suppressions

- Cargo.lock
- crates/devolutions-gateway-generators/src/lib.rs
- devolutions-gateway/Cargo.toml
- devolutions-gateway/src/api/fwd.rs
- devolutions-gateway/src/extract.rs
- devolutions-gateway/src/main.rs
- devolutions-gateway/src/middleware/auth.rs
- devolutions-gateway/src/proxy.rs
- devolutions-gateway/src/target_addr.rs
- devolutions-gateway/src/tls.rs
- devolutions-gateway/src/token.rs
- devolutions-gateway/tests/token_security.proptest-regressions
- devolutions-gateway/tests/token_security.rs
- tools/tokengen/src/lib.rs
- tools/tokengen/src/main.rs
Currently behind the unstable flag.
Some details may be adjusted in the future.
For HTTP requests without upgrade, we do not account the operation as a session: it does not influence DVLS licensing quota, subscriber events, etc.
HTTP requests resulting into a WebSocket upgrade however will count as a fully-fledged session as usual.
Issue: DGW-217
In `gateway.json`:
```json
{
/* snip */
"__debug__": {
"enable_unstable": true
}
}
```
You can use `curl`:
```shell
curl -X GET \
"http://localhost:7171/jet/fwd/http/f4fae090-5c07-4350-8fd6-937e0f3a5b43" \
-H "Dgw-Request-Target: GET /todos/1" \
-H "Authorization: Bearer $(
tokengen \
sign --provisioner-key /path/to/provisioner.key \
bridge --target-host https://jsonplaceholder.typicode.com --jet-aid …
```
> feat(dgw): initial implementation for /jet/fwd/http endpoint

- devolutions-gateway/src/api/fwd.rs
- devolutions-gateway/src/api/jrec.rs
- devolutions-gateway/src/api/update.rs
- devolutions-gateway/src/openapi.rs
- devolutions-gateway/src/recording.rs
This patch adds a new endpoint not taking any parameter via the request path. Instead, a list of session IDs is provided in the request body.
Here is how to test with cURL and tokengen tool:
```shell
curl -X DELETE \
-H "Content-Type: application/json" \
--data '["d3a8ac78-49a4-4866-9ded-cf73a24f52c4"]' \
"http://localhost:7171/jet/jrec/delete?token=$( \
cargo run --manifest-path ./tools/tokengen/Cargo.toml \
sign --provisioner-key ./config/provisioner.priv.key scope '*' \
)"
```
Issue: DGW-219
> feat(dgw): /jet/jrec/delete endpoint for mass deletion

- Cargo.lock
- devolutions-gateway/Cargo.toml
- devolutions-gateway/src/api/heartbeat.rs
On Windows, the std::fs::canonicalize function returns Windows NT UNC paths, but our code detecting the mount point does not understand that.
We use dunce to handle that for us instead.
Issue: DGW-218
> fix(dgw): better custom recording paths handling in heartbeat endpoint

- webapp/src/client/app/modules/login/login.component.ts
> fix(webapp): the initial 401 error is shown when it should not

- jetsocat/src/main.rs
This is typically not required because we only enable the ring backend, which is then automatically installed by rustls when `ClientConfig::builder` is called later down the road. However, it may be the case that during development the aws-lc-rs feature of rustls is enabled (especially when building the whole workspace at once), causing rustls to crash the process requesting to install a default crypto provider.
To smoothen the developer experience, we attempt to install the ring crypto provider just before executing the command action. Our CI is already ensuring that we are not shipping both crypto backends by mistake.
> fix(jetsocat): preemptively install crypto provider on start

- webapp/package-lock.json
- webapp/package.json
- webapp/src/client/app/modules/web-client/ard/web-client-ard.component.html
- webapp/src/client/app/modules/web-client/ard/web-client-ard.component.ts
- webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.html
- webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.ts
- webapp/src/client/app/modules/web-client/vnc/web-client-vnc.component.html
- webapp/src/client/app/modules/web-client/vnc/web-client-vnc.component.ts
- webapp/src/client/app/shared/components/session-toolbar/session-toolbar.component.html
- webapp/src/client/app/shared/components/session-toolbar/session-toolbar.component.scss
Issue: DGW-230
Resolved Style Loading Delay in Session Component by Leveraging Existing Toolbar Component
Addressed an issue where .scss styles were not loading immediately for the ARD session component when it was loaded dynamically. 
**Utilized Existing Session Toolbar Component:** 
I used the session toolbar component, which was already implemented for the terminal based components (SSH & Telnet). I also updated all the other windows based components (RDP & VNC) as they all were at risk of the UI missing it's styles during a loading delay. 
**Reasoning:**
The toolbar component independently manages its styles, avoiding any delay caused by asynchronous tasks in the parent session component. Leveraging this component for style loading eliminates the need for further adjustments to …
> fix(webapp): session toolbar loading issues

- webapp/src/client/app/modules/web-client/ard/web-client-ard.component.ts
- webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.ts
- webapp/src/client/app/modules/web-client/ssh/web-client-ssh.component.ts
- webapp/src/client/app/modules/web-client/telnet/web-client-telnet.component.ts
- webapp/src/client/app/modules/web-client/vnc/web-client-vnc.component.ts
- webapp/src/client/app/shared/bases/base-web-client.component.ts
- webapp/src/client/app/shared/components/dynamic-tab/dynamic-tab.component.ts
- webapp/src/client/app/shared/services/component-listener.service.ts
- webapp/src/client/app/shared/services/web-session.service.ts
Issue: DGW-231
Resolved an issue where the menu list of web session connection status for SSH/Telnet was briefly displayed as "connecting" even though the session was terminated.
**Improvements**:
- Added ComponentListenerService to manage SSH and Telnet listeners, ensuring only one listener per session type.
- Introduced the WebComponentReady interface for seamless listener integration via ComponentListenerService in dynamically loaded components.
- Refactored session status initialization and event handling across all session types for more reliable session tracking.
> fix(webapp): active session connection status in menu

- devolutions-agent/Cargo.toml
- devolutions-agent/src/main.rs
- devolutions-agent/src/updater/detect.rs
- devolutions-agent/src/updater/error.rs
- devolutions-agent/src/updater/io.rs
- devolutions-agent/src/updater/mod.rs
- devolutions-agent/src/updater/package.rs
- devolutions-agent/src/updater/productinfo/db.rs
- devolutions-agent/src/updater/security.rs
- devolutions-agent/src/updater/uuid.rs
This PR adds logic to allow arbitrary version upgrades for the devolutions gateway updater (previously we were only able to install the latest stable version) and also allows us to downgrade the product version.
However, currently, our MSI Installer [forbids ](https://github.com/Devolutions/devolutions-gateway/blob/fix/devolutions-updater-improvements/package/WindowsManaged/Program.cs#L209-L211)to perform the downgrade. MSI-related changes will be pushed in follow-up PR, as more in-depth manual testing is required for MSI. 
Additionally, multiple clippy fixes were performed in `updater` Agent module
JIRA Ticket: https://devolutions.atlassian.net/browse/DGW-233 (WIP)
> refactor(agent): updater improvements

- jetsocat/Cargo.toml
- jetsocat/src/doctor/help.rs
- jetsocat/src/doctor/mod.rs
- jetsocat/src/doctor/native_tls.rs
- jetsocat/src/doctor/rustls.rs
- jetsocat/src/doctor/schannel.rs
Make jetsocat doctor return one link per certificate in addition to the chain link.
Issue: DGW-235
> fix(jetsocat): (also) return one link per certificate

- package/AgentWindowsManaged/Actions/CustomActions.cs
- package/AgentWindowsManaged/Helpers/AppSearch.cs
- package/AgentWindowsManaged/Program.cs
- package/AgentWindowsManaged/Resources/DevolutionsAgent_en-us.wxl
- package/AgentWindowsManaged/Resources/DevolutionsAgent_fr-fr.wxl
- package/AgentWindowsManaged/Resources/Includes.cs
- package/AgentWindowsManaged/Resources/Strings.g.cs
- package/AgentWindowsManaged/Resources/Strings_en-US.json
- package/AgentWindowsManaged/Resources/Strings_fr-FR.json
Preserve installed features when upgrading Devolutions Agent.
Additionally, make .NET 4.8 a hard requirement.
> fix(installer): preserve Agent features across upgrades

- .github/workflows/release.yml
This PR excludes unwanted DLL files from the release assets.
The output of the "Create GitHub release" step of the call-release-workflow job confirms that the DLLs are removed.
[Previous workflow run with DLLs](https://github.com/Devolutions/devolutions-gateway/actions/runs/12123470160/job/33800868911)
[Workflow run for this PR](https://github.com/Devolutions/devolutions-gateway/actions/runs/12361298709/job/34519437866)
> ci: exclude DLLs from release assets

- .github/workflows/ci.yml
- Cargo.lock
- crates/devolutions-pedm/src/elevator/local_admin_elevator.rs
- crates/devolutions-pedm/src/elevator/mod.rs
- crates/devolutions-pedm/src/log.rs
- crates/devolutions-pedm/src/utils.rs
- crates/win-api-wrappers/Cargo.toml
- crates/win-api-wrappers/src/dst.rs
- crates/win-api-wrappers/src/lib.rs
- crates/win-api-wrappers/src/process.rs
- crates/win-api-wrappers/src/raw_buffer.rs
- crates/win-api-wrappers/src/security/privilege.rs
- crates/win-api-wrappers/src/str.rs
- crates/win-api-wrappers/src/token.rs
- crates/win-api-wrappers/src/user.rs
- crates/win-api-wrappers/src/utils.rs
- crates/win-api-wrappers/src/wts.rs
Audit and refactor the privileges module to remove code found to be causing undefined behaviors.
The token module was also partially rewritten accordingly.
To help ensuring the new code is correct and stays that way, tests were added, and the CI was updated to run them with the LLVM memory sanitizers and miri (for all the code that is not interfacing with Windows API directly)
Notable abstractions added:
- Safer wide strings (str module): Re-export string types from the widestring crate, and provide extension traits to integrate with the windows-strings crate.
- RawBuffer (raw_buffer module): A convenient RAII wrapper around the Rust std global allocator.
- Win32Dst (dst module): Generic wrapper for Win32-style dynamically sized types.
Issue: DGW-222
> refactor(pedm): audit and refactor privileges module

- .github/workflows/ci.yml
- .github/workflows/package.yml
- .github/workflows/release.yml
- ci/PSModuleHelpers.ps1
- ci/tlk.ps1
- Split Devolutions Gateway PowerShell module into its own build step
- Produce nupkg for PowerShell module only in the packaging workflow
- Properly code sign PowerShell module contents and reuse them in MSI
- Import PSModuleHelpers.ps1 reusable helpers, move out from tlk.ps1
- Fix "Devolutionsgateway" casing to "DevolutionsGateway" in release.yml
> split gateway powershell module build + code sign

- config_schema.json
Make it easier for manually editing the config file, it can be referenced directly with GitHub URL and users will receives update when we make changes in this file.
> docs: add json scheme for gateway.json

- ci/tlk.ps1
The control template expects a variable named `packager` but `package` was passed.
> build(dgw): correct typo causing missing packager

- ci/tlk.ps1
- devolutions-gateway/src/config.rs
- package/Linux/gateway/template/rules
This moves _libxmf.so_ from `/usr/share/devolutions-gateway` to
`/usr/lib/devolutions-gateway`.
According to the [FHS](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s11.html), `/usr/share` is for architecture-independent data files.
> build(dgw): move libxmf.so to /usr/lib

- .github/workflows/ci.yml
- .github/workflows/package.yml
- Cargo.toml
- ci/tlk.ps1
- package/AgentLinux/agent/template/control
- package/AgentLinux/agent/template/rules
- package/Linux/gateway/template/control
- package/Linux/gateway/template/rules
- package/WindowsManaged/Program.cs
This commit adds RPM packages for Gateway and Agent to the release assets.
`tlk.ps1 -TlkVerb package -Platform linux` now generates both a deb and an rpm for the specified product.
The rpm is generated with fpm, a Linux packaging tool.
In CI, no cache is used for the fpm dependency since the cache would not persist across release jobs.
The RPM includes all the assets of the corresponding Debian package, including the changelog, copyright, maintainer scripts, and webapp/libxmf.so for Gateway.
The changelog is copied directly from Debian. A separate PR will be made to convert it to an RPM-friendly changelog format.
Tested with RHEL 9 (glibc 2.34).
> build: add RPM for gateway and agent

- crates/devolutions-agent-shared/src/lib.rs
- crates/win-api-wrappers/Cargo.toml
- crates/win-api-wrappers/src/lib.rs
- crates/win-api-wrappers/src/service.rs
- devolutions-agent/src/session_manager.rs
- devolutions-agent/src/updater/error.rs
- devolutions-agent/src/updater/mod.rs
- devolutions-agent/src/updater/package.rs
- devolutions-agent/src/updater/product_actions.rs
- devolutions-gateway/src/service.rs
This PR adds the following logic to the updater:
* Gateway service startup mode when correctly performing MSI install
* Start service if it was in "Manual" startup mode before installation, but in "Running" state, to avoid unintuitive behavior
> fix(agent): add logic to start Gateway service after update

- webapp/player-project/src/ws-proxy.ts
Fix the problem when Websocket send is called, we have an illegal invocation exception. The Websocket send method needs to be tied to the Websocket instance instead of the proxy, that is, the `this` keywords need to be bind to the correct object. This problem was introduced in the previous effort to intercept the `close` method for Websocket
> fix(dgw): fix illegal invocation for send method on streaming player websocket proxy

- webapp/player-project/src/streamers/webm.ts
> fix(dgw): remove success notification from player

- devolutions-gateway/src/generic_client.rs
- devolutions-gateway/src/listener.rs
- Enhance the "Peer failure" log to include the peer address and the listener kind (in fact, always TCP).
- Instead of an ERROR-level trace, log an INFO-level trace when the wrong protocol is used on the TCP listener.
> fix(dgw): improve log quality

- crates/video-streamer/src/streamer/mod.rs
Trying to make the `websocket_compact ` function return a result with a new trait.
I tried to make a Generic type for the `WithExplict` but faild as the combination for With and Map trait generic and bounds is beyond my comprehension. I hope @CBenoit  could make a better type than this... 
feel free to edit it, and let me know your thoughts, thanks!
> fix(dgw): send close code 1005 when video streaming ends

- crates/video-streamer/src/streamer/iter.rs
- crates/video-streamer/src/streamer/mod.rs
- crates/video-streamer/src/streamer/tag_writers.rs
> fix(dgw): fix streamer failure when frame rate is too low

- ci/tlk.ps1
This removes unused dependencies.
libc6 on Debian is glibc on RPM-based systems.
libc6 version is bumped to 2.31 as that is the version provided by the CI runner generating the build.
libgcc-s1 depedency is removed as it is a dependency of libc6.
```
> ldd devolutions-gateway
linux-vdso.so.1 (0x000077b2330a9000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x000077b22f5b1000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x000077b22f4c4000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x000077b22f200000)
/lib64/ld-linux-x86-64.so.2 (0x000077b2330ab000)
```
The ldd output for Agent is identical.
> build: remove unused Linux deps

- .github/workflows/ci.yml
- .github/workflows/package.yml
- ci/tlk.ps1
- package/AgentWindowsManaged/Program.cs
Build the PEDM desktop application independently - it's a .NET application and architecture "neutral". The artifacts are uploaded in CI, then extracted and signed before packaging.
Fix some minor issues that cropped up while debugging the workflows.
> ci: build the PEDM desktop app so it can be signed

- Cargo.lock
- crates/test-utils/src/lib.rs
- crates/transport/Cargo.toml
- crates/transport/src/lib.rs
- crates/transport/src/pinnable.rs
- crates/transport/src/shared.rs
- crates/transport/src/ws.rs
- crates/video-streamer/examples/stream/local_websocket.rs
- devolutions-gateway/src/api/fwd.rs
- devolutions-gateway/src/api/jmux.rs
- devolutions-gateway/src/api/jrec.rs
- devolutions-gateway/src/api/rdp.rs
- devolutions-gateway/src/config.rs
- devolutions-gateway/src/streaming.rs
- devolutions-gateway/src/ws.rs
- jetsocat/src/doctor/mod.rs
- jetsocat/src/pipe.rs
- jetsocat/src/utils.rs
Our WebSockets are already responding Pong messages to Ping messages, but they were never sending Ping messages.
> fix(dgw,jetsocat): implement WebSocket keep-alive logic

- tools/bump-version.ps1
`tools/bump-version.ps1` will now update the packaging changelogs as well. The only thing it does is adding a new section for the new version, stating that no change was made to the package itself. If something was changed, the files should be modified manually afterwards.
> chore(tools): update packaging changelogs in bump-version.ps1

- devolutions-agent/src/updater/mod.rs
- devolutions-agent/src/updater/product_actions.rs
Fix the updater corner case when the user is trying to downgrade to the latest specified version in `productinfo.htm` while a newer unreleased version is installed locally.
> fix(agent): fix downgrade logic for unreleased Devolutions Gateway

- package/AgentWindowsManaged/Actions/AgentActions.cs
- package/AgentWindowsManaged/Actions/CustomActions.cs
- package/AgentWindowsManaged/Program.cs
- package/AgentWindowsManaged/Resources/Includes.cs
Register the "Run Elevated" shell extension as a traditional context menu extension, via the registry. This will appear in the second level context menu (after clicking "Show more options") on a modern Win11 system.
For now, registration of the `IExplorerCommand` "modern" shell extension (to appear in the top-level context menu on a Win11 system) is removed. This is unstable: it's tricky to register the extension for multiple users, and it causes significant problems with upgrades or uninstall/reinstall, due to the DLL remaining locked by the shell. A future pull request will reinstate the .msix registration with a different approach.
Remove some unused code that was carried out needlessly from Devolutions Gateway.
> feat(installer): register PEDM shell extension instead of msix

- package/AgentWindowsManaged/Actions/AgentActions.cs
- package/AgentWindowsManaged/Actions/CustomActions.cs
- package/AgentWindowsManaged/Program.cs
- package/AgentWindowsManaged/Properties/AgentProperties.g.cs
- package/AgentWindowsManaged/Properties/AgentProperties.g.tt
This PR disables the Windows Restart Manager for the Agent MSI.
The restart manager is intended to reduce reboots due to locked files; and will attempt to shutdown and relaunch executables that are using files the installer will delete and recreate. It prompts the user interactively in this case and offers them the choice to attempt a shutdown/restart of the relevant applications (requires that the applications integrate with the restart manager) or to allow a reboot.
Both the Agent tray application and the session executable trigger the restart manager, but in both cases we will manage things ourselves here. We don't want to prompt the user.
- Disable the restart manager. This makes Windows Installer fall back to the old-style "files in use" dialog, which, importantly, won't trigger for …
> feat(installer): disable restart manager in Agent MSI

- package/AgentWindowsManaged/Actions/CustomActions.cs
- package/AgentWindowsManaged/Actions/WinAPI.cs
- package/AgentWindowsManaged/Program.cs
Upgrading or uninstalling the PEDM shell extension is still problematic: in my test, the restart manager killed Windows Explorer and then failed to restart it properly. This caused a broken state on my machine that was difficult to recover.
Instead, we copy the shell extension DLL before registering it. On uninstall, the dll is moved to a temporary location and then marked for removal on reboot. This is the same approach taken by Notepad++ to avoid this issue.
> fix(pedm): copy the shell extension before registration

- devolutions-session/src/main.rs
The feature is still experimental, but it’s not necessary to guard the virtual channel behind the unstable flag when the "DevolutionsSession" feature itself is clearly marked as experimental.
> fix(agent): stabilize RDP virtual channel server

- devolutions-gateway/src/recording.rs
Fix the issue where recording ended but the  streaming task keeps alive, this will result in streaming client not received correct update of the streaming state.
> fix(dgw): notify all instead of notify one when recording ends

- package/Linux/gateway/debian/postinst
- package/Linux/gateway/debian/postrm
- package/Linux/gateway/debian/prerm
~~This PR is somewhat related to #1223 as currently you cannot uninstall `devolutions-gateway` properly (on Ubuntu) without modifying `/var/lib/dpkg/info/devolutions-gateway.prerm` because of the service name change making the `systemctl stop` command.~~ Post-publication edit: #1223 is a bug, hence the modifications related to this are removed.
~~And although not utilized by the service file, this PR also adds the functionality to create `/etc/defaults/devolutions-gateway` file.~~ Post-publication edit: References to the defaults file are also removed.
Lastly, the PR adds an `rm -rf /etc/devolutions-gateway` command if `postrm` is called with `purge` flag.
Post-publication edit: PR also changes the systemd reload command order and also enables (and starts) `devolutions-gateway` service to …
> fix(deb): improve deb package

- package/AgentWindowsManaged/Actions/AgentActions.cs
- package/AgentWindowsManaged/Actions/CustomActions.cs
The PEDM/Session feature toggle was manipulating `agent.json` _after_ `InstallFiles`.
The action that does an initialization of the `agent.json` was not actually added to the custom actions, and in any case it was sequenced _before_ `StartServices` (which is _after_ `InstallFiles`).
So: the PEDM/Session feature installation would create a new `agent.json` if it didn't already exist, and then the initialization custom action and service itself would not bother to initialize the `agent.json`. The result was that the "updater" configuration key would be missing if the user selected additional features.
This PR:
- Fixes the sequencing for feature installation and config file generation
- Disables the Agent/Session features when they are uninstalled
- Prevents the PEDM %programdata% …
> fix(installer): prevent invalid configuration due to installer sequencing

- package/AgentWindowsManaged/Actions/AgentActions.cs
- package/AgentWindowsManaged/Actions/CustomActions.cs
- package/AgentWindowsManaged/Dialogs/FeaturesDialog.Designer.cs
- package/AgentWindowsManaged/Dialogs/FeaturesDialog.cs
- package/AgentWindowsManaged/Dialogs/ProgressDialog.cs
- package/AgentWindowsManaged/Helpers/StockIcon.cs
- package/AgentWindowsManaged/Program.cs
- package/AgentWindowsManaged/Resources/DevolutionsAgent_en-us.wxl
- package/AgentWindowsManaged/Resources/DevolutionsAgent_fr-fr.wxl
- package/AgentWindowsManaged/Resources/Features.cs
- package/AgentWindowsManaged/Resources/Strings.g.cs
- package/AgentWindowsManaged/Resources/Strings_en-US.json
Make the Gateway updater a selectable feature in the Agent MSI installer.
New installs will select the feature by default; upgrades will follow what is already installed. Note that since this a "new feature", upgrades from prior versions will _not_ automatically select the updater feature. I choose not to code around this because we don't have a public release yet.
I reworked the `StockIcon` helper but ended up not using the changes. However, I keep the improvements that may be useful in future.
> feat(installer): make agent updater a selectable feature

- Cargo.lock
- crates/devolutions-pedm-shared/Cargo.toml
- crates/devolutions-pedm-shared/src/policy.rs
- crates/devolutions-pedm/Cargo.toml
- crates/devolutions-pedm/src/api/launch.rs
I've noticed that nearly every .NET application I elevate with PEDM, crashes (sometimes immediately, sometimes after running for a while).
The crashes seem centred around paths (for example, IISCrypto crashes on startup complaining of a invalid path; RDM crashes after some time when a third party component tries to interact with the shell by passing a path to the application, etc)
When elevating an executable, PEDM first expands environment variables in the executable path and then calls `fs::canonicalize` which has a side-effect of prefixing the canonical path with the Windows file namespace (`\\?\`).
It turns out, that not a single .NET application that I tested works when launched from a path with a Windows file namespace prefix.
This PR uses `dunce` in the same was as Devolutions …
> fix(pedm): don't use Windows file namespace in paths

- .github/workflows/ci.yml
- ci/download-cadeau.ps1
Properly target ubuntu-18.04, including for the cadeau library which was just released with ubuntu-18.04 targeting as well. By targeting ubuntu-18.04, we are forward-compatible with ubuntu 20.04, 22.04, 24.04 but we are also finally compatible with RHEL8, which uses a version of glibc older than ubuntu 20.04.
> build: target Ubuntu 18.04

- package/AgentWindowsManaged/Actions/AgentActions.cs
An unexpected error unregistering the PEDM shell extension can cause an uninstall to fail; this leads to a bad posture on the user machine.
cc: @allan2
> fix(installer): don't fail an uninstall if the shell extension can't be unregistered

- ci/Build/Build.psm1
- ci/README.md
- ci/package-gateway-deb.ps1
- ci/package-gateway-rpm.ps1
- package/AgentLinux/agent/template/control
- package/Linux/gateway/template/control
- package/Linux/gateway/template/rules
- package/Linux/template/copyright
- separation of Debian and RPM generation
- removes unused tokens in templates
- fixes a warning where debian/rules was missing the execution bit
- changes the intermediate build directories to 'gateway-deb` and `gateway-rpm`
- uses parameters instead of environment variables
- local use of `Set-Location`
- removes single-use string variables
- custom copyright file for RPM instead of the Debian-generated copyright
> build: separate Debian and RPM packaging

- Cargo.lock
- crates/job-queue-libsql/Cargo.toml
- devolutions-agent/Cargo.toml
Limit libsql features to what we really need (just local database support). This significantly reduces the dependencies brought into the main project through libsql, including rustls which we don't need in libsql as we're not using the server mode.
> build(dgw): don't use libsql default features

- ci/README.md
- ci/build.ps1
- ci/package-agent-windows.ps1
- dotnet/DesktopAgent/build.ps1
- package/AgentWindowsManaged/.gitignore
This builds a working Agent MSI.
- fixes MSI internal file names that were breaking install
- PedmShellExt.dll must be named exactly that
- fixes inclusion of DesktopAgent
- previously was only inlcuding source files
- adds MSBuild logs (excluded from version control)
- `OutputDir` changed to `Outfile` to allow custom output name
- for example, one can now build an MSI with a timestamped filename
> build: fix Agent MSI

- .github/workflows/ci.yml
`apt` is failing to install packages for arm64; however as per @awakecoding we actually don't need these packages anymore since everything we want is inside our custom sysroot.
> ci: fix configuration of arm64 linux runner

- package/WindowsManaged/Actions/CustomActions.cs
- package/WindowsManaged/Resources/Includes.cs
We've had sporadic issues where users cannot update the revocation list due to a permissions error on the .jrl file (access denied deleting the original file).
While investigating logs, I've seen similar errors where the service is not able to delete old log files while performing a log rotation.
My theory is:
- Gateway was installed and created this file(s) at or before version 2024.1.5
- In subsequent versions, we switched the service account to `NetworkService` and updated the DACL applied to the top-level %programdata%\Devolutions\Gateway directory
- However, files created previously did not retroactively inherit `NetworkService`'s new ACL
- This doesn't matter for most files where `Users` has read and execute permission
- Files that need `Modify` permission won't have it (for …
> fix(installer): ensure NetworkService has proper file permissions

- crates/transport/src/ws.rs
- devolutions-gateway/src/api/fwd.rs
- devolutions-gateway/src/api/jmux.rs
- devolutions-gateway/src/api/jrec.rs
- devolutions-gateway/src/api/rdp.rs
- devolutions-gateway/src/streaming.rs
- devolutions-gateway/src/ws.rs
- jetsocat/src/utils.rs
Fix Gateway WebSocket connection hanging when server has already closed the tcp connection.
Added new structure to have Gateway send proper close frame to indicates it's close state, and can be further extended with more senmantic close frames.
> fix(dgw): Make gateway to send proper close frame when WebSocket connection closes.

- devolutions-gateway/src/api/heartbeat.rs
It’s easier to diagnostic why canonicalization failed now.
Example:
> DEBUG listener{port=7171}:http{client=[::1]:60724}:request{method=GETpath=/jet /heartbeat}: devolutions_gateway::api::heartbeat: Failed to canonicalize recording path error=The system cannot find the file specified. (os error 2) recording_path=.\dvls\recordings
> fix(dgw): improve debug logs for recording path canonicalization

- package/AgentWindowsManaged/Actions/CustomActions.cs
The top-level file extension keys may not all exist (in the case of QA, `HKEY_CLASSES_ROOT\\.ps1` was not present). Although we check for an empty default _value_, we don't check for the presence of the top-level key which could cause a null-reference exception and force the installer to roll back.
> fix(installer): resolve potential null reference installing PEDM shell extension

- devolutions-gateway/src/tls.rs
We used the wrong key for sorting the certificates. It should have been "valid_not_after" instead of "valid_not_before".
Issue: DGW-261
> fix(dgw): properly order system certificates

- .github/workflows/ci.yml
- crates/devolutions-pedm-shared/devolutions-pedm-client-http/src/apis/default_api.rs
- crates/devolutions-pedm-shared/devolutions-pedm-client-http/src/apis/mod.rs
- crates/devolutions-pedm-shared/devolutions-pedm-client-http/src/apis/request.rs
- crates/terminal-streamer/src/lib.rs
- crates/terminal-streamer/src/trp_decoder.rs
- crates/video-streamer/examples/read_from.rs
- crates/video-streamer/examples/stream/local_websocket.rs
- crates/video-streamer/examples/stream/main.rs
- crates/video-streamer/src/streamer/iter.rs
- crates/video-streamer/src/streamer/mod.rs
- crates/video-streamer/src/streamer/protocol.rs
- crates/video-streamer/src/streamer/reopenable_file.rs
- crates/video-streamer/src/streamer/signal_writer.rs
- crates/video-streamer/src/streamer/tag_writers.rs
- devolutions-gateway/src/config.rs
- devolutions-gateway/src/ws.rs
I encountered a warning in the "Check formatting" step of the preflight job.
```
Warning: can't set `imports_granularity = Module`, unstable features are only available in nightly channel.
```
Switching to nightly resolves this issue.
> ci: switch to nightly for cargo fmt

- crates/devolutions-pedm/src/api/mod.rs
- crates/devolutions-pedm/src/api/state.rs
- crates/devolutions-pedm/src/config.rs
- crates/devolutions-pedm/src/lib.rs
- `serve` now takes a `Config` struct rather than a path
- pipe name is now part of `Config` rather than a direct argument
- `Config` struct is now exported as `devolutions_pedm::Config`
- `serve` is now exported as `devolutions_pedm::serve`
> refactor(pedm): modify `serve` arguments

- devolutions-gateway/src/api/net.rs
Up on the request for Paul.
Example output:
```
{
"name": "Ethernet",
"addresses": [
{
"V6": {
"ip": "fe80::1a61:8798:d284:1e54"
}
},
{
"V4": {
"ip": "169.254.160.203",
"netmask": "255.255.0.0"
}
}
],
"mac_addr": "AC:1A:3D:6F:56:6C",
"index": 17
},
```
> fix(dgw): rename param addrs to addresses

- crates/devolutions-pedm/src/config.rs
- crates/devolutions-pedm/src/lib.rs
The wrong function was being called when initializing the config. No default config was actually being written to disk.
This commit fixes it.
> fix(pedm): write default config when not present

- devolutions-gateway/src/api/net.rs
Stable enough now, it's just one function call in the `interfaces::get_network_interfaces`
> feat(dgw): stabilize /jet/net/config

- crates/win-api-wrappers/src/security/crypt.rs
The `CryptCATAdminCalcHashFromFileHandle2` [documentation](https://learn.microsoft.com/en-us/windows/win32/api/mscat/nf-mscat-cryptcatadmincalchashfromfilehandle2) says:
>Return value
>
>[...]
>
>ERROR_INSUFFICIENT_BUFFER | The buffer pointed to by the pbHash parameter was not NULL but was not large enough to be written. The correct size of the required buffer is contained in the value pointed to by the pcbHash parameter.
Ergo, the function will **not** return an error when passing a `NULL` value for `pbHash`, it will succeed. This is confusing because other similar Win32 APIs do not work the same way.
> fix(pedm): CryptCATAdminCalcHashFromFileHandle2 does not return error with NULL buffer

- crates/devolutions-pedm/src/log.rs
The `unimplemented!` macro causes us to panic here, which means elevation is not possible. This is counter productive to a minimum viable implementation (I do not know the current state of elevation logging).
> fix(pedm): don't panic on missing log_elevation function

- crates/devolutions-pedm-shell-ext/src/lib_win.rs
- crates/win-api-wrappers/Cargo.toml
- crates/win-api-wrappers/src/fs.rs
- crates/win-api-wrappers/src/security/crypt.rs
- package/AgentWindowsManaged/ExplorerCommand.ps1
By inspecting elevated .msi files launched from Explorer, we see that Explorer invokes %systemroot%\system32\msiexec, with the command line `"%systemroot%\system32\msiexec" /i "{path-to-msi}"`.
We achieve the same in the PEDM module by using the same command if the file extension is .msi. The .msi extension is already being trapped by the shell extension, but previously we would call `CreateProcess` on the .msi causing "file is not a valid Win32 executable".
Additionally, I polished and added @awakecoding's original "ExplorerCommand.ps1" script. This is useful for debugging, where the installed shell extension can't be overwritten as it's in use by Explorer. Install Devolutions Agent with the PEDM feature; then use the PowerShell to unregistered the shell extension. Swap in your …
> feat(pedm): explicitly support elevating .msi files

- webapp/src/client/app/modules/web-client/ard/web-client-ard.component.html
- webapp/src/client/app/modules/web-client/ard/web-client-ard.component.ts
- webapp/src/client/app/modules/web-client/form/form-controls/enable-display-configuration-control/enable-display-configuration-control.component.ts
- webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.html
- webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.ts
- webapp/src/client/app/modules/web-client/vnc/web-client-vnc.component.html
- webapp/src/client/app/modules/web-client/vnc/web-client-vnc.component.ts
- webapp/src/client/app/shared/components/session-toolbar/session-toolbar.component.html
- webapp/src/client/app/shared/components/session-toolbar/session-toolbar.component.scss
- webapp/src/client/app/shared/components/session-toolbar/session-toolbar.component.ts
Fix for https://github.com/Devolutions/devolutions-gateway/pull/1329#discussion_r2087157731
> refactor(webapp): add 'on' and 'off' states for `Toggle Cursor Button`

- webapp/src/client/app/modules/web-client/form/form-controls/enable-cursor-control/enable-cursor-control.component.html
In the standalone interface, in the VNC extra settings menu.
> fix(dgw): update tooltip of enable cursor checkbox

- Cargo.toml
- crates/devolutions-pedm-shell-ext/Cargo.toml
- devolutions-agent/Cargo.toml
- devolutions-gateway/Cargo.toml
- devolutions-session/Cargo.toml
- jetsocat/Cargo.toml
This sets the version in one place.
This will make endpoints that return the version, such as `/about` in PEDM, return a consistent version based on `CARGO_PKG_VERSION`.
A PR will follow to bump the `devolutions-pedm` version (currently 0.0.0).
> chore: use workspace version

- crates/devolutions-pedm/src/api/about.rs
The comments for [AboutData](https://github.com/Devolutions/devolutions-gateway/blob/668e0b43edd5ee2ce4cbf4692920c09d732eeb85/crates/devolutions-pedm/src/model.rs#L7) say
> This can be `None` if `/about` is the first request made.
Which is true and correct; but is causing a crash in the .NET OpenAPI client if /about is the first request made.
For whatever reason, the .NET OpenAPI [generator](https://github.com/Devolutions/devolutions-gateway/blob/668e0b43edd5ee2ce4cbf4692920c09d732eeb85/crates/devolutions-pedm/openapi/dotnet-client/src/Devolutions.Pedm.Client/Model/AboutData.cs#L74) is not creating a nullable property.
This may be related to the issues I had in #1164, but I don't have time to dig into it now. Since this is non-critical / non-user facing; I just force a value here for the …
> fix(pedm): ensure get_last_request_time has a value

- crates/win-api-wrappers/src/identity/account.rs
- crates/win-api-wrappers/src/utils.rs
This fixes a few but not all Clippy lints.
> chore: clippy fixes for win-api-wrappers

- webapp/package-lock.json
- webapp/package.json
- webapp/src/client/app/modules/web-client/ard/web-client-ard.component.ts
- webapp/src/client/app/modules/web-client/form/form-components/ard/ard-form.component.html
- webapp/src/client/app/modules/web-client/form/form-components/vnc/vnc-form.component.html
- webapp/src/client/app/modules/web-client/form/form-controls/wheel-speed-factor-control/wheel-speed-factor-control.component.html
- webapp/src/client/app/modules/web-client/form/form-controls/wheel-speed-factor-control/wheel-speed-factor-control.component.scss
- webapp/src/client/app/modules/web-client/form/form-controls/wheel-speed-factor-control/wheel-speed-factor-control.component.ts
- webapp/src/client/app/modules/web-client/vnc/web-client-vnc.component.ts
- webapp/src/client/app/modules/web-client/web-client.module.ts
- webapp/src/client/app/shared/interfaces/connection-params.interfaces.ts
- webapp/src/client/app/shared/interfaces/forms.interfaces.ts
> feat(webapp): add `wheel_speed_factor` setting to a VNC and ARD connection forms

- Cargo.lock
- devolutions-gateway/Cargo.toml
- devolutions-gateway/src/api/fwd.rs
- devolutions-gateway/src/api/preflight.rs
- devolutions-gateway/src/api/rdp.rs
- devolutions-gateway/src/config.rs
- devolutions-gateway/src/credential.rs
- devolutions-gateway/src/generic_client.rs
- devolutions-gateway/src/lib.rs
- devolutions-gateway/src/listener.rs
- devolutions-gateway/src/ngrok.rs
- devolutions-gateway/src/rd_clean_path.rs
- devolutions-gateway/src/rdp_pcb.rs
- devolutions-gateway/src/rdp_proxy.rs
- devolutions-gateway/src/tls.rs
- devolutions-gateway/src/token.rs
- devolutions-gateway/tests/preflight.rs
- docs/COOKBOOK.md
- Provide and associate the proxy-target credential mapping with the association token using a preflight API call.
- Connect using the fake (proxy) credentials to the Devolutions Gateway as usual, with a PCB containing the association token.
- Perform two-way forwarding between the client and the target until the TLS security upgrade.
- Separately perform the TLS upgrade for both the client and the server, effectively acting as a man-in-the-middle.
-  The client must trust the TLS certificate configured in the Devolutions Gateway.
- Separately perform CredSSP authentification as server with the client, and as client with the target.
- The fake, proxy credentials are used with the client.
- The real, target credentials are used with the target.
- Proceed with the usual two-way forwarding …
> feat(dgw): proxy-based credentials injection support for RDP

- devolutions-gateway/src/api/webapp.rs
- devolutions-gateway/src/generic_client.rs
- devolutions-gateway/src/token.rs
The favored approach when pushing credentials is now to use the preflight route.
> fix(dgw)!: drop the prx_usr, prx_pwd, dst_usr and dst_pwd claims

- webapp/package-lock.json
- webapp/package.json
- webapp/src/client/app/modules/web-client/ard/web-client-ard.component.ts
- webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.ts
- webapp/src/client/app/modules/web-client/vnc/web-client-vnc.component.ts
Update calls to `onSessionEvent` from _@devolutions/iron-remote-desktop_, as the interface changed after RxJS was removed from latter's dependencies.
> refactor(webapp): update calls to onSessionEvent

- .github/dependabot.yml
IronVNC also depends on a few IronRDP crates, so we may as well group them together.
cc @MathieuMorrissette
> ci(dependabot): group IronVNC bumps with IronRDP

- devolutions-gateway/src/api/net.rs
- devolutions-gateway/src/openapi.rs
cc @irvingoujAtDevolution 
The JSON output of the `/jet/net/config` route is changed to be more convenient in the consumer code.
Previous output example:
```json
[
{
"name": "vboxnet0",
"addresses": [
{
"V4": {
"ip": "192.168.56.1",
"broadcast": "192.168.56.255",
"netmask": "255.255.255.0"
}
},
{
"V6": {
"ip": "fe80::800:27ff:fe00:0",
"netmask": "ffff:ffff:ffff:ffff::"
}
}
],
"mac_addr": "0a:00:27:00:00:00",
"index": 4
}
]
```
New output example:
```json
{
"vboxnet0": [
{
"family": "IPv4",
"address": "192.168.56.1",
"broadcast": "192.168.56.255",
"netmask": "255.255.255.0",
"mac": "0a:00:27:00:00:00"
},
{
"family": "IPv6",
"address": "fe80::800:27ff:fe00:0",
"netmask": "ffff:ffff:ffff:ffff::",
"mac": "0a:00:27:00:00:00"
}
]
}
```
> fix(dgw)!: clean up /jet/net/config route

- crates/devolutions-pedm/src/api/policy.rs
- crates/devolutions-pedm/src/db/libsql.rs
- crates/devolutions-pedm/src/db/mod.rs
- crates/devolutions-pedm/src/db/pg.rs
If a user has never had a profile assigned, there will be no record of them in the `user` table.
However, if they try to select a profile, an error is returned. It's better to catch this scenario upfront and just return an empty profile selection and list.
> fix(pedm): don't error on profile selection if no assignments

- crates/devolutions-pedm/src/elevator/virtual_account_elevator.rs
- crates/win-api-wrappers/src/identity/account.rs
- crates/win-api-wrappers/src/token.rs
- crates/win-api-wrappers/src/token_groups.rs
Some users are experiencing an error with the virtual account elevator that I cannot reproduce, and we do not have the necessary contextual information. This PR adds additional context to the virtual account elevator code paths.
> fix(pedm): add additional context to virtual account code paths

- README.md
- devolutions-gateway/src/config.rs
- devolutions-gateway/src/tls.rs
- devolutions-gateway/tests/config.rs
This adds a `TlsVerifyStrict` option for controlling the new stricter verifications on TLS certificates.
When enabled (`true`), the client performs additional checks on the server certificate, including:
- Ensuring the presence of the **Subject Alternative Name (SAN)** extension.
- Verifying that the **Extended Key Usage (EKU)** extension includes `serverAuth`.
Certificates that do not meet these requirements are increasingly rejected by modern clients (e.g., Chrome, macOS). Therefore, we strongly recommend using certificates that comply with these standards.
The default configuration for fresh installs will include the `TlsVerifyStrict` key set to `true`.
Issue: DGW-293
> feat(dgw): new TlsVerifyStrict option

- README.md
- devolutions-gateway/src/config.rs
- devolutions-gateway/src/service.rs
- devolutions-gateway/src/tls.rs
Previously, strict TLS verification was performed even when the TlsVerifyStrict key was absent from the configuration file.
From now on, if this key is missing, it will default to "TlsVerifyStrict": false.
This change ensures that existing users who are currently using improper certificates will not be affected. At the same time, newly generated configuration files will continue to include "TlsVerifyStrict": true by default, encouraging using proper certificates from the start.
New users can still opt out of strict verification by explicitly setting the value to false or removing the key entirely if they are willing to accept potential compatibility issues with some clients, such as Chrome or macOS.
A warning will be logged if the option is disabled as it may hide latent issues. …
> fix(dgw): set default value of TlsVerifyStrict to false

- devolutions-agent/src/config.rs
- devolutions-gateway/src/config.rs
- devolutions-session/src/config.rs
Output the full path to the configuration file when initializing the configuration for both Devolutions Gateway and Devolutions Agent. This simplifies debugging and setup verification.
> feat(dgw,agent): display config file path during initialization

- .github/workflows/package.yml
- .github/workflows/release.yml
We decided to drop Windows container images a while back, but this was not reflected in the workflow.
> ci: drop leftover code for Windows containers

- .github/workflows/ci.yml
- .github/workflows/package.yml
- .github/workflows/release.yml
- Create a tarball archive instead of a zip archive for the PowerShell module.
-  It’s unclear to me why, but the PowerShell module we sign and re-archive in the package workflow is corrupted when we try to decompress it in the release workflow.
- This is something I could verify locally using the `7z` command.
- The `Publish-Module` cmdlet was also failing with a cryptic error:
> Write-Error: Cannot retrieve the dynamic parameters for the cmdlet. Loading repository store failed: Could not find a part of the path '/home/runner/.local/share/PSResourceGet/PSResourceRepository.xml'.
- I walked around that by switching to the newer `Publish-PSResource` cmdlet, which is a more modern rewrite of `Publish-Module`.
> ci: fix powershell publishing job

- webapp/package-lock.json
- webapp/package.json
- webapp/src/client/app/modules/login/login.component.ts
- webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.ts
- webapp/src/client/app/shared/components/tab-view/tab-view.component.ts
- webapp/src/client/app/shared/guards/auth.guard.ts
- webapp/src/client/app/shared/services/navigation.service.ts
This PR adds support for `config`, `autoconnect`, and `protocol` query parameters in the Devolutions Gateway Standalone.
Since it is an MVP, there are many things left to be done (I marked them with TODO). 
Here is a demo:  
https://github.com/user-attachments/assets/249ccde3-1973-424b-bd19-78b9d3a71045
> feat(webapp): implement MVP for self-contained session URLs

- crates/traffic-audit-libsql/src/lib.rs
- crates/traffic-audit-libsql/tests/integration.rs
- crates/traffic-audit/src/lib.rs
- devolutions-gateway/src/api/mod.rs
- devolutions-gateway/src/api/traffic.rs
- devolutions-gateway/src/extract.rs
- devolutions-gateway/src/token.rs
- devolutions-gateway/src/traffic_audit.rs
- devolutions-gateway/tests/traffic.rs
- docs/COOKBOOK.md
Add two new endpoints for external traffic audit integration:
- `POST /jet/traffic/claim` - Claim events with lease-based locking
- `POST /jet/traffic/ack` - Acknowledge processed events
Issue: DGW-271
> feat(dgw): implement traffic audit claim/ack HTTP endpoints

- webapp/src/client/app/shared/interfaces/forms.interfaces.ts
Follow up to https://github.com/Devolutions/devolutions-gateway/pull/1464.
> style(web): add a comment explaining why `enableExtendedClipboard` field can be uninitialized

- jetsocat/src/main.rs
Add automatic path expansion for np:// and np-listen:// schemes:
- Windows: simple names expand to "./pipe/<NAME>"
- Unix: simple names expand to "/tmp/<NAME>"
> feat(jetsocat): expand simple pipe names

- Cargo.toml
Size was already optimized in the past by enabling lto and stripping the debug symbols. Adding codegen-units = 1 brings the binary size further down.
- Jetsocat baseline: 7.3M
- Jetsocat after: 6.6M
- Devolutions Gateway baseline: 27M
- Devolutions Gateway after: 25M
> build(jetsocat,dgw): optimize binary size

- .github/workflows/release.yml
Unfortunately, this is stuff that does not run unless we cut a release, so it’s hard to get right… but I think now we should be good!
> ci(release): fix SBOM job

- jetsocat/src/main.rs
Improves the handling of optional command-line flags in jetsocat by replacing direct flag access with proper error handling: missing optional flags are handled gracefully while invalid flag values still produce clear error messages.
> fix(jetsocat): improve optional flag handling and error reporting

- devolutions-gateway/src/main.rs
- package/Linux/gateway/debian/service
- removes unnecessary clear lines (following typical convention in /usr/lib/systemd/system/foo.service)
- removes extra leading whitespace
> build(package): remove unnecessary lines

- devolutions-gateway/src/service.rs
This splits the warnings for absent and false.
> fix(dgw): split TlsVerifyStrict warning for absent and false
