src/http/controllers/jet.rs
src/http/controllers/mod.rs

Added Content-Type: application/json in response when we gather candidates

Added content-type in response

---

src/main.rs
tests/jet_client.rs

Fixed multiple tcp listener + fixed issue where jet doesn't run if no tcp listener is defined

Multiple tcp listener

---

Cargo.lock
Cargo.toml
src/http/controllers/jet.rs
src/http/http_server.rs
src/jet/association.rs
src/jet/candidate.rs
src/jet_client.rs
src/main.rs
src/transport/mod.rs
src/transport/tcp.rs
src/transport/ws.rs
src/utils/association.rs
src/websocket_client.rs

New endpoint /jet/association. It returns a json similar to that : 
[
{
"id": "68459df0-c5c9-47ad-9667-e4ab5f9e154e",
"version": 2,
"bytes_sent": 3268,
"bytes_recv": 155360
},
{
"id": "dea5d57f-1175-42e2-82f1-4d4a08dcb062",
"version": 2,
"bytes_sent": 720,
"bytes_recv": 1711
}
]

Get associations

---

README.md

Described how to enable required cipher suits on Windows 7/8 to make it work with Jet

Add Windows 7/8 troubleshooting section to the README

---

examples/client.rs

It is not perfect, but the example client is an easy way to test JET_V1 on any jet server. It can be used to know if a deployment has been done correctly.  Now, the jet server can return a different mask so the client has to support it to print the response correctly.

Support mask when we use the example client

---

Cargo.lock
Cargo.toml
src/rdp/sequence_future/post_mcs.rs
src/rdp/sequence_future/post_mcs/licensing.rs
tests/rdp.rs

Added licensing exchange to Jet. Now it works with Windows Terminal Server.
WIP until IronRDP is publshed and Cargo.toml is changed.

Add license exchange

---

Cargo.lock
Cargo.toml
examples/benchmark/src/jet_proto.rs
jet-proto/src/lib.rs
src/config.rs
src/main.rs
src/proxy.rs
src/rdp/sequence_future/nla.rs
src/transport/mod.rs
src/transport/ws.rs
src/websocket_client.rs

Just add a timeout on the finish forward future.

Fix transport futures edgecase causing ghost associations

---

CHANGELOG.adoc
Cargo.lock
Cargo.toml

Préparation de la prochaine version...

Version bump from 0.12.0 to 0.13.0

---

build.rs
jet-proto/src/test.rs
src/config.rs
src/main.rs
src/rdp/preconnection_pdu.rs
src/service.rs

Fixed clippy issues
Validated with:
```
cargo clippy --all-targets --all-features -- -D warnings
```

Fixed clippy issues

---

Cargo.lock
devolutions-gateway/Cargo.toml
devolutions-gateway/src/config.rs
devolutions-gateway/src/http/controllers/jet.rs
devolutions-gateway/src/interceptor/mod.rs
devolutions-gateway/src/interceptor/pcap.rs
devolutions-gateway/src/interceptor/pcap_recording.rs
devolutions-gateway/src/jet/association.rs
devolutions-gateway/src/jet_client.rs
devolutions-gateway/src/lib.rs
devolutions-gateway/src/plugin_manager.rs
devolutions-gateway/src/plugin_manager/general.rs
devolutions-gateway/src/plugin_manager/packets_parsing.rs
devolutions-gateway/src/plugin_manager/plugin_info.rs
devolutions-gateway/src/plugin_manager/recording.rs
devolutions-gateway/src/proxy.rs
devolutions-gateway/src/service.rs
devolutions-gateway/src/transport/mod.rs
devolutions-gateway/src/transport/tcp.rs
devolutions-gateway/src/utils.rs
jet-proto/Cargo.toml
jet-proto/tests/rdp.rs
jet-proto/tests/routing_client.rs

- added handling of the jet-tp claim
- added ffi to communicate with dll
- fixed tests

Session recording inside gateway

---

Cargo.lock
devolutions-gateway/src/http/controllers/sogar_token.rs
devolutions-gateway/src/http/middlewares/sogar_auth.rs
devolutions-gateway/src/registry/mod.rs
devolutions-gateway/src/registry/push_files.rs
devolutions-gateway/src/utils/association.rs

1 - Sogar update to 0.1.1
2 - Don't delete recording when we push the file in a remote repository. The recording will be deleted based on KeepFiles and KeepTime
3 - I improved some logs
4 - cargo fmt

Sogar update

---

powershell/build.ps1

try to remove the nuget cert revocation check and see if it fixes the issue on the CI

Fix powershell build: Remove nuget cert revocation check

---

.github/workflows/ci.yml

Add a skeleton .yml for GitHub workflow. I need this file to exist on the master branch to be able to manually dispatch the workflow.

GitHub workflow skeleton yml

---

.github/workflows/ci.yml
.github/workflows/prepublish.yml
.github/workflows/publish-dev.yml
.github/workflows/publish-release.yml
Cargo.toml
README.md
ci/azure-pipelines.yaml
rust-toolchain.toml

- Only enable LTO when building master
- Put rust channel into a toolchain file
- Skeleton yml files for release pipeline

CI and release pipelines

---

.github/workflows/ci.yml

Ensure we set the Docker base image when generating a release

Fix docker image in release pipeline

---

Cargo.lock
devolutions-gateway/Cargo.toml
devolutions-gateway/src/config.rs
devolutions-gateway/src/generic_client.rs
devolutions-gateway/src/http/controllers/diagnostics.rs
devolutions-gateway/src/jet_client.rs
devolutions-gateway/src/logger.rs
devolutions-gateway/src/plugin_manager.rs
devolutions-gateway/src/rdp.rs
devolutions-gateway/src/service.rs
devolutions-gateway/src/utils.rs
devolutions-gateway/src/websocket_client.rs

Can you confirm this fixes the use cases you told me?

WAYK-2579: improve startup configuration checks

---

devolutions-gateway/src/websocket_client.rs
jetsocat/src/lib.rs
jetsocat/src/listener.rs
jmux-proxy/src/lib.rs

- Use a bounded channel for the API request instead of an unbounded one
(provides backpressure)
- Internal channels are still unbounded because this is faster and the
JUMX protocol's windowing is already providing backpressure.
- Use a oneshot channel for the API response.
- Builder pattern to configure the proxy instead of the 6-parameters
function.

jmux-proxy: improve API

---

Cargo.lock
devolutions-gateway/Cargo.toml
devolutions-gateway/src/generic_client.rs
devolutions-gateway/src/http/controllers/association.rs
devolutions-gateway/src/http/middlewares/auth.rs
devolutions-gateway/src/jet_client.rs
devolutions-gateway/src/preconnection_pdu.rs
devolutions-gateway/src/rdp.rs
devolutions-gateway/src/service.rs
devolutions-gateway/src/token.rs
devolutions-gateway/src/websocket_client.rs
tools/tokengen/src/main.rs

If a given token is reused by a peer with a different IP address, request is rejected.
A cache with a few information extracted from the token is maintained to make this possible.

DPS-5297: mitigate token reuse

---

.github/workflows/ci.yml
Cargo.toml
ci/tlk.ps1
rust-toolchain.toml

Update the toolchain to rust 1.57 and use a custom "production" cargo profile to enable LTO on master builds.

Custom cargo profile

---

devolutions-gateway/src/interceptor/pcap_recording.rs
devolutions-gateway/src/jet_client.rs
devolutions-gateway/src/rdp/sequence_future/nla.rs
devolutions-gateway/src/token.rs
devolutions-gateway/src/transport/mcs.rs
devolutions-gateway/src/transport/rdp.rs
devolutions-gateway/src/websocket_client.rs
jet-proto/src/accept.rs
jet-proto/src/connect.rs
jet-proto/src/lib.rs
jet-proto/src/test.rs

Clippy from latest 1.57 toolchain gives new warnings.

Fix new clippy warnings

---

Cargo.lock
devolutions-gateway/Cargo.toml
jet-proto/Cargo.toml
jetsocat/Cargo.toml
jetsocat/proxy/Cargo.toml
jmux-proxy/Cargo.toml
tools/tokengen/Cargo.toml

I'll wait until we are able to publish the new version of `ceviche` before merging.

Update all dependencies

---

CHANGELOG.md
crates/jmux-proto/src/lib.rs
crates/jmux-proxy/src/codec.rs
crates/proxy-socks/src/socks5.rs
crates/transport/src/any.rs
devolutions-gateway/src/interceptor/pcap.rs
devolutions-gateway/src/rdp/dvc_manager.rs
devolutions-gateway/src/rdp/sequence_future/post_mcs/licensing.rs
devolutions-gateway/src/token.rs
jetsocat/src/main.rs
package/Windows/wisubstg.vbs

Found using https://github.com/crate-ci/typos

style: fix typos

---

devolutions-gateway/src/http/middlewares/log.rs

feat(dgw): downgrade health route logs to debug

---

Cargo.lock
devolutions-gateway/Cargo.toml
devolutions-gateway/src/token.rs
devolutions-gateway/src/websocket_client.rs
devolutions-gateway/tests/dvls_compatibility.rs

feat(dgw): session info when using JMUX

---

.github/workflows/ci.yml

A variable renaming went wrong.

ci: fix pre-release OneDrive upload

---

devolutions-gateway/src/http/controllers/kdc_proxy.rs
devolutions-gateway/src/http/http_server.rs
devolutions-gateway/src/http/middlewares/auth.rs
devolutions-gateway/src/http/middlewares/log.rs
devolutions-gateway/src/http/mod.rs
devolutions-gateway/src/websocket_client.rs

feat(dgw): retrieve KDC token from the path

---

devolutions-gateway/src/http/http_server.rs
devolutions-gateway/src/http/middlewares/cors.rs
devolutions-gateway/src/http/middlewares/mod.rs

feat(dgw): support for CORS calls

---

clients/dotnet/Devolutions.Gateway.Clients/GatewayClient.cs
clients/ts/gateway.generated.ts
devolutions-gateway/doc/api.yaml
devolutions-gateway/src/http/controllers/diagnostics.rs
devolutions-gateway/src/http/controllers/sessions.rs

feat!(openapi): remove scope_token parameter

---

crates/devolutions-gateway-generators/src/lib.rs
devolutions-gateway/src/http/middlewares/auth.rs
devolutions-gateway/src/preconnection_pdu.rs
devolutions-gateway/src/token.rs
devolutions-gateway/tests/dvls_compatibility.rs
devolutions-gateway/tests/token_security.rs

When this claim is specified, a given token can only be used on a Gateway with the very same ID.

feat(dgw): add general claim `jet_gw_id`

---

crates/devolutions-gateway-generators/src/lib.rs
devolutions-gateway/src/http/guards/access.rs
devolutions-gateway/src/token.rs
devolutions-gateway/tests/token_security.rs

feat(dgw): wildcard scope tokens

---

.github/workflows/ci.yml
.github/workflows/jetsocat-nuget.yml
.github/workflows/package.yml
.github/workflows/release.yml

Mostly quality of life improvements when exploring the artifacts on OneDrive.
I also updated ubuntu runners.

ci: quality of life improvements to OneDrive uploads

---

devolutions-gateway/src/http/middlewares/cors.rs

Might want to check request headers to return the appropriate values instead.

Temporary work around?

---

.github/workflows/release.yml

Je l'ai ajoute avant l'upload a OneDrive mais peut etre deplace.

[DEVSEC-604][DEVSEC-606] Generate SBOM

---

.github/workflows/publish-clients.yml

Somehow this fixes the problem.

ci: fix client publishing (bis)

---

devolutions-gateway/openapi/doc/index.adoc
devolutions-gateway/openapi/dotnet-client/docs/SessionInfo.md
devolutions-gateway/openapi/dotnet-client/src/Devolutions.Gateway.Client/Model/SessionInfo.cs
devolutions-gateway/openapi/gateway-api.yaml
devolutions-gateway/openapi/ts-angular-client/model/sessionInfo.ts
devolutions-gateway/src/generic_client.rs
devolutions-gateway/src/jet_client.rs
devolutions-gateway/src/jet_rendezvous_tcp_proxy.rs
devolutions-gateway/src/openapi.rs
devolutions-gateway/src/proxy.rs
devolutions-gateway/src/rdp.rs
devolutions-gateway/src/session.rs
devolutions-gateway/src/token.rs
devolutions-gateway/src/websocket_client.rs
tools/tokengen/src/main.rs

This adds a new claim `jet_ttl` specifying the maximum lifetime for a given session. Devolutions Gateway will kill the session if it is still running after the deadline.

feat(dgw): maximum session lifetime enforcing

---

.github/workflows/ci.yml

Add a macOS universal binary for jetsocat

Universal jetsocat build for macOS

---

.github/workflows/ci.yml
.github/workflows/package.yml

We have issues with these runners, I'm trying to change and see if it's any better.

ci: feeling lucky with runners

---

.github/workflows/ci.yml
Cargo.lock
devolutions-gateway/Cargo.toml
devolutions-gateway/src/token.rs
devolutions-gateway/tests/token_security.rs

test(dgw): fix token_cache test

---

.github/workflows/package.yml

Based on a different public repo
https://github.com/Devolutions/devolutions-crypto/blob/master/.github/workflows/ci.yml#L246

feat (sbom): fix devolutions action checkout

---

.github/workflows/package.yml

cyclonedx cargo file stored on OneDrive was updated
https://github.com/Devolutions/devolutions-gateway/actions/runs/3396225996 ✔

feat (sbom): Fix sbom generation

---

devolutions-gateway/src/config.rs
devolutions-gateway/src/lib.rs
devolutions-gateway/src/rdp.rs
rust-toolchain.toml

TLS certificate chain may be specified if necessary.

fix: allow TLS certificate chain

---

.github/workflows/ci.yml
.github/workflows/publish-clients.yml
ci/npm-publish.ps1
devolutions-gateway/openapi/dotnet-client/build.ps1
devolutions-gateway/openapi/dotnet-subscriber/build.ps1
devolutions-gateway/openapi/ts-angular-client/build.ps1
utils/dotnet/.editorconfig
utils/dotnet/Devolutions.Gateway.Utils.Tests/Devolutions.Gateway.Utils.Tests.csproj
utils/dotnet/Devolutions.Gateway.Utils.Tests/JsonSerializationTests.cs
utils/dotnet/Devolutions.Gateway.Utils.Tests/KdcUtilsTests.cs
utils/dotnet/Devolutions.Gateway.Utils.Tests/TokenUtilsTests.cs
utils/dotnet/Devolutions.Gateway.Utils.Tests/Usings.cs
utils/dotnet/Devolutions.Gateway.Utils/Devolutions.Gateway.Utils.csproj
utils/dotnet/Devolutions.Gateway.Utils/src/AccessScope.cs
utils/dotnet/Devolutions.Gateway.Utils/src/AccessScopeJsonConverter.cs
utils/dotnet/Devolutions.Gateway.Utils/src/ApplicationProtocol.cs
utils/dotnet/Devolutions.Gateway.Utils/src/ApplicationProtocolJsonConverter.cs
utils/dotnet/Devolutions.Gateway.Utils/src/AssociationClaims.cs
utils/dotnet/Devolutions.Gateway.Utils/src/IGatewayClaims.cs
utils/dotnet/Devolutions.Gateway.Utils/src/JmuxClaims.cs
utils/dotnet/Devolutions.Gateway.Utils/src/KdcClaims.cs
utils/dotnet/Devolutions.Gateway.Utils/src/KdcUtils.cs
utils/dotnet/Devolutions.Gateway.Utils/src/ScopeClaims.cs
utils/dotnet/Devolutions.Gateway.Utils/src/TargetAddr.cs
utils/dotnet/Devolutions.Gateway.Utils/src/TargetAddrJsonConverter.cs
utils/dotnet/Devolutions.Gateway.Utils/src/TokenUtils.cs
utils/dotnet/GatewayUtils.sln
utils/dotnet/build.ps1

feat(utils): initial Devolutions.Gateway.Utils nuget

---

package/Windows/Actions/CustomAction.cpp
package/Windows/Actions/stdafx.h

fix(installer): only use the host portion of the access URI

---

devolutions-gateway/src/rdp_extension.rs

I’m unsure why reusing the ClientConfig is an issue.
rustls doc says:
> Making one of these can be expensive,
> and should be once per process rather than once per connection.
source: https://docs.rs/rustls/0.20.8/rustls/struct.ClientConfig.html
In our case, this doesn’t work, so I’m creating a new ClientConfig from scratch each time (slower).
I opened an issue on rustls side:
https://github.com/rustls/rustls/issues/1186

fix(dgw): workaround rustls’ ClientConfig reuse issue

---

package/Windows/Actions/CustomAction.cpp

.cer is another popular extension for certificate files.

feat(installer): show *.cer when browsing for certificate files

---

devolutions-gateway/src/lib.rs
devolutions-gateway/src/tcp.rs
devolutions-gateway/src/websocket_client.rs

Issue: DGW-82
https://user-images.githubusercontent.com/3809077/225110187-3522c5c5-f64b-4847-9bc9-3e7c58554df1.mp4

feat(dgw): WebSocket-TCP endpoint (/jet/tcp)

---

devolutions-gateway/Cargo.toml
devolutions-gateway/src/config.rs
devolutions-gateway/src/jet_client.rs
devolutions-gateway/src/jrec.rs
devolutions-gateway/src/lib.rs
devolutions-gateway/src/registry/mod.rs
devolutions-gateway/src/token.rs
devolutions-gateway/src/websocket_client.rs
powershell/DevolutionsGateway/Public/DGateway.ps1

- Add new JREC token type for session recording
- Add new jet_rft (recording file type) private claim
- Handle /jet/jrec route for WSS to file streaming
- Improve PowerShell module to generate JREC tokens

Initial JREC session recording token support with /jet/jrec route

---

devolutions-gateway/src/config.rs
devolutions-gateway/src/interceptor/plugin_recording.rs
devolutions-gateway/src/jet_client.rs
devolutions-gateway/src/jrec.rs
devolutions-gateway/src/token.rs
devolutions-gateway/src/websocket_client.rs

I opened this PR mostly to push a semver-compliant commit associated to this PR: https://github.com/Devolutions/devolutions-gateway/pull/404
This is so I don’t forget anything when writing the changelog (mostly auto-generated thanks to semver spec)
Also tagging the Jira issue.
Issue: DGW-64

Follow up on new /jet/jrec endpoint for session recording

---

devolutions-gateway/src/generic_client.rs
devolutions-gateway/src/rdp_extension.rs
devolutions-gateway/src/websocket_client.rs
devolutions-gateway/src/websocket_forward.rs

- /jet/tcp → /jet/fwd/tcp
- /jet/tls → /jet/fwd/tls

refactor(dgw)!: move ws-{tcp,tls} endpoints under /jet/fwd

---

devolutions-gateway/src/http/controllers/heartbeat.rs
devolutions-gateway/src/http/mod.rs
devolutions-gateway/src/jrec.rs
devolutions-gateway/src/token.rs
devolutions-gateway/src/websocket_client.rs
powershell/DevolutionsGateway/Public/DGateway.ps1

- use recording.json, recording.webm instead of session.json, session.webm
- use /jet/jrec/push instead of /jet/jrec (/jet/jrec/pull will be added next)
- use fileType=webm query param instead of jet_rft private claim in token
- add jet_rop=push|pull private claim in token (must match /jetc/jrec/push|pull)

update /jetc/jrec/push, token claims, file layout

---

jetsocat/src/utils.rs

With this change, port may be omitted from the WebSocket URL. In such case, the default port will be used (either 80 or 443).

feat(jetsocat): default port in WebSocket URLs

---

devolutions-gateway/src/api/fwd.rs

This was inconsistent with other routes such as /jet/jmux where `dst_hst` will have the `http` or `https` scheme, but this is simply used as a filter policy and Devolutions Gateway will not wrap the stream further into an "`https` protocol layer".
Instead, we rely on the requested uri to choose between plain TCP and TLS wrapping at proxy level (i.e.: /jet/fwd/tcp vs /jet/fwd/tls).

fix(dgw): do not enforce scheme in /jet/fwd

---

devolutions-gateway/src/token.rs
utils/dotnet/Devolutions.Gateway.Utils/Devolutions.Gateway.Utils.csproj
utils/dotnet/Devolutions.Gateway.Utils/src/ApplicationProtocol.cs

This is known as Devolutions Gateway Tunnel on RDM side.
Issue: ARC-142

feat(dgw): add known application protocol "tunnel"

---

devolutions-gateway/build.rs
utils/dotnet/Devolutions.Gateway.Utils.Tests/JsonSerializationTests.cs
utils/dotnet/Devolutions.Gateway.Utils/Devolutions.Gateway.Utils.csproj
utils/dotnet/Devolutions.Gateway.Utils/src/JrlClaims.cs
utils/dotnet/Devolutions.Gateway.Utils/src/RecordingClaims.cs
utils/dotnet/Devolutions.Gateway.Utils/src/RevocationList.cs

Jrl claims have this shape:
```
{
"iat": 1649109471,
"jrl": {
"jti": [
"d96f17ba-60f2-4334-b5ff-77c4a751275b",
"e349faab-7279-4579-b32f-9e3c2fec27c5"
]
},
"jti": "167cffd1-e444-4112-bafa-a64af1db2f7d"
}
```

fix(dotnet-utils): invalid jrl claims

---

utils/dotnet/Devolutions.Gateway.Utils.Tests/JsonSerializationTests.cs
utils/dotnet/Devolutions.Gateway.Utils/Devolutions.Gateway.Utils.csproj
utils/dotnet/Devolutions.Gateway.Utils/src/JrlClaims.cs
utils/dotnet/Devolutions.Gateway.Utils/src/RecordingClaims.cs

Recording tokens are expected to live longer.

feat(dotnet-utils): default exp of 4h for jrec token

---

devolutions-gateway/src/api/kdc_proxy.rs
devolutions-gateway/src/extract.rs
devolutions-gateway/src/lib.rs
devolutions-gateway/src/middleware/auth.rs
jetsocat/src/main.rs

fix(dgw): KDC proxy auth using token in path

---

.github/workflows/package.yml

Removed from https://github.com/Devolutions/devolutions-gateway/pull/453

ci: added back SBOM generation 

---

.github/workflows/package.yml

Uses changes from https://github.com/Devolutions/actions/pull/390
Ran successfully https://github.com/Devolutions/devolutions-gateway/actions/runs/5291385875

SBOM cdxgen

---

devolutions-gateway/src/rdp_pcb.rs

Too many bytes are consumed when PCB string is missing the null-terminator.
Indeed, until now the number of bytes to consume was found by computing the size of the previously decoded PCB when re-encoded. IronRDP will always encode PCB string with a null-terminator (just like mstcs client). This is generally correct, but will cause payload truncation when the received PCB string did not originally contain the null-terminator.
This patch is changing this. The "cursor API" is used instead, and cursor position after reading the PCB can be used to find the number of bytes actually read (even if re-encoding the PDU would give a different result).
Issue: DGW-97

fix(dgw): truncated payload after PCB reading

---

README.md
devolutions-gateway/src/config.rs

Document `RecordingPath` and `Ngrok` options as stable.

docs(dgw): stabilize `RecordingPath` and `Ngrok` options

---

devolutions-gateway/src/rdp_extension.rs

This will help when troubleshooting web client issues.

fix(dgw): more trace records for RDP extension

---

README.md
devolutions-gateway/src/config.rs
devolutions-gateway/src/log.rs
devolutions-gateway/src/proxy.rs
devolutions-gateway/src/service.rs
devolutions-gateway/tests/config.rs

This adds a stable option to configure log verbosity.

feat(dgw): new `VerbosityProfile` option

---

powershell/DevolutionsGateway/Public/DGateway.ps1
powershell/pester/Config.Tests.ps1

```
[string] $TlsPrivateKeyPassword,
[ValidateSet("External", "System")]
[string] $TlsCertificateSource,
[string] $TlsCertificateSubjectName,
[string] $TlsCertificateStoreName,
[ValidateSet("CurrentUser", "LocalMachine", "CurrentService")]
[string] $TlsCertificateStoreLocation,
```

add new TLS configuration options

---

README.md
devolutions-gateway/src/config.rs
devolutions-gateway/tests/config.rs

Adds the configuration keys for the Devolutions Gateway Standalone mode.

feat(dgw): add config keys for standalone web app

---

Cargo.lock
crates/jet-proto/Cargo.toml
devolutions-gateway/Cargo.toml
devolutions-gateway/src/api/health.rs
devolutions-gateway/src/api/kdc_proxy.rs
devolutions-gateway/src/http.rs
devolutions-gateway/src/listener.rs
devolutions-gateway/src/middleware/auth.rs
devolutions-gateway/src/middleware/log.rs

Supersede https://github.com/Devolutions/devolutions-gateway/pull/613

build(deps): update HTTP-related dependencies

---

devolutions-gateway/src/config.rs
devolutions-gateway/src/tls.rs
devolutions-gateway/src/utils.rs

fix(dgw): spurious warning when using a wildcard certificate

---

README.md
devolutions-gateway/src/config.rs
devolutions-gateway/tests/config.rs

Not a breaking change, because the option is not yet released.

refactor(dgw): rename UsersPath option to UsersFile

---

devolutions-gateway/src/api/webapp.rs

The root folder for the web application is now found either along the executable, or at the location specified by the `DGATEWAY_WEBAPP_PATH` env variable.

fix(dgw): adjust web application root folder path

---

devolutions-gateway/src/api/webapp.rs
webapp/src/client/app/app-auth.interceptor.ts
webapp/src/client/app/modules/login/login.component.html
webapp/src/client/app/modules/login/login.component.scss
webapp/src/client/app/modules/login/login.component.ts
webapp/src/client/app/modules/web-client/rdp/form/rdp-form.component.html
webapp/src/client/app/modules/web-client/rdp/form/rdp-form.component.scss
webapp/src/client/app/modules/web-client/rdp/form/rdp-form.component.ts
webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.ts
webapp/src/client/app/shared/services/api.service.ts
webapp/src/client/app/shared/services/auth.service.ts
webapp/src/client/app/shared/services/dynamic-component.service.ts
webapp/src/client/app/shared/services/web-session.service.ts

- autologin adjustments. Also includes changes to the rust code. (thanks @irvingoujAtDevolution!!)
re:  sending header property 'x-requested-with': 'XMLHttpRequest'.
- auto complete on for the login form and the RDP connection form.
- fixed labels in the dropdown for screen sizes.
- added hide/show password feature to the login screen and the RDP connection form.

fix(dgw): autologin fixes, autocomplete adjusted, hide/show password.

---

webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.html
webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.scss
webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.ts

Added feature that allows for the session to go into full screen mode of the monitor. 
The session toolbar is initially hidden in full screen mode. It reappears when the user hovers the mouse at the top edge of the screen.

feat(webapp): add full screen mode for monitor screen

---

webapp/src/client/app/modules/base/menu/menu-list-active-sessions/menu-list-active-sessions.component.html
webapp/src/client/app/modules/base/menu/menu-list-active-sessions/menu-list-active-sessions.component.scss
webapp/src/client/app/modules/base/menu/menu-list-active-sessions/menu-list-active-sessions.component.ts
webapp/src/client/app/modules/web-client/rdp/form/rdp-form.component.ts
webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.html
webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.ts
webapp/src/client/app/shared/components/dynamic-tab/dynamic-tab.component.ts
webapp/src/client/app/shared/components/tab-view/tab-view.component.html
webapp/src/client/app/shared/components/tab-view/tab-view.component.ts
webapp/src/client/app/shared/models/web-session.model.ts
webapp/src/client/app/shared/services/dynamic-component.service.ts
webapp/src/client/app/shared/services/web-session.service.ts

- Fixed a bug in the sidebar menu displaying the active sessions. 
- Continued to adjust the menu stylings as per the Figma documentation.

fix(webapp): fix bug managing active sessions in the left sidebar menu

---

crates/network-scanner-net/src/runtime.rs
crates/network-scanner-proto/src/icmp_v4.rs

This way, there is less indirections in our data structure.
What do you think? @irvingoujAtDevolution

refactor(dgw): fix clippy warnings in network scan

---

webapp/src/client/app/app.component.ts
webapp/src/client/app/modules/base/menu/app-menu.component.ts
webapp/src/client/app/modules/base/menu/menu-list-active-sessions/menu-list-active-sessions.component.ts
webapp/src/client/app/modules/web-client/rdp/form/rdp-form.component.ts
webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.html
webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.ts
webapp/src/client/app/shared/bases/base-web-client.component.ts
webapp/src/client/app/shared/components/dynamic-tab/dynamic-tab.component.ts
webapp/src/client/app/shared/components/tab-view/tab-view.component.html
webapp/src/client/app/shared/components/tab-view/tab-view.component.ts
webapp/src/client/app/shared/enums/screen-size.enum.ts
webapp/src/client/app/shared/models/component-status.model.ts
webapp/src/client/app/shared/models/session.ts
webapp/src/client/app/shared/models/web-session.model.ts
webapp/src/client/app/shared/services/auth.service.ts
webapp/src/client/app/shared/services/dynamic-component.service.ts
webapp/src/client/app/shared/services/utils/storage.service.ts
webapp/src/client/app/shared/services/utils/string.service.ts
webapp/src/client/app/shared/services/web-client.service.ts
webapp/src/client/app/shared/services/web-session.service.ts

- added full screen mode.
- fixed screen size data sent to IronRDP component
- fixed screen size when default setting or the full screen setting is used in input form.
- fixed when token expires and session data was not removed.

fix(webapp): bug fixes for removing connections & added full screen size feature.

---

webapp/src/client/app/modules/web-client/rdp/form/rdp-form.component.ts
webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.html
webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.ts
webapp/src/client/app/shared/components/dynamic-tab/dynamic-tab.component.ts
webapp/src/client/app/shared/services/web-client.service.ts
webapp/src/client/app/shared/services/web-session.service.ts

-Bug fix: session connections were not closed upon logout. 
-removed dead code

fix(webapp): terminate session connections on logout.

---

tools/tokengen/src/main.rs

`cargo clippy --fix` for the tokengen crates

refactor(tokengen): fix clippy warnings

---

webapp/src/client/app/modules/web-client/rdp/form/rdp-form.component.ts

- small fix for setting the hostname in the rdp form when the form is returned from ctrl-alt-del sign out, a disconnect via the Start Menu, or an error in a connection.

fix(webapp): fix selection of hostname rdp form

---

Cargo.lock
devolutions-gateway/Cargo.toml
devolutions-gateway/src/api/mod.rs
devolutions-gateway/src/api/network_scan.rs
devolutions-gateway/src/extract.rs
devolutions-gateway/src/token.rs

Added basic api websocket endpoint for network scan

feat(dgw): network scan HTTP API

---

webapp/src/client/app/modules/web-client/rdp/form/rdp-form.component.ts

handles the case for when the local storage is empty for hostnames.

local storage Hostnames bug fix when storage is empty.

---

crates/network-scanner/examples/mdns.rs
crates/network-scanner/src/mdns.rs
crates/network-scanner/src/netbios.rs
crates/network-scanner/src/ping.rs
crates/network-scanner/src/scanner.rs
crates/network-scanner/src/task_utils.rs

Enhance readability
1.change some function names so it align with it's semantics
2. update comments
3. use TimeoutManager whenver possible
4. use parameter destructure whenever possible
5. fix typos

refactor: network-scanner crate housekeeping

---

package/WindowsManaged/Actions/GatewayActions.cs
package/WindowsManaged/DevolutionsGateway.csproj
package/WindowsManaged/Dialogs/ExitDialog.cs
package/WindowsManaged/Dialogs/ProgressDialog.cs
package/WindowsManaged/Dialogs/Wizard.cs
package/WindowsManaged/Resources/DevolutionsGateway_en-us.wxl
package/WindowsManaged/Resources/DevolutionsGateway_fr-fr.wxl
package/WindowsManaged/Resources/Strings.g.cs
package/WindowsManaged/Resources/Strings_en-US.json
package/WindowsManaged/Resources/Strings_fr-FR.json

This PR adds an (almost complete) French localization.
Additionally:
- Bump wixsharp dependency to 1.25.0
- On installing the embedded web application, launch the browser when the user presses "Finish" instead of once the install is completed. This prevents the installer from hanging around while the user goes on to play 🎲

feat(installer): French localization and UI tweaks

---

package/WindowsManaged/Resources/DevolutionsGateway_fr-fr.wxl
package/WindowsManaged/Resources/Strings_fr-FR.json

Simply update the French localization with missing strings

feat(installer): additional localization strings

---

crates/network-scanner/examples/ipconfig.rs
crates/network-scanner/src/interfaces/linux.rs
crates/network-scanner/src/interfaces/windows.rs
devolutions-gateway/src/api/net.rs

fix(dgw): fix endpoint /jet/net/config for linux

---

devolutions-gateway/src/ngrok.rs

Follow up to https://github.com/Devolutions/devolutions-gateway/pull/718#discussion_r1499356007

style(dgw): fix ngrok subscription-related typos

---

webapp/src/client/app/modules/web-client/ard/web-client-ard.component.html
webapp/src/client/app/modules/web-client/ard/web-client-ard.component.ts
webapp/src/client/app/modules/web-client/form/web-client-form.component.ts
webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.html
webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.ts
webapp/src/client/app/modules/web-client/ssh/web-client-ssh.component.ts
webapp/src/client/app/modules/web-client/telnet/web-client-telnet.component.ts
webapp/src/client/app/modules/web-client/vnc/web-client-vnc.component.html
webapp/src/client/app/modules/web-client/vnc/web-client-vnc.component.ts
webapp/src/client/app/shared/services/web-session.service.ts

- Removed all the console.log entries in the .ts code, including the one that shows connection parameters.
- Turned off the debugwasm & verbose for IronRDP and IronVNC.

DGW-140-Standalone-Passwords-are-shown-in-clear-text-in-the-DevTool-Console

---

webapp/src/client/app/modules/base/menu/menu-list-active-sessions/menu-list-active-sessions.component.html
webapp/src/client/app/modules/base/menu/menu-list-active-sessions/menu-list-active-sessions.component.scss
webapp/src/client/app/modules/web-client/form/web-client-form.component.scss
webapp/src/client/app/modules/web-client/form/web-client-form.component.ts
webapp/src/client/app/shared/enums/web-client-protocol.enum.ts

Made changes to Web Form:
- fixed the host autocomplete dropdown from being cut off in it's container. 
This also fixed the issue with scroll bars appearing.
- Added the tooltips for Telnet and SSH dropdown.
- Also fixed in the same code, an un-reported issue with the protocol dropdown showing the wrong tooltip when there was an error displayed above the web form.
Changes in the sidebar:
- When a long host name is used it was cut off. Added the tooltip ellipsis to manage these cases.

DGW-143-Standalone-Web-App-UI-Issues

---

webapp/src/client/app/modules/web-client/form/web-client-form.component.ts

Small update to preserve the authentication state upon error.

fix(webapp): authentication list state is not preserved on error

---

webapp/angular.json
webapp/package.json

fix(webapp): configure angular production build.

---

webapp/src/client/app/modules/web-client/form/web-client-form.component.ts

fix(webapp): web form UI - fix spinner for autocomplete

---

powershell/DevolutionsGateway/Private/CertificateHelper.ps1

fix(pwsh): support for non-PEM, binary certificate files

---

webapp/src/client/app/modules/web-client/ard/web-client-ard.component.html
webapp/src/client/app/modules/web-client/ard/web-client-ard.component.ts
webapp/src/client/app/modules/web-client/vnc/web-client-vnc.component.ts

fix(webapp): improve the error catching for VNC and ARD

---

webapp/package-lock.json
webapp/package.json

- fix connection not shut down properly

fix(webapp): update IronVNC to 0.1.6

---

webapp/src/client/app/modules/web-client/ard/web-client-ard.component.ts
webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.ts
webapp/src/client/app/modules/web-client/ssh/web-client-ssh.component.ts
webapp/src/client/app/modules/web-client/telnet/web-client-telnet.component.ts
webapp/src/client/app/modules/web-client/vnc/web-client-vnc.component.ts
webapp/src/client/app/shared/services/web-session.service.ts

fix(webapp): shutdown not called when closing from left menu

---

webapp/proxy.conf.json
webapp/src/assets/css/theme/_light-theme.scss
webapp/src/client/app/modules/base/menu/app-menu.component.html
webapp/src/client/app/modules/base/menu/app-menu.component.scss
webapp/src/client/app/modules/base/menu/app-menu.component.ts
webapp/src/client/app/shared/services/api.service.ts

copied dvls css with small adjustment on padding

Add version number on the bottom of the app menu

---

webapp/src/client/app/modules/web-client/ard/web-client-ard.component.ts
webapp/src/client/app/modules/web-client/form/web-client-form.component.scss
webapp/src/client/app/modules/web-client/form/web-client-form.component.ts
webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.ts
webapp/src/client/app/modules/web-client/vnc/web-client-vnc.component.ts

fix(webapp): show error backtrace for VNC, ARD and RDP clients

---

.github/workflows/ci.yml

Remove conan setup from the CI, it's no longer needed

fix(ci): Remove conan

---

.cargo/config
.github/workflows/ci.yml
ci/tlk.ps1
jetsocat/nuget/Devolutions.Jetsocat.nuspec
jetsocat/nuget/Devolutions.Jetsocat.targets

Build `jetsocat` for Linux ARM64 target

build(jetsocat): build jetsocat for linux-arm64 target

---

.github/workflows/ci.yml
.gitignore
ci/tlk.ps1
package/Linux/gateway/debian/copyright
package/Linux/gateway/template/rules

Deploy the web client frontend in /usr/share/devolutions-gateway/webapp/client

fix(installer): add webapp client frontend to .deb package

---

.github/workflows/release.yml
package/Linux/Dockerfile
package/Windows/Dockerfile

Add and import the Devolutions Gateway PowerShell module in containers

ci: add PowerShell module to containers

---

devolutions-gateway/src/api/jrec.rs
devolutions-gateway/src/api/mod.rs
devolutions-gateway/src/api/webapp.rs
devolutions-gateway/src/config.rs
devolutions-gateway/src/middleware/auth.rs

feat(dgw): add /jet/jrec/play endpoint

---

webapp/package-lock.json
webapp/package.json

- Improve MVS codec performance by about 60%
- Reenable MVS codec
Issue: DGW-138

perf(webapp): update IronVNC to 0.2.2

---

.github/workflows/package.yml
.github/workflows/release.yml
ci/tlk.ps1

Preserve debug symbols for Devolutions Gateway on Windows

ci: preserve Windows .pdb files

---

webapp/src/client/app/app.module.ts
webapp/src/client/app/modules/web-client/form/form-components/rdp/rdp-form.component.ts
webapp/src/client/app/modules/web-client/web-client.module.ts

DGW-176-Login-screen-not-shown-when-opening-jet-webapp-client

---

webapp/src/client/app/modules/web-client/net-scan/net-scan.component.html
webapp/src/client/app/modules/web-client/net-scan/net-scan.component.scss
webapp/src/client/app/modules/web-client/net-scan/net-scan.component.ts

when on hover, a scroll bar horizontally will pop up (if the string is long enough), allow user to view the entire ip address or username

fix(webapp):fix ui align with titile or ip is too long

---

devolutions-gateway/src/api/jrl.rs

It’s preferable to proceed like this to avoid losing current JRL file if the file is truncated without being rewritten succesfully immediately.
Issue: DGW-104

fix(dgw): write new JRL into a temporary file, and swap on success

---

webapp/src/client/app/modules/web-client/form/web-client-form.component.html
webapp/src/client/app/modules/web-client/form/web-client-form.component.ts
webapp/src/client/app/shared/services/utils/string.service.ts

fix(webapp): format the error backtrace to show line breaks

---

webapp/src/client/app/modules/web-client/ard/web-client-ard.component.ts
webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.ts
webapp/src/client/app/modules/web-client/vnc/web-client-vnc.component.ts

fix(webapp): menu icon does not update on error for RDP, ARD, VNC

---

webapp/src/client/app/modules/web-client/form/web-client-form.component.ts

fix(webapp): tooltip for the selected protocol is always set to RDP

---

powershell/DevolutionsGateway/Public/DGateway.ps1

To add support for Linux with Devolutions Gateway in PowerShell, I have updated the functions:
- `Start-DGateway`
- `Stop-DGateway`
- `Restart-DGateway`
I have also created a function `Get-DGatewayService` to retrieve the status of the service. This wraps the systemd commands on Linux to operate on and retrieve the status of the service. This supports a custom service name, if you have multiple, with defaults to `devolutionsgateway` on Windows and `devolutions-gateway.service` on Linux.

Update Gateway PowerShell service functions for Linux support

---

powershell/DevolutionsGateway/Public/DGateway.ps1

cc: @alistek just FYI, it's important to maintain compatibility with Windows PowerShell

fix(powershell): restore compatability with Windows PowerShell

---

crates/network-scanner/src/interfaces/linux.rs
crates/network-scanner/src/interfaces/mod.rs
crates/network-scanner/src/interfaces/windows.rs
devolutions-gateway/src/api/net.rs

Rework network interface DTO definition for network scan crates and endpoint. As described in Jira ticket.
Issue: DGW-187

fix(dgw): rework network interface DTO definition

---

devolutions-agent/src/config.rs
devolutions-agent/src/service.rs

For consistency between our config files.

refactor(agent): updater.disable → updater.enabled

---

utils/dotnet/Devolutions.Gateway.Utils.Tests/JsonSerializationTests.cs
utils/dotnet/Devolutions.Gateway.Utils/Devolutions.Gateway.Utils.csproj
utils/dotnet/Devolutions.Gateway.Utils/src/AssociationClaims.cs
utils/dotnet/Devolutions.Gateway.Utils/src/JmuxClaims.cs
utils/dotnet/Devolutions.Gateway.Utils/src/SessionTtl.cs
utils/dotnet/Devolutions.Gateway.Utils/src/SessionTtlJsonConverter.cs

feat(dotnet-utils): `jet_ttl` claim support

---

webapp/player/index.html
webapp/player/js/index.js
webapp/player/js/trp-decoder.js

Re-organized file structure, separated JS code from the`<script>` tag. 
Fixed cast file not working
Fixed title

fix(dgw): fix cast file not working, add title to HTML page

---

.github/workflows/ci.yml

I forgot we needed the outputs from the preflight job :man_facepalming:

ci: fix OneDrive upload job

---

webapp/player/index.html
webapp/player/js/index.js

- CSS changes, the recording player now scales with the size of the window
Issue: DGW-198

fix(dgw): recording player now scales with the size of the window

---

.github/workflows/ci.yml

I missed a few places in the previous PR.

ci: install aws-lc dependencies for all targets

---

docs/NOW-spec.md

Proposed changes/questions for the draft NOW-PROTO specification

NOW-PROTO corrections

---

webapp/player/js/index.js
webapp/player/js/trp-decoder.js

1. Remove usage of btoa, it fails on different charset
2. Add 1 millisecond if the time of previous event is the same at the next event. Otherwise the player will throw an error
Issue: DPS-11197

fix(dgw): fix recording player parsing problem

---

webapp/biome.json
webapp/package-lock.json
webapp/package.json

Added Biome as formatter and linter for Webapp.
This PR only contains change in dependency and configuration files.

chore(webapp): add Biome as linter for webapp

---

webapp/src/client/app/modules/web-client/form/form-controls/preconnection-blob/pre-connection-blob-control.component.ts

fix(webapp): clicking more settings in rdp form disables connect session button

---

devolutions-gateway/src/config.rs
devolutions-gateway/src/lib.rs
devolutions-gateway/src/recording.rs
devolutions-gateway/src/service.rs

This environment variable can be used optionally to specify the path to the XMF native library.

feat(dgw): support env variable DGATEWAY_LIB_XMF_PATH

---

.github/workflows/package.yml

ci: download Cadeau only on Windows in package workflow

---

.github/workflows/release.yml
package/Linux/Dockerfile
package/Windows/Dockerfile

XMF native library artifact was not properly prepared before packaging the container.

ci(release): fix container build step

---

crates/jmux-proxy/src/lib.rs

In JMUX proxy, a HashSet is used to track channels waiting for window adjustement instead of iterating through the whole list.
Throughput and CPU-usage is slightly improved.
1 connection:
```
[  1] 0.0000-600.4660 sec  16.0 GBytes   229 Mbits/sec
```
2 connections:
```
[  2] 0.0000-605.0918 sec  8.18 GBytes   116 Mbits/sec
[  1] 0.0000-605.1930 sec  8.18 GBytes   116 Mbits/sec
[SUM] 0.0000-605.1930 sec  16.4 GBytes   232 Mbits/sec
```
10 connections:
```
[  9] 0.0000-626.1216 sec  1.69 GBytes  23.1 Mbits/sec
[ 10] 0.0000-626.2644 sec  1.69 GBytes  23.1 Mbits/sec
[  1] 0.0000-626.2643 sec  1.69 GBytes  23.1 Mbits/sec
[  3] 0.0000-626.2633 sec  1.69 GBytes  23.1 Mbits/sec
[  8] 0.0000-626.2619 sec  1.69 GBytes  23.2 Mbits/sec
[  6] 0.0000-626.3628 sec  1.69 GBytes  23.1 Mbits/sec
[  7] …
```

perf(jetsocat,dgw): HashSet to track channels waiting for adjustment

---

docs/JMUX-proxy-performance.md

This document summarize the optimization work done on our JMUX proxy implementation so far.

docs: add JMUX-proxy-performance.md

---

Cargo.lock
devolutions-agent/Cargo.toml
devolutions-agent/src/main.rs
devolutions-agent/src/remote_desktop/tls.rs
devolutions-gateway/Cargo.toml
devolutions-gateway/src/config.rs
devolutions-gateway/src/main.rs
devolutions-gateway/src/rdp_extension.rs
devolutions-gateway/src/service.rs
devolutions-gateway/src/tls.rs

We keep using ring as our crypto provider for now.

build: update cryptography dependencies

---

.github/workflows/package.yml
.github/workflows/release.yml

Debug Symbols were not stored at the expected place.

ci: fix agent package and release workflow

---

.github/workflows/package.yml
.github/workflows/release.yml

ci(agent): zip all debug symbol files together

---

crates/devolutions-pedm-contextmenu/devolutions-pedm-contextmenu-shell/src/lib_win.rs

refactor: follow up to PR 990

---

.github/workflows/ci.yml
.github/workflows/package.yml
ci/tlk.ps1
package/AgentWindowsManaged/Actions/AgentActions.cs
package/AgentWindowsManaged/Actions/CustomActions.cs
package/AgentWindowsManaged/Program.cs
package/AgentWindowsManaged/Resources/Includes.cs

This PR adds `devolutions-host` to installer & CI scripts
(This is follow-up PR for https://github.com/Devolutions/devolutions-gateway/pull/997)

feat(host): devolutions-host installer changes

---

tools/jetsocat-bench.nu

- Add parameters
- Allow module usage
- Custom command for converting results into a markdown table
Script usage:
```shell
$ ./tools/jetsocat-bench.nu build ./target master optimization-branch
$ ./tools/jetsocat-bench.nu run
```
Module usage:
```nu
$ use ./tools/jetsocat-bench.nu
$ jetsocat-bench run | jetsocat-bench mdtable
```
This will output a table looking like this (dummy data):
| Name | Parallel connections | Average throughput | Server node peak memory usage | Client node peak memory usage |
|------|----------------------|--------------------|-------------------------------|-------------------------------|
|master.delay.001|1|7.5 MiB/s|12.7 MiB|10.6 MiB|
|master.delay.002|2|15.0 MiB/s|12.7 MiB|10.5 MiB|
|master.delay.010|10|75.3 MiB/s|10.6 MiB|10.6 MiB|
|master.nodelay.001|1|108.0 …

chore(jetsocat-bench): clean up benchmark script

---

webapp/player/js/index.js

fix(player): start recording when tab is open

---

jetsocat/src/doctor.rs
jetsocat/src/main.rs

Returns a link to x509.io Certificate Viewer in order to inspect the certification chain conveniently.

feat(jetsocat): make doctor returns links to x509.io

---

webapp/player/js/index.js
webapp/player/js/players/cast.js
webapp/player/js/players/index.js
webapp/player/js/players/trp.js
webapp/player/js/players/webm.js

Split code into different files, get ready for session shadowing

refactor(dgw): update recording player project structure

---

.github/workflows/ci.yml
.github/workflows/package.yml
ci/tlk.ps1
dotnet/DesktopAgent/build.ps1
package/AgentWindowsManaged/Dialogs/FeaturesDialog.Designer.cs
package/AgentWindowsManaged/Dialogs/FeaturesDialog.cs
package/AgentWindowsManaged/Program.cs

Incremental PR to build and package the new desktop agent executable for PEDM

feat(pedm): initial integration of new desktop agent

---

Cargo.lock
crates/job-queue-libsql/Cargo.toml

Use Marc's Pull Request from libsql https://github.com/tursodatabase/libsql/pull/1791/commits

fix(libsql): fix build on windows

---

crates/win-api-wrappers/src/lib.rs
crates/win-api-wrappers/src/memory.rs
crates/win-api-wrappers/src/netmgmt.rs
crates/win-api-wrappers/src/utils.rs
crates/win-api-wrappers/src/wts.rs
devolutions-session/src/dvc/io.rs

Applied remaining suggestions from https://github.com/Devolutions/devolutions-gateway/pull/1114 and fixed some issues. See the comments.

fix(pedm): audit and refactor netmgmt and wts modules

---

Cargo.lock
jetsocat/Cargo.toml
jetsocat/src/doctor/mod.rs
jetsocat/src/doctor/native_tls.rs
jetsocat/src/doctor/schannel.rs
jetsocat/src/main.rs

These diagnostics will return detailed information about how Windows will understand the specified certification chain.
Issue: ARC-255

feat(jetsocat): Schannel diagnostics for Windows

---

crates/streamer/src/streamer/iter.rs

fix(dgw): adjust tracing level in recording streamer

---

cliff.toml

Just cleaning up the file a bit.

chore: update cliff.toml

---

devolutions-gateway/src/api/jrec.rs
devolutions-gateway/src/service.rs

Follow up to #1167 
I forgot to apply the small suggestions.

refactor(dgw): follow up to PR 1167

---

crates/video-streamer/src/streamer/mod.rs
webapp/shadow-player/src/streamer.css
webapp/shadow-player/src/streamer.ts

this requires https://github.com/Devolutions/devolutions-gateway/pull/1186 to be merged first.

feat(dgw): add a replay button on streaming finish

---

devolutions-gateway/src/api/jrec.rs
devolutions-gateway/src/streaming.rs
webapp/player-project/src/main.ts
webapp/player-project/src/streamers/cast.ts
webapp/player-project/src/streamers/webm.ts

Custom error handling in streaming endpoint and the streamer. 
Since we are going to have localization in the short future, this change makes error handling more clear and manageable.

fix(dgw): streamer error handling with custom code

---

webapp/player-project/index.html
webapp/player-project/package-lock.json
webapp/player-project/package.json
webapp/player-project/public/locales/de/translation.json
webapp/player-project/public/locales/en/translation.json
webapp/player-project/public/locales/es/translation.json
webapp/player-project/public/locales/fr/translation.json
webapp/player-project/src/gateway.ts
webapp/player-project/src/i18n.ts
webapp/player-project/src/main.ts
webapp/player-project/src/notification.ts
webapp/player-project/src/streamers/webm.ts
webapp/recording-player-tester/index.html
webapp/recording-player-tester/src/player.ts
webapp/recording-player-tester/src/streaming-list.ts

This PR introduces a flexible localization system for the streamer with the following key features:
URL query parameter lang (highest priority)
Browser language settings (fallback)
English as default (ultimate fallback)
Language translations are bundled within the player project for simplified deployment
Minimized configuration requirements for installers, RDM, and DVLS
Included initial English and French translations as reference implementations
Seamless language switching without reload
Zero additional setup for installer
Maintainable translation structure for future language additions
Please review the included translations to ensure they accurately convey the intended meanings.

feat(dgw): add localization for streamer

---

.github/workflows/ci.yml

Build the Devolutions.Pedm.Client nuget package in CI

ci: build Devolutions.Pedm.Client in CI

---

package/AgentLinux/CHANGELOG.md
package/Linux/CHANGELOG.md

This updates the package changelogs for 2025.1.0.
This should fix the deb generation in tlk.ps1.
#1203 related

chore(release): update package changelog

---

.github/workflows/build-tools.yml
.github/workflows/ci.yml
.github/workflows/package.yml
.github/workflows/publish-libraries.yml
.github/workflows/release.yml

Start updating ubuntu runners away from 20.04

ci: update ubuntu runners

---

crates/devolutions-agent-shared/src/lib.rs
devolutions-agent/src/lib.rs
devolutions-agent/src/log.rs
devolutions-agent/src/main.rs
devolutions-agent/src/remote_desktop/mod.rs
devolutions-agent/src/service.rs
devolutions-agent/src/session_manager.rs
devolutions-agent/src/updater/mod.rs
devolutions-gateway/src/service.rs

fix(dgw): revert service name to "devolutions-gateway" on Linux

---

.github/workflows/release.yml

Devolutions Agent for Linux is not ready yet.

ci(release): filter out agent Linux artifacts for GitHub releases

---

ci/build.ps1

`$Target` being optional was causing a problem when running the script file like `build.ps1 agent`.
This adds a default `infer` value so that it can be omitted.

build: fix build.ps1 param parsing

---

ci/package-agent-windows.ps1

This fixes the copy message.
It also removes an unnecessary parameter referring to the static `DesktopAgent` directory in the repo.
Closes #1247

build: fix MSI copy message

---

ci/package-gateway-deb.ps1
ci/tlk.ps1

build: fix missing webapp in deb

---

crates/win-api-wrappers/src/netmgmt.rs

refactor(pedm): reintroduce remove_local_group_member

---

utils/dotnet/Devolutions.Gateway.Utils/Devolutions.Gateway.Utils.csproj

build(dotnet): update NuGet packages dependencies

---

crates/win-api-wrappers/src/identity/account.rs
crates/win-api-wrappers/src/identity/sid.rs
crates/win-api-wrappers/src/security/crypt.rs
crates/win-api-wrappers/src/thread.rs
crates/win-api-wrappers/src/token.rs

fix(pedm): check for ERROR_MORE_DATA status at relevant places

---

devolutions-gateway/src/main.rs

https://devolutions.atlassian.net/browse/ARC-307

feat(dgw): add --config-path command-line option

---

devolutions-gateway/src/tls.rs

When using the system certificate store, we now properly reopen the store for each HTTP request, eliminating the need for restarting the service when renewing the certificate.
Issue: DGW-256

fix(dgw): reopen the certificate store for each request

---

devolutions-gateway/src/api/heartbeat.rs
devolutions-gateway/src/api/mod.rs
devolutions-gateway/src/api/preflight.rs
devolutions-gateway/src/config.rs
devolutions-gateway/src/credendials.rs
devolutions-gateway/src/extract.rs
devolutions-gateway/src/lib.rs
devolutions-gateway/src/openapi.rs
devolutions-gateway/src/token.rs
docs/COOKBOOK.md
utils/dotnet/Devolutions.Gateway.Utils/src/AccessScope.cs

Possible operations:
- `get-version`
- `get-agent-version`
- `get-running-session-count`
- `get-recording-storage-health`
- `push-token`
- `push-credentials`
- `lookup-host`
Possible results:
- `version`
- `agent-version`
- `running-session-count`
- `recording-storage-health`
- `resolved-host`
- `alert`
Issue: DGW-245

feat(dgw): preflight API

---

Cargo.lock
devolutions-session/Cargo.toml
devolutions-session/src/dvc/channel.rs
devolutions-session/src/dvc/fs.rs
devolutions-session/src/dvc/now_message_dissector.rs
devolutions-session/src/dvc/process.rs
devolutions-session/src/dvc/task.rs
devolutions-session/src/main.rs

Adds [keyboard layout switcher functionality](https://devolutions.atlassian.net/browse/ARC-271) to now-proto DVC server 
NOTE: This PR merges to `feat/now-proto-server-refactoring` branch, CI could be ignored for now

feat: set keyboard layout functionality

---

devolutions-gateway/src/api/heartbeat.rs
devolutions-gateway/src/api/preflight.rs
devolutions-gateway/src/openapi.rs
docs/COOKBOOK.md

refactor(dgw): follow up to PR #1279

---

webapp/src/client/app/modules/web-client/form/form-controls/enable-cursor-control/enable-cursor-control.component.html

Fix for https://github.com/Devolutions/devolutions-gateway/pull/1329#issuecomment-2876913378

refactor(webapp): add tooltip for enable cursor checkbox

---

crates/win-api-wrappers/src/utils.rs

`expand_environment` is flawed; because it splits the input on "%" there can be improper boundary detection. For example, given input with back-to-back variables like "%HOMEDIR%%HOMEPATH%".
Instead, we walk the string one character at a time and properly tokenize the variables. This still account for the malformed example in Kyle's original comment ("For strings such as "%MyVar%MyVar%", only the first occurrence should be replaced").

fix(pedm): fix flawed expand_environment function

---

webapp/src/client/app/modules/web-client/form/form-controls/resolution-quality-control/resolution-quality-control.component.html

Fix small typo in form label for resolutionQuality.

fix(webapp): typo in resolution quality control

---

.github/workflows/ci.yml

Please wait for @Sylfwood to confirm the token is working

ci: update npm token to ARTIFACTORY_NPM_READ_TOKEN

---

webapp/src/client/app/modules/web-client/vnc/web-client-vnc.component.ts

https://github.com/Devolutions/devolutions-gateway/pull/1402 has to be merged first

refactor(webapp): remove unnecessary scaling after `dynamicResizeSupported` callback in VNC component

---

webapp/src/client/app/modules/web-client/ard/web-client-ard.component.ts

We already handle the toolbar in the https://github.com/Devolutions/devolutions-gateway/blob/master/webapp/src/client/app/shared/components/session-toolbar/session-toolbar.component.ts file.

refactor(webapp): remove toolbar handling in ARD component

---

devolutions-gateway/src/config.rs
devolutions-gateway/src/main.rs

This will make troubleshooting configuration errors much more easier.
Issue: DGW-292

feat(dgw): write startup failures into boot.stacktrace file

---

Cargo.lock
devolutions-agent/Cargo.toml

Look in environment variables to set HTTP, HTTPS or SOCKS proxies.
Issue: DGW-291

feat(agent): auto-detect proxy setup when fetching productinfo.htm

---

package/Linux/Dockerfile
package/Linux/README.md
package/Linux/entrypoint.ps1

Add exhaustive entry point script to Devolutions Gateway container image with most settings mapped from environment variables, such that everything can be reconstructed in temporary storage inside the container. It also works properly in Azure Web App - it can be redeployed and even automatically re-deployed when a new container image is published.

Improve container image for Azure Web App usage

---

webapp/video-player/package-lock.json

This fixes some vulnerabilities detected by Dependabot, including a critical CVE in form-data (CVE-2025-7783).

build: npm audit fix on video player

---

.github/workflows/package.yml

https://github.com/Devolutions/devolutions-gateway/actions/runs/16778043386

ci(sbom): add SBOM to OneDrive

---

webapp/package-lock.json
webapp/package.json
webapp/src/client/app/modules/web-client/ard/web-client-ard.component.ts
webapp/src/client/app/modules/web-client/form/form-components/vnc/vnc-form.component.html
webapp/src/client/app/modules/web-client/form/form-components/vnc/vnc-form.component.ts
webapp/src/client/app/modules/web-client/rdp/web-client-rdp.component.ts
webapp/src/client/app/modules/web-client/vnc/web-client-vnc.component.ts
webapp/src/client/app/shared/bases/base-web-client.component.ts
webapp/src/client/app/shared/enums/session-event-type.enum.ts
webapp/src/client/app/shared/interfaces/forms.interfaces.ts

Follow-up to https://github.com/Devolutions/IronRDP/pull/951.
Before merging this PR, we have to release https://github.com/Devolutions/IronRDP/pull/951(https://github.com/Devolutions/IronRDP/pull/957). Also, we should merge it not before https://github.com/Devolutions/devolutions-gateway/pull/1459.

fix(webapp): improve clipboard interaction for outdated versions of the Firefox browser

---

devolutions-session/src/dvc/env.rs
devolutions-session/src/dvc/mod.rs
devolutions-session/src/dvc/process.rs
devolutions-session/src/dvc/task.rs

fix(agent): improve ANSI escape codes suppressions in pwsh

---

devolutions-gateway/src/service.rs

The listener binding will be reattempted a set amount of time when a transient error is hit, such as "address already in use".
Issue: DGW-310

fix(dgw): retrial logic when binding the listeners

---

.github/workflows/release.yml

The Devolutions/actions repository was not checked out.

ci: fix SBOM upload
